\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/etc Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{The databases}
The databases are built in this Makefile even though the prerequisites
are actually made during the previous step in the algebra directory.
This allows us to use a simple wildcard to express the fact that
all of the algreba/*.nrlib/code.o files are required in order to build
the databases. If any if any of these are changed, the databases must
be re-built.
<<dbcomplete>>=
${MNT}/${SYS}/algebra/*.daase: ${INT}/algebra/*.nrlib/code.o
	@ echo 4 rebuilding databases...
	@ cp ${SRC}/doc/gloss.text ${INT}/algebra
	@ cp ${SRC}/doc/gloss.text ${INT}/algebra
	@ cp ${SRC}/doc/topics.data ${INT}/algebra
	@ cp ${SRC}/doc/topics.data ${INT}/algebra
	@ (cd ${INT}/algebra ; \
           echo ')lisp (make-databases "" nil)' | ${INTERPSYS} )
	@ cp -pr ${INT}/algebra/*.daase ${MNT}/${SYS}/algebra

@
\section{summary}
<<summary>>=
${LIB}/summary: ${IN}/summary
	@echo 2 making ${LIB}/summary from ${IN}/summary
	@cp ${IN}/summary ${LIB}/summary

@
\section{copyright}
<<copyright>>=
${LIB}/copyright: ${IN}/copyright
	@echo 3 making ${LIB}/copyright from ${IN}/copyright
	@cp ${IN}/copyright ${LIB}/copyright

@
\section{asq}
asq is a command line tool to ask questions about Axiom's domains,
packages, and categories.

\begin{verbatim}
asq -property searchkey
 property is one of the following flags: (all is the default)
  (ab)    abbreviation          (an)    ancestors
  (at)    attributes            (ca cc) constructorcategory
  (cf fo) constructorform       (ck ki) constructorkind
  (cm)    constructormodemap    (con)   constructor
  (cos)   cosig                 (de)    defaultdomain
  (dom)   domain                (doc)   documentation
  (mo)    modemaps              (ni)    niladic
  (ob)    object                (op)    operationalist
  (pr)    predicates            (so)    sourcefile
searchkey can be either a domain or its abbreviation.
 e.g. %s -so Integer
 will give the source file name written to stdout
\end{verbatim}
<<asq>>=
${OUT}/asq: ${MID}/asq.c
	@echo 4 making ${OUT}/asq from ${MID}/asq.c
	@( cd ${MID} ; ${CC} ${CCF} -o asq asq.c )
	@cp ${MID}/asq ${OUT}

${MID}/asq.c: ${IN}/asq.c.pamphlet
	@echo 5 making ${OUT}/asq from ${MID}/asq.c
	@( cd ${MID} ; \
	  ${TANGLE} ${IN}/asq.c.pamphlet >asq.c )

@
<<*>>=
IN=${SRC}/etc
MID=${OBJ}/${SYS}/etc
OUT=${MNT}/${SYS}/bin
LIB=${MNT}/${SYS}/lib
DOC=${INT}/doc/src/etc
INTERPSYS=${OBJ}/${SYS}/bin/interpsys

all: ${MNT}/${SYS}/algebra/*.daase ${OUT}/asq ${LIB}/summary \
     ${LIB}/copyright 
	@echo 6 finished ${IN}

<<dbcomplete>>
<<asq>>
<<summary>>
<<copyright>>
document:
	@echo 7 documenting ${IN}
	@( cd ${DOC} ; \
	  cp ${IN}/asq.c.pamphlet . ; \
	  ${DOCUMENT} ${NOISE} asq.c ; \
	  rm asq.c.pamphlet )

clean:
	@echo 8 cleaning ${SRC}/etc
	@rm -rf ${MID}
	@rm -rf ${DOC}
	@rm -f Makefile Makefile.dvi

@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
