\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/lib Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{environment}
<<environment>>=
IN=${SRC}/lib
MID=${INT}/lib
OUT=${OBJ}/${SYS}/lib
DOCINT=${INT}/doc/src/lib
DOCMNT=${MNT}/${SYS}/doc/src/lib
INC= ${SRC}/include

AR=	${OUT}/bsdsignal.o  ${OUT}/cursor.o ${OUT}/edin.o     \
        ${OUT}/fnct-key.o   ${OUT}/halloc.o ${OUT}/openpty.o  \
        ${OUT}/pixmap.o     ${OUT}/prt.o    ${OUT}/sockio-c.o \
        ${OUT}/spadcolors.o ${OUT}/util.o   ${OUT}/wct.o      \
        ${OUT}/XDither.o    ${OUT}/XShade.o ${OUT}/XSpadFill.o 

OTHER=	${OUT}/cfuns-c.o ${OUT}/hash.o

DOCFILES=\
 ${DOCMNT}/bsdsignal.c.dvi  ${DOCMNT}/cfuns-c.c.dvi  ${DOCMNT}/cursor.c.dvi \
 ${DOCMNT}/edin.c.dvi       ${DOCMNT}/fnct-key.c.dvi ${DOCMNT}/halloc.c.dvi \
 ${DOCMNT}/hash.c.dvi       ${DOCMNT}/openpty.c.dvi  ${DOCMNT}/pixmap.c.dvi \
 ${DOCMNT}/prt.c.dvi        ${DOCMNT}/sockio-c.c.dvi ${DOCMNT}/Makefile.dvi \
 ${DOCMNT}/spadcolors.c.dvi ${DOCMNT}/util.c.dvi     ${DOCMNT}/wct.c.dvi    \
 ${DOCMNT}/XDither.c.dvi    ${DOCMNT}/XShade.c.dvi   ${DOCMNT}/XSpadFill.c.dvi 

@
\section{Files}
\subsection{bsdsignal.c \cite{1}}

<<bsdsignal>>=
${MID}/bsdsignal.c: ${IN}/bsdsignal.c.pamphlet
	@echo 1 making ${MID}/bsdsignal.c from ${IN}/bsdsignal.c.pamphlet
	@${TANGLE} bsdsignal.c.pamphlet >${MID}/bsdsignal.c

${OUT}/bsdsignal.o: ${MID}/bsdsignal.c
	@echo 2 making ${OUT}/bsdsignal.o from ${MID}/bsdsignal.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/bsdsignal.c )

${DOCINT}/bsdsignal.c.dvi: ${IN}/bsdsignal.c.pamphlet 
	@echo 3 making ${DOCINT}/bsdsignal.c.dvi from ${IN}/bsdsignal.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/bsdsignal.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} bsdsignal.c ; \
	rm -f ${DOCINT}/bsdsignal.c.pamphlet ; \
	rm -f ${DOCINT}/bsdsignal.c.tex ; \
	rm -f ${DOCINT}/bsdsignal.c )

${DOCMNT}/bsdsignal.c.dvi: ${DOCINT}/bsdsignal.c.dvi 
	@echo 4 making ${DOCMNT}/bsdsignal.c.dvi from ${DOCINT}/bsdsignal.c.dvi
	@cp ${DOCINT}/bsdsignal.c.dvi ${DOCMNT}/bsdsignal.c.dvi 

@

\subsection{cfuns-c.c \cite{2}}
The cfuns-c file contains socket primitives used by Axiom.
They must be linked into and visible from the inferior lisp.
In GCL this link happens thru setting a shell variable called
{\bf EXTRAS} in the {\bf h/386-linux.defs} file. This file
gets included as part of the final system build of GCL.

<<cfuns-c>>=
${MID}/cfuns-c.c: ${IN}/cfuns-c.c.pamphlet
	@echo 5 making ${MID}/cfuns-c.c from ${IN}/cfuns-c.c.pamphlet
	@${TANGLE} cfuns-c.c.pamphlet >${MID}/cfuns-c.c

${OUT}/cfuns-c.o: ${MID}/cfuns-c.c
	@echo 6 making ${OUT}/cfuns-c.o from ${MID}/cfuns-c.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/cfuns-c.c )

${DOCINT}/cfuns-c.c.dvi: ${IN}/cfuns-c.c.pamphlet 
	@echo 7 making ${DOCINT}/cfuns-c.c.dvi from ${IN}/cfuns-c.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/cfuns-c.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} cfuns-c.c ; \
	rm -f ${DOCINT}/cfuns-c.c.pamphlet ; \
	rm -f ${DOCINT}/cfuns-c.c.tex ; \
	rm -f ${DOCINT}/cfuns-c.c )

${DOCMNT}/cfuns-c.c.dvi: ${DOCINT}/cfuns-c.c.dvi
	@echo 8 making ${DOCMNT}/cfuns-c.c.dvi from ${DOCINT}/cfuns-c.c.dvi
	@cp ${DOCINT}/cfuns-c.c.dvi ${DOCMNT}/cfuns-c.c.dvi 

@
\subsection{cursor.c \cite{3}}
<<cursor>>=
${MID}/cursor.c: ${IN}/cursor.c.pamphlet
	@echo 9 making ${MID}/cursor.c from ${IN}/cursor.c.pamphlet
	@${TANGLE} cursor.c.pamphlet >${MID}/cursor.c

${OUT}/cursor.o: ${MID}/cursor.c
	@echo 10 making ${OUT}/cursor.o from ${MID}/cursor.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/cursor.c )

${DOCINT}/cursor.c.dvi: ${IN}/cursor.c.pamphlet 
	@echo 11 making ${DOCINT}/cursor.c.dvi from ${IN}/cursor.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/cursor.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} cursor.c ; \
	rm -f ${DOCINT}/cursor.c.pamphlet ; \
	rm -f ${DOCINT}/cursor.c.tex ; \
	rm -f ${DOCINT}/cursor.c )

${DOCMNT}/cursor.c.dvi: ${DOCINT}/cursor.c.dvi
	@echo 12 making ${DOCMNT}/cursor.c.dvi from ${DOCINT}/cursor.c.dvi
	@cp ${DOCINT}/cursor.c.dvi ${DOCMNT}/cursor.c.dvi 

@
\subsection{edin.c \cite{4}}
<<edin>>=
${MID}/edin.c: ${IN}/edin.c.pamphlet
	@echo 13 making ${MID}/edin.c from ${IN}/edin.c.pamphlet
	@${TANGLE} edin.c.pamphlet >${MID}/edin.c

${OUT}/edin.o: ${MID}/edin.c
	@echo 14 making ${OUT}/edin.o from ${MID}/edin.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/edin.c )

${DOCINT}/edin.c.dvi: ${IN}/edin.c.pamphlet 
	@echo 15 making ${DOCINT}/edin.c.dvi from ${IN}/edin.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/edin.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} edin.c ; \
	rm -f ${DOCINT}/edin.c.pamphlet ; \
	rm -f ${DOCINT}/edin.c.tex ; \
	rm -f ${DOCINT}/edin.c )

${DOCMNT}/edin.c.dvi: ${DOCINT}/edin.c.dvi
	@echo 16 making ${DOCMNT}/edin.c.dvi from ${DOCINT}/edin.c.dvi
	@cp ${DOCINT}/edin.c.dvi ${DOCMNT}/edin.c.dvi 

@
\subsection{fnct-key.c \cite{5}}
<<fnctkey>>=
${MID}/fnct-key.c: ${IN}/fnct-key.c.pamphlet
	@echo 17 making ${MID}/fnct-key.c from ${IN}/fnct-key.c.pamphlet
	@${TANGLE} fnct-key.c.pamphlet >${MID}/fnct-key.c

${OUT}/fnct-key.o: ${MID}/fnct-key.c
	@echo 18 making ${OUT}/fnct-key.o from ${MID}/fnct-key.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/fnct-key.c )

${DOCINT}/fnct-key.c.dvi: ${IN}/fnct-key.c.pamphlet 
	@echo 19 making ${DOCINT}/fnct-key.c.dvi from ${IN}/fnct-key.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/fnct-key.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} fnct-key.c ; \
	rm -f ${DOCINT}/fnct-key.c.pamphlet ; \
	rm -f ${DOCINT}/fnct-key.c.tex ; \
	rm -f ${DOCINT}/fnct-key.c )

${DOCMNT}/fnct-key.c.dvi: ${DOCINT}/fnct-key.c.dvi
	@echo 20 making ${DOCMNT}/fnct-key.c.dvi from ${DOCINT}/fnct-key.c.dvi
	@cp ${DOCINT}/fnct-key.c.dvi ${DOCMNT}/fnct-key.c.dvi 

@
\subsection{halloc.c \cite{6}}
<<halloc>>=
${MID}/halloc.c: ${IN}/halloc.c.pamphlet
	@echo 21 making ${MID}/halloc.c from ${IN}/halloc.c.pamphlet
	@${TANGLE} halloc.c.pamphlet >${MID}/halloc.c

${OUT}/halloc.o: ${MID}/halloc.c
	@echo 22 making ${OUT}/halloc.o from ${MID}/halloc.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/halloc.c )

${DOCINT}/halloc.c.dvi: ${IN}/halloc.c.pamphlet 
	@echo 23 making ${DOCINT}/halloc.c.dvi from ${IN}/halloc.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/halloc.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} halloc.c ; \
	rm -f ${DOCINT}/halloc.c.pamphlet ; \
	rm -f ${DOCINT}/halloc.c.tex ; \
	rm -f ${DOCINT}/halloc.c )

${DOCMNT}/halloc.c.dvi: ${DOCINT}/halloc.c.dvi
	@echo 24 making ${DOCMNT}/halloc.c.dvi from ${DOCINT}/halloc.c.dvi
	@cp ${DOCINT}/halloc.c.dvi ${DOCMNT}/halloc.c.dvi 

@
\subsection{hash.c \cite{6}}
This a a string-based hash table that is used both in the graph
and hyper functions. It is included here because we need it built
earlier so the graph and hyper routines can refer to it.
<<hash>>=
${MID}/hash.c: ${IN}/hash.c.pamphlet
	@echo 25 making ${MID}/hash.c from ${IN}/hash.c.pamphlet
	@${TANGLE} hash.c.pamphlet >${MID}/hash.c

${OUT}/hash.o: ${MID}/hash.c
	@echo 26 making ${OUT}/hash.o from ${MID}/hash.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/hash.c )

${DOCINT}/hash.c.dvi: ${IN}/hash.c.pamphlet 
	@echo 27 making ${DOCINT}/hash.c.dvi from ${IN}/hash.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/hash.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} hash.c ; \
	rm -f ${DOCINT}/hash.c.pamphlet ; \
	rm -f ${DOCINT}/hash.c.tex ; \
	rm -f ${DOCINT}/hash.c )

${DOCMNT}/hash.c.dvi: ${DOCINT}/hash.c.dvi
	@echo 28 making ${DOCMNT}/hash.c.dvi from ${DOCINT}/hash.c.dvi
	@cp ${DOCINT}/hash.c.dvi ${DOCMNT}/hash.c.dvi 

@
\subsection{openpty.c \cite{7}}
<<openpty>>=
${MID}/openpty.c: ${IN}/openpty.c.pamphlet
	@echo 29 making ${MID}/openpty.c from ${IN}/openpty.c.pamphlet
	@${TANGLE} openpty.c.pamphlet >${MID}/openpty.c

${OUT}/openpty.o: ${MID}/openpty.c
	@echo 30 making ${OUT}/openpty.o from ${MID}/openpty.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/openpty.c )

${DOCINT}/openpty.c.dvi: ${IN}/openpty.c.pamphlet 
	@echo 31 making ${DOCINT}/openpty.c.dvi from ${IN}/openpty.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/openpty.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} openpty.c ; \
	rm -f ${DOCINT}/openpty.c.pamphlet ; \
	rm -f ${DOCINT}/openpty.c.tex ; \
	rm -f ${DOCINT}/openpty.c )

${DOCMNT}/openpty.c.dvi: ${DOCINT}/openpty.c.dvi
	@echo 32 making ${DOCMNT}/openpty.c.dvi from ${DOCINT}/openpty.c.dvi
	@cp ${DOCINT}/openpty.c.dvi ${DOCMNT}/openpty.c.dvi 

@
\subsection{pixmap.c \cite{8}}
<<pixmap>>=
${MID}/pixmap.c: ${IN}/pixmap.c.pamphlet
	@echo 33 making ${MID}/pixmap.c from ${IN}/pixmap.c.pamphlet
	@${TANGLE} pixmap.c.pamphlet >${MID}/pixmap.c

${OUT}/pixmap.o: ${MID}/pixmap.c
	@echo 34 making ${OUT}/pixmap.o from ${MID}/pixmap.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/pixmap.c )

${DOCINT}/pixmap.c.dvi: ${IN}/pixmap.c.pamphlet 
	@echo 35 making ${DOCINT}/pixmap.c.dvi from ${IN}/pixmap.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/pixmap.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} pixmap.c ; \
	rm -f ${DOCINT}/pixmap.c.pamphlet ; \
	rm -f ${DOCINT}/pixmap.c.tex ; \
	rm -f ${DOCINT}/pixmap.c )

${DOCMNT}/pixmap.c.dvi: ${DOCINT}/pixmap.c.dvi
	@echo 36 making ${DOCMNT}/pixmap.c.dvi from ${DOCINT}/pixmap.c.dvi
	@cp ${DOCINT}/pixmap.c.dvi ${DOCMNT}/pixmap.c.dvi 

@
\subsection{prt.c \cite{9}}
<<prt>>=
${MID}/prt.c: ${IN}/prt.c.pamphlet
	@echo 37 making ${MID}/prt.c from ${IN}/prt.c.pamphlet
	@${TANGLE} prt.c.pamphlet >${MID}/prt.c

${OUT}/prt.o: ${MID}/prt.c
	@echo 38 making ${OUT}/prt.o from ${MID}/prt.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/prt.c )

${DOCINT}/prt.c.dvi: ${IN}/prt.c.pamphlet 
	@echo 39 making ${DOCINT}/prt.c.dvi from ${IN}/prt.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/prt.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} prt.c ; \
	rm -f ${DOCINT}/prt.c.pamphlet ; \
	rm -f ${DOCINT}/prt.c.tex ; \
	rm -f ${DOCINT}/prt.c )

${DOCMNT}/prt.c.dvi: ${DOCINT}/prt.c.dvi
	@echo 40 making ${DOCMNT}/prt.c.dvi from ${DOCINT}/prt.c.dvi
	@cp ${DOCINT}/prt.c.dvi ${DOCMNT}/prt.c.dvi 

@
\subsection{sockio-c.c \cite{10}}
The sockio-c file contains socket primitives used by Axiom.
They must be linked into and visible from the inferior lisp.
In GCL this link happens thru setting a shell variable called
{\bf EXTRAS} in the {\bf h/386-linux.defs} file. This file
gets included as part of the final system build of GCL.

<<sockio-c>>=
${MID}/sockio-c.c: ${IN}/sockio-c.c.pamphlet
	@echo 41 making ${MID}/sockio-c.c from ${IN}/sockio-c.c.pamphlet
	@${TANGLE} sockio-c.c.pamphlet >${MID}/sockio-c.c

${OUT}/sockio-c.o: ${MID}/sockio-c.c
	@echo 42 making ${OUT}/sockio-c.o from ${MID}/sockio-c.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/sockio-c.c )

${DOCINT}/sockio-c.c.dvi: ${IN}/sockio-c.c.pamphlet 
	@echo 43 making ${DOCINT}/sockio-c.c.dvi from ${IN}/sockio-c.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/sockio-c.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} sockio-c.c ; \
	rm -f ${DOCINT}/sockio-c.c.pamphlet ; \
	rm -f ${DOCINT}/sockio-c.c.tex ; \
	rm -f ${DOCINT}/sockio-c.c )

${DOCMNT}/sockio-c.c.dvi: ${DOCINT}/sockio-c.c.dvi
	@echo 44 making ${DOCMNT}/sockio-c.c.dvi from ${DOCINT}/sockio-c.c.dvi
	@cp ${DOCINT}/sockio-c.c.dvi ${DOCMNT}/sockio-c.c.dvi 

@
\subsection{spadcolors.c \cite{11}}
<<spadcolors>>=
${MID}/spadcolors.c: ${IN}/spadcolors.c.pamphlet
	@echo 45 making ${MID}/spadcolors.c from ${IN}/spadcolors.c.pamphlet
	@${TANGLE} spadcolors.c.pamphlet >${MID}/spadcolors.c

${OUT}/spadcolors.o: ${MID}/spadcolors.c
	@echo 46 making ${OUT}/spadcolors.o from ${MID}/spadcolors.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/spadcolors.c )

${DOCINT}/spadcolors.c.dvi: ${IN}/spadcolors.c.pamphlet 
	@echo 47 making ${DOCINT}/spadcolors.c.dvi from \
          ${IN}/spadcolors.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/spadcolors.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} spadcolors.c ; \
	rm -f ${DOCINT}/spadcolors.c.pamphlet ; \
	rm -f ${DOCINT}/spadcolors.c.tex ; \
	rm -f ${DOCINT}/spadcolors.c )

${DOCMNT}/spadcolors.c.dvi: ${DOCINT}/spadcolors.c.dvi
	@echo 48 making ${DOCMNT}/spadcolors.c.dvi from ${DOCINT}/spadcolors.c.dvi
	@cp ${DOCINT}/spadcolors.c.dvi ${DOCMNT}/spadcolors.c.dvi 

@
\subsection{util.c \cite{12}}
<<util>>=
${MID}/util.c: ${IN}/util.c.pamphlet
	@echo 49 making ${MID}/util.c from ${IN}/util.c.pamphlet
	@${TANGLE} util.c.pamphlet >${MID}/util.c

${OUT}/util.o: ${MID}/util.c
	@echo 50 making ${OUT}/util.o from ${MID}/util.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/util.c )

${DOCINT}/util.c.dvi: ${IN}/util.c.pamphlet 
	@echo 51 making ${DOCINT}/util.c.dvi from ${IN}/util.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/util.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} util.c ; \
	rm -f ${DOCINT}/util.c.pamphlet ; \
	rm -f ${DOCINT}/util.c.tex ; \
	rm -f ${DOCINT}/util.c )

${DOCMNT}/util.c.dvi: ${DOCINT}/util.c.dvi
	@echo 52 making ${DOCMNT}/util.c.dvi from ${DOCINT}/util.c.dvi
	@cp ${DOCINT}/util.c.dvi ${DOCMNT}/util.c.dvi 

@
\subsection{wct.c \cite{13}}
<<wct>>=
${MID}/wct.c: ${IN}/wct.c.pamphlet
	@echo 53 making ${MID}/wct.c from ${IN}/wct.c.pamphlet
	@${TANGLE} wct.c.pamphlet >${MID}/wct.c

${OUT}/wct.o: ${MID}/wct.c
	@echo 54 making ${OUT}/wct.o from ${MID}/wct.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/wct.c )

${DOCINT}/wct.c.dvi: ${IN}/wct.c.pamphlet 
	@echo 55 making ${DOCINT}/wct.c.dvi from ${IN}/wct.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/wct.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} wct.c ; \
	rm -f ${DOCINT}/wct.c.pamphlet ; \
	rm -f ${DOCINT}/wct.c.tex ; \
	rm -f ${DOCINT}/wct.c )

${DOCMNT}/wct.c.dvi: ${DOCINT}/wct.c.dvi
	@echo 56 making ${DOCMNT}/wct.c.dvi from ${DOCINT}/wct.c.dvi
	@cp ${DOCINT}/wct.c.dvi ${DOCMNT}/wct.c.dvi 

@
\subsection{XDither.c \cite{14}}
<<XDither>>=
${MID}/XDither.c: ${IN}/XDither.c.pamphlet
	@echo 57 making ${MID}/XDither.c from ${IN}/XDither.c.pamphlet
	@${TANGLE} XDither.c.pamphlet >${MID}/XDither.c

${OUT}/XDither.o: ${MID}/XDither.c
	@echo 58 making ${OUT}/XDither.o from ${MID}/XDither.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/XDither.c )

${DOCINT}/XDither.c.dvi: ${IN}/XDither.c.pamphlet 
	@echo 59 making ${DOCINT}/XDither.c.dvi from ${IN}/XDither.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/XDither.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} XDither.c ; \
	rm -f ${DOCINT}/XDither.c.pamphlet ; \
	rm -f ${DOCINT}/XDither.c.tex ; \
	rm -f ${DOCINT}/XDither.c )

${DOCMNT}/XDither.c.dvi: ${DOCINT}/XDither.c.dvi
	@echo 60 making ${DOCMNT}/XDither.c.dvi from ${DOCINT}/XDither.c.dvi
	@cp ${DOCINT}/XDither.c.dvi ${DOCMNT}/XDither.c.dvi 

@
\subsection{XShade.c \cite{15}}
<<XShade>>=
${MID}/XShade.c: ${IN}/XShade.c.pamphlet
	@echo 61 making ${MID}/XShade.c from ${IN}/XShade.c.pamphlet
	@${TANGLE} XShade.c.pamphlet >${MID}/XShade.c

${OUT}/XShade.o: ${MID}/XShade.c
	@echo 62 making ${OUT}/XShade.o from ${MID}/XShade.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/XShade.c )

${DOCINT}/XShade.c.dvi: ${IN}/XShade.c.pamphlet 
	@echo 63 making ${DOCINT}/XShade.c.dvi from ${IN}/XShade.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/XShade.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} XShade.c ; \
	rm -f ${DOCINT}/XShade.c.pamphlet ; \
	rm -f ${DOCINT}/XShade.c.tex ; \
	rm -f ${DOCINT}/XShade.c )

${DOCMNT}/XShade.c.dvi: ${DOCINT}/XShade.c.dvi
	@echo 64 making ${DOCMNT}/XShade.c.dvi from ${DOCINT}/XShade.c.dvi
	@cp ${DOCINT}/XShade.c.dvi ${DOCMNT}/XShade.c.dvi 

@
\subsection{XSpadFill.c \cite{16}}
<<XSpadFill>>=
${MID}/XSpadFill.c: ${IN}/XSpadFill.c.pamphlet
	@echo 65 making ${MID}/XSpadFill.c from ${IN}/XSpadFill.c.pamphlet
	@${TANGLE} XSpadFill.c.pamphlet >${MID}/XSpadFill.c

${OUT}/XSpadFill.o: ${MID}/XSpadFill.c
	@echo 66 making ${OUT}/XSpadFill.o from ${MID}/XSpadFill.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/XSpadFill.c )

${DOCINT}/XSpadFill.c.dvi: ${IN}/XSpadFill.c.pamphlet 
	@echo 67 making ${DOCINT}/XSpadFill.c.dvi from ${IN}/XSpadFill.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/XSpadFill.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} XSpadFill.c ; \
	rm -f ${DOCINT}/XSpadFill.c.pamphlet ; \
	rm -f ${DOCINT}/XSpadFill.c.tex ; \
	rm -f ${DOCINT}/XSpadFill.c )

${DOCMNT}/XSpadFill.c.dvi: ${DOCINT}/XSpadFill.c.dvi
	@echo 68 making ${DOCMNT}/XSpadFill.c.dvi from ${DOCINT}/XSpadFill.c.dvi
	@cp ${DOCINT}/XSpadFill.c.dvi ${DOCMNT}/XSpadFill.c.dvi 

@
\section{The document stanza}
<<document>>=
document: ${DOCFILES}
	@echo 69 documenting ${IN}

@
\section{The clean stanza}
<<clean>>=
clean:
	@echo 70 cleaning ${IN}
	@rm -rf ${MID} ${OUT} ${DOCINT} ${DOCMNT}
	@rm -f Makefile Makefile.dvi

@
\subsection{Makefile documentation}
<<Makefile.dvi>>=
${DOCMNT}/Makefile.dvi: ${IN}/Makefile.dvi
	@echo 71 making ${DOCMNT}/Makefile.dvi from ${IN}/Makefile.dvi
	@cp ${IN}/Makefile.dvi ${DOCMNT}/Makefile.dvi 

@
<<*>>=
<<environment>>

all: ${OUT}/libspad.a ${OTHER} ${DOCFILES}
	@echo 72 finished making ${IN}

${OUT}/libspad.a: ${AR} 
	@echo 73 making ${OUT}/libspad.a
	@(cd ${OUT} ; \
	ar ru ${OUT}/libspad.a ${AR} ; \
	${RANLIB} ${OBJ}/${SYS}/lib/libspad.a )

<<Makefile.dvi>>
<<bsdsignal>>
<<cfuns-c>>
<<cursor>>
<<edin>>
<<fnctkey>>
<<halloc>>
<<hash>>
<<openpty>>
<<pixmap>>
<<prt>>
<<sockio-c>>
<<spadcolors>>
<<util>>
<<wct>>
<<XDither>>
<<XShade>>
<<XSpadFill>>
<<document>>
<<clean>>
@

\eject
\begin{thebibliography}{99}
\bibitem{1} {\$SPAD/src/lib/bsdssignal.c.pamphlet}
\bibitem{2} {\$SPAD/src/lib/cfuns-c.c.pamphlet}
\bibitem{3} {\$SPAD/src/lib/cursor.c.pamphlet}
\bibitem{4} {\$SPAD/src/lib/edin.c.pamphlet}
\bibitem{5} {\$SPAD/src/lib/fnct-key.c.pamphlet}
\bibitem{6} {\$SPAD/src/lib/halloc.c.pamphlet}
\bibitem{7} {\$SPAD/src/lib/openpty.c.pamphlet}
\bibitem{8} {\$SPAD/src/lib/pixmap.c.pamphlet}
\bibitem{9} {\$SPAD/src/lib/prt.c.pamphlet}
\bibitem{10} {\$SPAD/src/lib/sockio-c.c.pamphlet}
\bibitem{11} {\$SPAD/src/lib/spadcolors.c.pamphlet}
\bibitem{12} {\$SPAD/src/lib/util.c.pamphlet}
\bibitem{13} {\$SPAD/src/lib/wct.c.pamphlet}
\bibitem{14} {\$SPAD/src/lib/XDither.c.pamphlet}
\bibitem{15} {\$SPAD/src/lib/XShade.c.pamphlet}
\bibitem{16} {\$SPAD/src/lib/XSpadFill.c.pamphlet}
\end{thebibliography}
\end{document}
