\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/lib Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{environment}
\begin{chunk}{environment}
IN=${SRC}/lib
MID=${INT}/lib
OUT=${OBJ}/${SYS}/lib
DOCINT=${INT}/doc/src/lib
DOCMNT=${MNT}/${SYS}/doc/src/lib
INC= ${SRC}/include

AR=	${OUT}/bsdsignal.o  ${OUT}/cursor.o ${OUT}/edin.o     \
        ${OUT}/fnct-key.o   ${OUT}/halloc.o ${OUT}/openpty.o  \
        ${OUT}/pixmap.o     ${OUT}/prt.o    ${OUT}/sockio-c.o \
        ${OUT}/spadcolors.o ${OUT}/util.o   ${OUT}/wct.o      \
        ${OUT}/xdither.o    ${OUT}/xshade.o ${OUT}/xspadfill.o 

OTHER=	${OUT}/cfuns-c.o ${OUT}/hash.o

DOCFILES=\
 ${DOCMNT}/bsdsignal.c.pdf  ${DOCMNT}/cfuns-c.c.pdf  ${DOCMNT}/cursor.c.pdf \
 ${DOCMNT}/edin.c.pdf       ${DOCMNT}/fnct-key.c.pdf ${DOCMNT}/halloc.c.pdf \
 ${DOCMNT}/hash.c.pdf       ${DOCMNT}/openpty.c.pdf  ${DOCMNT}/pixmap.c.pdf \
 ${DOCMNT}/prt.c.pdf        ${DOCMNT}/sockio-c.c.pdf ${DOCMNT}/Makefile.pdf \
 ${DOCMNT}/spadcolors.c.pdf ${DOCMNT}/util.c.pdf     ${DOCMNT}/wct.c.pdf    \
 ${DOCMNT}/xdither.c.pdf    ${DOCMNT}/xshade.c.pdf   ${DOCMNT}/xspadfill.c.pdf 

\end{chunk}
\section{Files}
\subsection{bsdsignal.c \cite{1}}

\begin{chunk}{bsdsignal}
${MID}/bsdsignal.c: ${IN}/bsdsignal.c.pamphlet
	@echo sl01 making ${MID}/bsdsignal.c from ${IN}/bsdsignal.c.pamphlet
	@${BOOKS}/tangle bsdsignal.c.pamphlet >${MID}/bsdsignal.c

${OUT}/bsdsignal.o: ${MID}/bsdsignal.c
	@echo sl02 making ${OUT}/bsdsignal.o from ${MID}/bsdsignal.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/bsdsignal.c )

${DOCINT}/bsdsignal.c.pdf: ${IN}/bsdsignal.c.pamphlet 
	@echo sl03 making ${DOCINT}/bsdsignal.c.pdf \
                     from ${IN}/bsdsignal.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/bsdsignal.c.pamphlet ${DOCINT} ; \
	${EXTRACT} bsdsignal.c.pamphlet ; \
	rm -f ${DOCINT}/bsdsignal.c.pamphlet ; \
	rm -f ${DOCINT}/bsdsignal.c.tex ; \
	rm -f ${DOCINT}/bsdsignal.c )

${DOCMNT}/bsdsignal.c.pdf: ${DOCINT}/bsdsignal.c.pdf
	@echo sl12 making ${DOCMNT}/bsdsignal.c.pdf from \
                          ${DOCINT}/bsdsignal.c.pdf
	@cp ${DOCINT}/bsdsignal.c.pdf ${DOCMNT}/bsdsignal.c.pdf 

\end{chunk}

\subsection{cfuns-c.c \cite{2}}
The cfuns-c file contains socket primitives used by Axiom.
They must be linked into and visible from the inferior lisp.
In GCL this link happens thru setting a shell variable called
{\bf EXTRAS} in the {\bf h/386-linux.defs} file. This file
gets included as part of the final system build of GCL.

\begin{chunk}{cfuns-c}
${MID}/cfuns-c.c: ${IN}/cfuns-c.c.pamphlet
	@echo sl05 making ${MID}/cfuns-c.c from ${IN}/cfuns-c.c.pamphlet
	@${BOOKS}/tangle cfuns-c.c.pamphlet >${MID}/cfuns-c.c

${OUT}/cfuns-c.o: ${MID}/cfuns-c.c
	@echo sl06 making ${OUT}/cfuns-c.o from ${MID}/cfuns-c.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/cfuns-c.c )

${DOCINT}/cfuns-c.c.pdf: ${IN}/cfuns-c.c.pamphlet 
	@echo sl07 making ${DOCINT}/cfuns-c.c.pdf from ${IN}/cfuns-c.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/cfuns-c.c.pamphlet ${DOCINT} ; \
	${EXTRACT} cfuns-c.c.pamphlet ; \
	rm -f ${DOCINT}/cfuns-c.c.pamphlet ; \
	rm -f ${DOCINT}/cfuns-c.c.tex ; \
	rm -f ${DOCINT}/cfuns-c.c )

${DOCMNT}/cfuns-c.c.pdf: ${DOCINT}/cfuns-c.c.pdf
	@echo sl04 making ${DOCMNT}/cfuns-c.c.pdf from \
                          ${IN}/cfuns-c.c.pamphlet
	@cp ${DOCINT}/cfuns-c.c.pdf ${DOCMNT}/cfuns-c.c.pdf 

\end{chunk}
\subsection{cursor.c \cite{3}}
\begin{chunk}{cursor}
${MID}/cursor.c: ${IN}/cursor.c.pamphlet
	@echo sl09 making ${MID}/cursor.c from ${IN}/cursor.c.pamphlet
	@${BOOKS}/tangle cursor.c.pamphlet >${MID}/cursor.c

${OUT}/cursor.o: ${MID}/cursor.c
	@echo sl10 making ${OUT}/cursor.o from ${MID}/cursor.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/cursor.c )

${DOCINT}/cursor.c.pdf: ${IN}/cursor.c.pamphlet 
	@echo sl11 making ${DOCINT}/cursor.c.pdf from ${IN}/cursor.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/cursor.c.pamphlet ${DOCINT} ; \
	${EXTRACT} cursor.c.pamphlet ; \
	rm -f ${DOCINT}/cursor.c.pamphlet ; \
	rm -f ${DOCINT}/cursor.c.tex ; \
	rm -f ${DOCINT}/cursor.c )

${DOCMNT}/cursor.c.pdf: ${DOCINT}/cursor.c.pdf
	@echo sl12 making ${DOCMNT}/cursor.c.pdf from ${DOCINT}/cursor.c.pdf
	@cp ${DOCINT}/cursor.c.pdf ${DOCMNT}/cursor.c.pdf 

\end{chunk}
\subsection{edin.c \cite{4}}
\begin{chunk}{edin}
${MID}/edin.c: ${IN}/edin.c.pamphlet
	@echo sl13 making ${MID}/edin.c from ${IN}/edin.c.pamphlet
	@${BOOKS}/tangle edin.c.pamphlet >${MID}/edin.c

${OUT}/edin.o: ${MID}/edin.c
	@echo sl14 making ${OUT}/edin.o from ${MID}/edin.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/edin.c )

${DOCINT}/edin.c.pdf: ${IN}/edin.c.pamphlet 
	@echo sl15 making ${DOCINT}/edin.c.pdf from ${IN}/edin.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/edin.c.pamphlet ${DOCINT} ; \
	${EXTRACT} edin.c.pamphlet ; \
	rm -f ${DOCINT}/edin.c.pamphlet ; \
	rm -f ${DOCINT}/edin.c.tex ; \
	rm -f ${DOCINT}/edin.c )

${DOCMNT}/edin.c.pdf: ${DOCINT}/edin.c.pdf
	@echo sl16 making ${DOCMNT}/edin.c.pdf from ${DOCINT}/edin.c.pdf
	@cp ${DOCINT}/edin.c.pdf ${DOCMNT}/edin.c.pdf 

\end{chunk}
\subsection{fnct-key.c \cite{5}}
\begin{chunk}{fnctkey}
${MID}/fnct-key.c: ${IN}/fnct-key.c.pamphlet
	@echo sl17 making ${MID}/fnct-key.c from ${IN}/fnct-key.c.pamphlet
	@${BOOKS}/tangle fnct-key.c.pamphlet >${MID}/fnct-key.c

${OUT}/fnct-key.o: ${MID}/fnct-key.c
	@echo sl18 making ${OUT}/fnct-key.o from ${MID}/fnct-key.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/fnct-key.c )

${DOCINT}/fnct-key.c.pdf: ${IN}/fnct-key.c.pamphlet 
	@echo sl19 making ${DOCINT}/fnct-key.c.pdf from ${IN}/fnct-key.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/fnct-key.c.pamphlet ${DOCINT} ; \
	${EXTRACT} fnct-key.c.pamphlet ; \
	rm -f ${DOCINT}/fnct-key.c.pamphlet ; \
	rm -f ${DOCINT}/fnct-key.c.tex ; \
	rm -f ${DOCINT}/fnct-key.c )

${DOCMNT}/fnct-key.c.pdf: ${DOCINT}/fnct-key.c.pdf
	@echo sl20 making ${DOCMNT}/fnct-key.c.pdf from ${DOCINT}/fnct-key.c.pdf
	@cp ${DOCINT}/fnct-key.c.pdf ${DOCMNT}/fnct-key.c.pdf 

\end{chunk}
\subsection{halloc.c \cite{6}}
\begin{chunk}{halloc}
${MID}/halloc.c: ${IN}/halloc.c.pamphlet
	@echo sl21 making ${MID}/halloc.c from ${IN}/halloc.c.pamphlet
	@${BOOKS}/tangle halloc.c.pamphlet >${MID}/halloc.c

${OUT}/halloc.o: ${MID}/halloc.c
	@echo sl22 making ${OUT}/halloc.o from ${MID}/halloc.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/halloc.c )

${DOCINT}/halloc.c.pdf: ${IN}/halloc.c.pamphlet 
	@echo sl23 making ${DOCINT}/halloc.c.pdf from ${IN}/halloc.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/halloc.c.pamphlet ${DOCINT} ; \
	${EXTRACT} halloc.c.pamphlet ; \
	rm -f ${DOCINT}/halloc.c.pamphlet ; \
	rm -f ${DOCINT}/halloc.c.tex ; \
	rm -f ${DOCINT}/halloc.c )

${DOCMNT}/halloc.c.pdf: ${DOCINT}/halloc.c.pdf
	@echo sl24 making ${DOCMNT}/halloc.c.pdf from ${DOCINT}/halloc.c.pdf
	@cp ${DOCINT}/halloc.c.pdf ${DOCMNT}/halloc.c.pdf 

\end{chunk}
\subsection{hash.c \cite{6}}
This a a string-based hash table that is used both in the graph
and hyper functions. It is included here because we need it built
earlier so the graph and hyper routines can refer to it.
\begin{chunk}{hash}
${MID}/hash.c: ${IN}/hash.c.pamphlet
	@echo sl25 making ${MID}/hash.c from ${IN}/hash.c.pamphlet
	@${BOOKS}/tangle hash.c.pamphlet >${MID}/hash.c

${OUT}/hash.o: ${MID}/hash.c
	@echo sl26 making ${OUT}/hash.o from ${MID}/hash.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/hash.c )

${DOCINT}/hash.c.pdf: ${IN}/hash.c.pamphlet 
	@echo sl27 making ${DOCINT}/hash.c.pdf from ${IN}/hash.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/hash.c.pamphlet ${DOCINT} ; \
	${EXTRACT} hash.c.pamphlet ; \
	rm -f ${DOCINT}/hash.c.pamphlet ; \
	rm -f ${DOCINT}/hash.c.tex ; \
	rm -f ${DOCINT}/hash.c )

${DOCMNT}/hash.c.pdf: ${DOCINT}/hash.c.pdf
	@echo sl28 making ${DOCMNT}/hash.c.pdf from ${DOCINT}/hash.c.pdf
	@cp ${DOCINT}/hash.c.pdf ${DOCMNT}/hash.c.pdf 

\end{chunk}
\subsection{openpty.c \cite{7}}
\begin{chunk}{openpty}
${MID}/openpty.c: ${IN}/openpty.c.pamphlet
	@echo sl29 making ${MID}/openpty.c from ${IN}/openpty.c.pamphlet
	@${BOOKS}/tangle openpty.c.pamphlet >${MID}/openpty.c

${OUT}/openpty.o: ${MID}/openpty.c
	@echo sl30 making ${OUT}/openpty.o from ${MID}/openpty.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/openpty.c )

${DOCINT}/openpty.c.pdf: ${IN}/openpty.c.pamphlet 
	@echo sl31 making ${DOCINT}/openpty.c.pdf from ${IN}/openpty.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/openpty.c.pamphlet ${DOCINT} ; \
	${EXTRACT} openpty.c.pamphlet ; \
	rm -f ${DOCINT}/openpty.c.pamphlet ; \
	rm -f ${DOCINT}/openpty.c.tex ; \
	rm -f ${DOCINT}/openpty.c )

${DOCMNT}/openpty.c.pdf: ${DOCINT}/openpty.c.pdf
	@echo sl32 making ${DOCMNT}/openpty.c.pdf from ${DOCINT}/openpty.c.pdf
	@cp ${DOCINT}/openpty.c.pdf ${DOCMNT}/openpty.c.pdf 

\end{chunk}
\subsection{pixmap.c \cite{8}}
\begin{chunk}{pixmap}
${MID}/pixmap.c: ${IN}/pixmap.c.pamphlet
	@echo sl33 making ${MID}/pixmap.c from ${IN}/pixmap.c.pamphlet
	@${BOOKS}/tangle pixmap.c.pamphlet >${MID}/pixmap.c

${OUT}/pixmap.o: ${MID}/pixmap.c
	@echo sl34 making ${OUT}/pixmap.o from ${MID}/pixmap.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/pixmap.c )

${DOCINT}/pixmap.c.pdf: ${IN}/pixmap.c.pamphlet 
	@echo sl35 making ${DOCINT}/pixmap.c.pdf from ${IN}/pixmap.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/pixmap.c.pamphlet ${DOCINT} ; \
	${EXTRACT} pixmap.c.pamphlet ; \
	rm -f ${DOCINT}/pixmap.c.pamphlet ; \
	rm -f ${DOCINT}/pixmap.c.tex ; \
	rm -f ${DOCINT}/pixmap.c )

${DOCMNT}/pixmap.c.pdf: ${DOCINT}/pixmap.c.pdf
	@echo sl36 making ${DOCMNT}/pixmap.c.pdf from ${DOCINT}/pixmap.c.pdf
	@cp ${DOCINT}/pixmap.c.pdf ${DOCMNT}/pixmap.c.pdf 

\end{chunk}
\subsection{prt.c \cite{9}}
\begin{chunk}{prt}
${MID}/prt.c: ${IN}/prt.c.pamphlet
	@echo sl37 making ${MID}/prt.c from ${IN}/prt.c.pamphlet
	@${BOOKS}/tangle prt.c.pamphlet >${MID}/prt.c

${OUT}/prt.o: ${MID}/prt.c
	@echo sl38 making ${OUT}/prt.o from ${MID}/prt.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/prt.c )

${DOCINT}/prt.c.pdf: ${IN}/prt.c.pamphlet 
	@echo sl39 making ${DOCINT}/prt.c.pdf from ${IN}/prt.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/prt.c.pamphlet ${DOCINT} ; \
	${EXTRACT} prt.c.pamphlet ; \
	rm -f ${DOCINT}/prt.c.pamphlet ; \
	rm -f ${DOCINT}/prt.c.tex ; \
	rm -f ${DOCINT}/prt.c )

${DOCMNT}/prt.c.pdf: ${DOCINT}/prt.c.pdf
	@echo sl40 making ${DOCMNT}/prt.c.pdf from ${DOCINT}/prt.c.pdf
	@cp ${DOCINT}/prt.c.pdf ${DOCMNT}/prt.c.pdf 

\end{chunk}
\subsection{sockio-c.c \cite{10}}
The sockio-c file contains socket primitives used by Axiom.
They must be linked into and visible from the inferior lisp.
In GCL this link happens thru setting a shell variable called
{\bf EXTRAS} in the {\bf h/386-linux.defs} file. This file
gets included as part of the final system build of GCL.

\begin{chunk}{sockio-c}
${MID}/sockio-c.c: ${IN}/sockio-c.c.pamphlet
	@echo sl41 making ${MID}/sockio-c.c from ${IN}/sockio-c.c.pamphlet
	@${BOOKS}/tangle sockio-c.c.pamphlet >${MID}/sockio-c.c

${OUT}/sockio-c.o: ${MID}/sockio-c.c
	@echo sl42 making ${OUT}/sockio-c.o from ${MID}/sockio-c.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/sockio-c.c )

${DOCINT}/sockio-c.c.pdf: ${IN}/sockio-c.c.pamphlet 
	@echo sl43 making ${DOCINT}/sockio-c.c.pdf from ${IN}/sockio-c.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/sockio-c.c.pamphlet ${DOCINT} ; \
	${EXTRACT} sockio-c.c.pamphlet ; \
	rm -f ${DOCINT}/sockio-c.c.pamphlet ; \
	rm -f ${DOCINT}/sockio-c.c.tex ; \
	rm -f ${DOCINT}/sockio-c.c )

${DOCMNT}/sockio-c.c.pdf: ${DOCINT}/sockio-c.c.pdf
	@echo sl44 making ${DOCMNT}/sockio-c.c.pdf from ${DOCINT}/sockio-c.c.pdf
	@cp ${DOCINT}/sockio-c.c.pdf ${DOCMNT}/sockio-c.c.pdf 

\end{chunk}
\subsection{spadcolors.c \cite{11}}
\begin{chunk}{spadcolors}
${MID}/spadcolors.c: ${IN}/spadcolors.c.pamphlet
	@echo sl45 making ${MID}/spadcolors.c from ${IN}/spadcolors.c.pamphlet
	@${BOOKS}/tangle spadcolors.c.pamphlet >${MID}/spadcolors.c

${OUT}/spadcolors.o: ${MID}/spadcolors.c
	@echo sl46 making ${OUT}/spadcolors.o from ${MID}/spadcolors.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/spadcolors.c )

${DOCINT}/spadcolors.c.pdf: ${IN}/spadcolors.c.pamphlet 
	@echo sl47 making ${DOCINT}/spadcolors.c.pdf from \
          ${IN}/spadcolors.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/spadcolors.c.pamphlet ${DOCINT} ; \
	${EXTRACT} spadcolors.c.pamphlet ; \
	rm -f ${DOCINT}/spadcolors.c.pamphlet ; \
	rm -f ${DOCINT}/spadcolors.c.tex ; \
	rm -f ${DOCINT}/spadcolors.c )

${DOCMNT}/spadcolors.c.pdf: ${DOCINT}/spadcolors.c.pdf
	@echo sl48 making ${DOCMNT}/spadcolors.c.pdf from ${DOCINT}/spadcolors.c.pdf
	@cp ${DOCINT}/spadcolors.c.pdf ${DOCMNT}/spadcolors.c.pdf

\end{chunk}
\subsection{util.c \cite{12}}
\begin{chunk}{util}
${MID}/util.c: ${IN}/util.c.pamphlet
	@echo sl49 making ${MID}/util.c from ${IN}/util.c.pamphlet
	@${BOOKS}/tangle util.c.pamphlet >${MID}/util.c

${OUT}/util.o: ${MID}/util.c
	@echo sl50 making ${OUT}/util.o from ${MID}/util.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/util.c )

${DOCINT}/util.c.pdf: ${IN}/util.c.pamphlet 
	@echo sl51 making ${DOCINT}/util.c.pdf from ${IN}/util.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/util.c.pamphlet ${DOCINT} ; \
	${EXTRACT} util.c.pamphlet ; \
	rm -f ${DOCINT}/util.c.pamphlet ; \
	rm -f ${DOCINT}/util.c.tex ; \
	rm -f ${DOCINT}/util.c )

${DOCMNT}/util.c.pdf: ${DOCINT}/util.c.pdf
	@echo sl52 making ${DOCMNT}/util.c.pdf from ${DOCINT}/util.c.pdf
	@cp ${DOCINT}/util.c.pdf ${DOCMNT}/util.c.pdf

\end{chunk}
\subsection{wct.c \cite{13}}
\begin{chunk}{wct}
${MID}/wct.c: ${IN}/wct.c.pamphlet
	@echo sl53 making ${MID}/wct.c from ${IN}/wct.c.pamphlet
	@${BOOKS}/tangle wct.c.pamphlet >${MID}/wct.c

${OUT}/wct.o: ${MID}/wct.c
	@echo sl54 making ${OUT}/wct.o from ${MID}/wct.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/wct.c )

${DOCINT}/wct.c.pdf: ${IN}/wct.c.pamphlet 
	@echo sl55 making ${DOCINT}/wct.c.pdf from ${IN}/wct.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/wct.c.pamphlet ${DOCINT} ; \
	${EXTRACT} wct.c.pamphlet ; \
	rm -f ${DOCINT}/wct.c.pamphlet ; \
	rm -f ${DOCINT}/wct.c.tex ; \
	rm -f ${DOCINT}/wct.c )

${DOCMNT}/wct.c.pdf: ${DOCINT}/wct.c.pdf
	@echo sl56 making ${DOCMNT}/wct.c.pdf from ${DOCINT}/wct.c.pdf
	@cp ${DOCINT}/wct.c.pdf ${DOCMNT}/wct.c.pdf

\end{chunk}
\subsection{xdither.c \cite{14}}
\begin{chunk}{xdither}
${MID}/xdither.c: ${IN}/xdither.c.pamphlet
	@echo sl57 making ${MID}/xdither.c from ${IN}/xdither.c.pamphlet
	@${BOOKS}/tangle xdither.c.pamphlet >${MID}/xdither.c

${OUT}/xdither.o: ${MID}/xdither.c
	@echo sl58 making ${OUT}/xdither.o from ${MID}/xdither.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/xdither.c )

${DOCINT}/xdither.c.pdf: ${IN}/xdither.c.pamphlet 
	@echo sl59 making ${DOCINT}/xdither.c.pdf from ${IN}/xdither.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/xdither.c.pamphlet ${DOCINT} ; \
	${EXTRACT} xdither.c.pamphlet ; \
	rm -f ${DOCINT}/xdither.c.pamphlet ; \
	rm -f ${DOCINT}/xdither.c.tex ; \
	rm -f ${DOCINT}/xdither.c )

${DOCMNT}/xdither.c.pdf: ${DOCINT}/xdither.c.pdf
	@echo sl60 making ${DOCMNT}/xdither.c.pdf from ${DOCINT}/xdither.c.pdf
	@cp ${DOCINT}/xdither.c.pdf ${DOCMNT}/xdither.c.pdf

\end{chunk}
\subsection{xshade.c \cite{15}}
\begin{chunk}{xshade}
${MID}/xshade.c: ${IN}/xshade.c.pamphlet
	@echo sl61 making ${MID}/xshade.c from ${IN}/xshade.c.pamphlet
	@${BOOKS}/tangle xshade.c.pamphlet >${MID}/xshade.c

${OUT}/xshade.o: ${MID}/xshade.c
	@echo sl62 making ${OUT}/xshade.o from ${MID}/xshade.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/xshade.c )

${DOCINT}/xshade.c.pdf: ${IN}/xshade.c.pamphlet 
	@echo sl63 making ${DOCINT}/xshade.c.pdf from ${IN}/xshade.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/xshade.c.pamphlet ${DOCINT} ; \
	${EXTRACT} xshade.c.pamphlet ; \
	rm -f ${DOCINT}/xshade.c.pamphlet ; \
	rm -f ${DOCINT}/xshade.c.tex ; \
	rm -f ${DOCINT}/xshade.c )

${DOCMNT}/xshade.c.pdf: ${DOCINT}/xshade.c.pdf
	@echo sl64 making ${DOCMNT}/xshade.c.pdf from ${DOCINT}/xshade.c.pdf
	@cp ${DOCINT}/xshade.c.pdf ${DOCMNT}/xshade.c.pdf

\end{chunk}
\subsection{xspadfill.c \cite{16}}
\begin{chunk}{xspadfill}
${MID}/xspadfill.c: ${IN}/xspadfill.c.pamphlet
	@echo sl65 making ${MID}/xspadfill.c from ${IN}/xspadfill.c.pamphlet
	@${BOOKS}/tangle xspadfill.c.pamphlet >${MID}/xspadfill.c

${OUT}/xspadfill.o: ${MID}/xspadfill.c
	@echo sl66 making ${OUT}/xspadfill.o from ${MID}/xspadfill.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/xspadfill.c )

${DOCINT}/xspadfill.c.pdf: ${IN}/xspadfill.c.pamphlet 
	@echo sl67 making ${DOCINT}/xspadfill.c.pdf from ${IN}/xspadfill.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/xspadfill.c.pamphlet ${DOCINT} ; \
	${EXTRACT} xspadfill.c.pamphlet ; \
	rm -f ${DOCINT}/xspadfill.c.pamphlet ; \
	rm -f ${DOCINT}/xspadfill.c.tex ; \
	rm -f ${DOCINT}/xspadfill.c )

${DOCMNT}/xspadfill.c.pdf: ${DOCINT}/xspadfill.c.pdf
	@echo sl68 making ${DOCMNT}/xspadfill.c.pdf from ${DOCINT}/xspadfill.c.pdf
	@cp ${DOCINT}/xspadfill.c.pdf ${DOCMNT}/xspadfill.c.pdf

\end{chunk}
\section{The document stanza}
\begin{chunk}{document}
document: ${DOCFILES}
	@echo sl69 documenting ${IN}

\end{chunk}
\section{The clean stanza}
\begin{chunk}{clean}
clean:
	@echo sl70 cleaning ${IN}
	@rm -rf ${MID} ${OUT} ${DOCINT} ${DOCMNT}
	@rm -f Makefile Makefile.pdf

\end{chunk}
\subsection{Makefile documentation}
\begin{chunk}{Makefile.pdf}
${DOCMNT}/Makefile.pdf: ${IN}/Makefile.pdf
	@echo sl71 making ${DOCMNT}/Makefile.pdf from ${IN}/Makefile.pdf
	@cp ${IN}/Makefile.pdf ${DOCMNT}/Makefile.pdf

\end{chunk}
\begin{chunk}{*}
\getchunk{environment}

all: announce ${OUT}/libspad.a ${OTHER} ${DOCFILES}
	@echo sl72 finished making ${IN}

announce:
	@ echo ======================================
	@ echo src/lib BUILDING LIB FILES
	@ echo ======================================

${OUT}/libspad.a: ${AR} 
	@echo sl73 making ${OUT}/libspad.a
	@(cd ${OUT} ; \
	ar ru ${OUT}/libspad.a ${AR} ; \
	${RANLIB} ${OBJ}/${SYS}/lib/libspad.a )

\getchunk{Makefile.pdf}
\getchunk{bsdsignal}
\getchunk{cfuns-c}
\getchunk{cursor}
\getchunk{edin}
\getchunk{fnctkey}
\getchunk{halloc}
\getchunk{hash}
\getchunk{openpty}
\getchunk{pixmap}
\getchunk{prt}
\getchunk{sockio-c}
\getchunk{spadcolors}
\getchunk{util}
\getchunk{wct}
\getchunk{xdither}
\getchunk{xshade}
\getchunk{xspadfill}
\getchunk{document}
\getchunk{clean}
\end{chunk}

\eject
\begin{thebibliography}{99}
\bibitem{1} {\$SPAD/src/lib/bsdssignal.c.pamphlet}
\bibitem{2} {\$SPAD/src/lib/cfuns-c.c.pamphlet}
\bibitem{3} {\$SPAD/src/lib/cursor.c.pamphlet}
\bibitem{4} {\$SPAD/src/lib/edin.c.pamphlet}
\bibitem{5} {\$SPAD/src/lib/fnct-key.c.pamphlet}
\bibitem{6} {\$SPAD/src/lib/halloc.c.pamphlet}
\bibitem{7} {\$SPAD/src/lib/openpty.c.pamphlet}
\bibitem{8} {\$SPAD/src/lib/pixmap.c.pamphlet}
\bibitem{9} {\$SPAD/src/lib/prt.c.pamphlet}
\bibitem{10} {\$SPAD/src/lib/sockio-c.c.pamphlet}
\bibitem{11} {\$SPAD/src/lib/spadcolors.c.pamphlet}
\bibitem{12} {\$SPAD/src/lib/util.c.pamphlet}
\bibitem{13} {\$SPAD/src/lib/wct.c.pamphlet}
\bibitem{14} {\$SPAD/src/lib/xdither.c.pamphlet}
\bibitem{15} {\$SPAD/src/lib/xshade.c.pamphlet}
\bibitem{16} {\$SPAD/src/lib/xspadfill.c.pamphlet}
\end{thebibliography}
\end{document}
