\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/lib Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{environment}
<<environment>>=
IN=${SRC}/lib
MID=${INT}/lib
OUT=${OBJ}/${SYS}/lib
DOCINT=${INT}/doc/src/lib
DOCMNT=${MNT}/${SYS}/doc/src/lib
INC= ${SRC}/include

AR=	${OUT}/bsdsignal.o  ${OUT}/cursor.o ${OUT}/edin.o     \
        ${OUT}/fnct-key.o   ${OUT}/halloc.o ${OUT}/openpty.o  \
        ${OUT}/pixmap.o     ${OUT}/prt.o    ${OUT}/sockio-c.o \
        ${OUT}/spadcolors.o ${OUT}/util.o   ${OUT}/wct.o      \
        ${OUT}/xdither.o    ${OUT}/xshade.o ${OUT}/xspadfill.o 

OTHER=	${OUT}/cfuns-c.o ${OUT}/hash.o

DOCFILES=\
 ${DOCMNT}/bsdsignal.c.dvi  ${DOCMNT}/cfuns-c.c.dvi  ${DOCMNT}/cursor.c.dvi \
 ${DOCMNT}/edin.c.dvi       ${DOCMNT}/fnct-key.c.dvi ${DOCMNT}/halloc.c.dvi \
 ${DOCMNT}/hash.c.dvi       ${DOCMNT}/openpty.c.dvi  ${DOCMNT}/pixmap.c.dvi \
 ${DOCMNT}/prt.c.dvi        ${DOCMNT}/sockio-c.c.dvi ${DOCMNT}/Makefile.dvi \
 ${DOCMNT}/spadcolors.c.dvi ${DOCMNT}/util.c.dvi     ${DOCMNT}/wct.c.dvi    \
 ${DOCMNT}/xdither.c.dvi    ${DOCMNT}/xshade.c.dvi   ${DOCMNT}/xspadfill.c.dvi 

@
\section{Files}
\subsection{bsdsignal.c \cite{1}}

<<bsdsignal>>=
${MID}/bsdsignal.c: ${IN}/bsdsignal.c.pamphlet
	@echo sl01 making ${MID}/bsdsignal.c from ${IN}/bsdsignal.c.pamphlet
	@${TANGLE} bsdsignal.c.pamphlet >${MID}/bsdsignal.c

${OUT}/bsdsignal.o: ${MID}/bsdsignal.c
	@echo sl02 making ${OUT}/bsdsignal.o from ${MID}/bsdsignal.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/bsdsignal.c )

${DOCINT}/bsdsignal.c.dvi: ${IN}/bsdsignal.c.pamphlet 
	@echo sl03 making ${DOCINT}/bsdsignal.c.dvi from ${IN}/bsdsignal.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/bsdsignal.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} bsdsignal.c ; \
	rm -f ${DOCINT}/bsdsignal.c.pamphlet ; \
	rm -f ${DOCINT}/bsdsignal.c.tex ; \
	rm -f ${DOCINT}/bsdsignal.c )

${DOCMNT}/bsdsignal.c.dvi: ${DOCINT}/bsdsignal.c.dvi 
	@echo sl04 making ${DOCMNT}/bsdsignal.c.dvi from ${DOCINT}/bsdsignal.c.dvi
	@cp ${DOCINT}/bsdsignal.c.dvi ${DOCMNT}/bsdsignal.c.dvi 

@

\subsection{cfuns-c.c \cite{2}}
The cfuns-c file contains socket primitives used by Axiom.
They must be linked into and visible from the inferior lisp.
In GCL this link happens thru setting a shell variable called
{\bf EXTRAS} in the {\bf h/386-linux.defs} file. This file
gets included as part of the final system build of GCL.

<<cfuns-c>>=
${MID}/cfuns-c.c: ${IN}/cfuns-c.c.pamphlet
	@echo sl05 making ${MID}/cfuns-c.c from ${IN}/cfuns-c.c.pamphlet
	@${TANGLE} cfuns-c.c.pamphlet >${MID}/cfuns-c.c

${OUT}/cfuns-c.o: ${MID}/cfuns-c.c
	@echo sl06 making ${OUT}/cfuns-c.o from ${MID}/cfuns-c.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/cfuns-c.c )

${DOCINT}/cfuns-c.c.dvi: ${IN}/cfuns-c.c.pamphlet 
	@echo sl07 making ${DOCINT}/cfuns-c.c.dvi from ${IN}/cfuns-c.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/cfuns-c.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} cfuns-c.c ; \
	rm -f ${DOCINT}/cfuns-c.c.pamphlet ; \
	rm -f ${DOCINT}/cfuns-c.c.tex ; \
	rm -f ${DOCINT}/cfuns-c.c )

${DOCMNT}/cfuns-c.c.dvi: ${DOCINT}/cfuns-c.c.dvi
	@echo sl08 making ${DOCMNT}/cfuns-c.c.dvi from ${DOCINT}/cfuns-c.c.dvi
	@cp ${DOCINT}/cfuns-c.c.dvi ${DOCMNT}/cfuns-c.c.dvi 

@
\subsection{cursor.c \cite{3}}
<<cursor>>=
${MID}/cursor.c: ${IN}/cursor.c.pamphlet
	@echo sl09 making ${MID}/cursor.c from ${IN}/cursor.c.pamphlet
	@${TANGLE} cursor.c.pamphlet >${MID}/cursor.c

${OUT}/cursor.o: ${MID}/cursor.c
	@echo sl10 making ${OUT}/cursor.o from ${MID}/cursor.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/cursor.c )

${DOCINT}/cursor.c.dvi: ${IN}/cursor.c.pamphlet 
	@echo sl11 making ${DOCINT}/cursor.c.dvi from ${IN}/cursor.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/cursor.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} cursor.c ; \
	rm -f ${DOCINT}/cursor.c.pamphlet ; \
	rm -f ${DOCINT}/cursor.c.tex ; \
	rm -f ${DOCINT}/cursor.c )

${DOCMNT}/cursor.c.dvi: ${DOCINT}/cursor.c.dvi
	@echo sl12 making ${DOCMNT}/cursor.c.dvi from ${DOCINT}/cursor.c.dvi
	@cp ${DOCINT}/cursor.c.dvi ${DOCMNT}/cursor.c.dvi 

@
\subsection{edin.c \cite{4}}
<<edin>>=
${MID}/edin.c: ${IN}/edin.c.pamphlet
	@echo sl13 making ${MID}/edin.c from ${IN}/edin.c.pamphlet
	@${TANGLE} edin.c.pamphlet >${MID}/edin.c

${OUT}/edin.o: ${MID}/edin.c
	@echo sl14 making ${OUT}/edin.o from ${MID}/edin.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/edin.c )

${DOCINT}/edin.c.dvi: ${IN}/edin.c.pamphlet 
	@echo sl15 making ${DOCINT}/edin.c.dvi from ${IN}/edin.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/edin.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} edin.c ; \
	rm -f ${DOCINT}/edin.c.pamphlet ; \
	rm -f ${DOCINT}/edin.c.tex ; \
	rm -f ${DOCINT}/edin.c )

${DOCMNT}/edin.c.dvi: ${DOCINT}/edin.c.dvi
	@echo sl16 making ${DOCMNT}/edin.c.dvi from ${DOCINT}/edin.c.dvi
	@cp ${DOCINT}/edin.c.dvi ${DOCMNT}/edin.c.dvi 

@
\subsection{fnct-key.c \cite{5}}
<<fnctkey>>=
${MID}/fnct-key.c: ${IN}/fnct-key.c.pamphlet
	@echo sl17 making ${MID}/fnct-key.c from ${IN}/fnct-key.c.pamphlet
	@${TANGLE} fnct-key.c.pamphlet >${MID}/fnct-key.c

${OUT}/fnct-key.o: ${MID}/fnct-key.c
	@echo sl18 making ${OUT}/fnct-key.o from ${MID}/fnct-key.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/fnct-key.c )

${DOCINT}/fnct-key.c.dvi: ${IN}/fnct-key.c.pamphlet 
	@echo sl19 making ${DOCINT}/fnct-key.c.dvi from ${IN}/fnct-key.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/fnct-key.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} fnct-key.c ; \
	rm -f ${DOCINT}/fnct-key.c.pamphlet ; \
	rm -f ${DOCINT}/fnct-key.c.tex ; \
	rm -f ${DOCINT}/fnct-key.c )

${DOCMNT}/fnct-key.c.dvi: ${DOCINT}/fnct-key.c.dvi
	@echo sl20 making ${DOCMNT}/fnct-key.c.dvi from ${DOCINT}/fnct-key.c.dvi
	@cp ${DOCINT}/fnct-key.c.dvi ${DOCMNT}/fnct-key.c.dvi 

@
\subsection{halloc.c \cite{6}}
<<halloc>>=
${MID}/halloc.c: ${IN}/halloc.c.pamphlet
	@echo sl21 making ${MID}/halloc.c from ${IN}/halloc.c.pamphlet
	@${TANGLE} halloc.c.pamphlet >${MID}/halloc.c

${OUT}/halloc.o: ${MID}/halloc.c
	@echo sl22 making ${OUT}/halloc.o from ${MID}/halloc.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/halloc.c )

${DOCINT}/halloc.c.dvi: ${IN}/halloc.c.pamphlet 
	@echo sl23 making ${DOCINT}/halloc.c.dvi from ${IN}/halloc.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/halloc.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} halloc.c ; \
	rm -f ${DOCINT}/halloc.c.pamphlet ; \
	rm -f ${DOCINT}/halloc.c.tex ; \
	rm -f ${DOCINT}/halloc.c )

${DOCMNT}/halloc.c.dvi: ${DOCINT}/halloc.c.dvi
	@echo sl24 making ${DOCMNT}/halloc.c.dvi from ${DOCINT}/halloc.c.dvi
	@cp ${DOCINT}/halloc.c.dvi ${DOCMNT}/halloc.c.dvi 

@
\subsection{hash.c \cite{6}}
This a a string-based hash table that is used both in the graph
and hyper functions. It is included here because we need it built
earlier so the graph and hyper routines can refer to it.
<<hash>>=
${MID}/hash.c: ${IN}/hash.c.pamphlet
	@echo sl25 making ${MID}/hash.c from ${IN}/hash.c.pamphlet
	@${TANGLE} hash.c.pamphlet >${MID}/hash.c

${OUT}/hash.o: ${MID}/hash.c
	@echo sl26 making ${OUT}/hash.o from ${MID}/hash.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/hash.c )

${DOCINT}/hash.c.dvi: ${IN}/hash.c.pamphlet 
	@echo sl27 making ${DOCINT}/hash.c.dvi from ${IN}/hash.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/hash.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} hash.c ; \
	rm -f ${DOCINT}/hash.c.pamphlet ; \
	rm -f ${DOCINT}/hash.c.tex ; \
	rm -f ${DOCINT}/hash.c )

${DOCMNT}/hash.c.dvi: ${DOCINT}/hash.c.dvi
	@echo sl28 making ${DOCMNT}/hash.c.dvi from ${DOCINT}/hash.c.dvi
	@cp ${DOCINT}/hash.c.dvi ${DOCMNT}/hash.c.dvi 

@
\subsection{openpty.c \cite{7}}
<<openpty>>=
${MID}/openpty.c: ${IN}/openpty.c.pamphlet
	@echo sl29 making ${MID}/openpty.c from ${IN}/openpty.c.pamphlet
	@${TANGLE} openpty.c.pamphlet >${MID}/openpty.c

${OUT}/openpty.o: ${MID}/openpty.c
	@echo sl30 making ${OUT}/openpty.o from ${MID}/openpty.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/openpty.c )

${DOCINT}/openpty.c.dvi: ${IN}/openpty.c.pamphlet 
	@echo sl31 making ${DOCINT}/openpty.c.dvi from ${IN}/openpty.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/openpty.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} openpty.c ; \
	rm -f ${DOCINT}/openpty.c.pamphlet ; \
	rm -f ${DOCINT}/openpty.c.tex ; \
	rm -f ${DOCINT}/openpty.c )

${DOCMNT}/openpty.c.dvi: ${DOCINT}/openpty.c.dvi
	@echo sl32 making ${DOCMNT}/openpty.c.dvi from ${DOCINT}/openpty.c.dvi
	@cp ${DOCINT}/openpty.c.dvi ${DOCMNT}/openpty.c.dvi 

@
\subsection{pixmap.c \cite{8}}
<<pixmap>>=
${MID}/pixmap.c: ${IN}/pixmap.c.pamphlet
	@echo sl33 making ${MID}/pixmap.c from ${IN}/pixmap.c.pamphlet
	@${TANGLE} pixmap.c.pamphlet >${MID}/pixmap.c

${OUT}/pixmap.o: ${MID}/pixmap.c
	@echo sl34 making ${OUT}/pixmap.o from ${MID}/pixmap.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/pixmap.c )

${DOCINT}/pixmap.c.dvi: ${IN}/pixmap.c.pamphlet 
	@echo sl35 making ${DOCINT}/pixmap.c.dvi from ${IN}/pixmap.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/pixmap.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} pixmap.c ; \
	rm -f ${DOCINT}/pixmap.c.pamphlet ; \
	rm -f ${DOCINT}/pixmap.c.tex ; \
	rm -f ${DOCINT}/pixmap.c )

${DOCMNT}/pixmap.c.dvi: ${DOCINT}/pixmap.c.dvi
	@echo sl36 making ${DOCMNT}/pixmap.c.dvi from ${DOCINT}/pixmap.c.dvi
	@cp ${DOCINT}/pixmap.c.dvi ${DOCMNT}/pixmap.c.dvi 

@
\subsection{prt.c \cite{9}}
<<prt>>=
${MID}/prt.c: ${IN}/prt.c.pamphlet
	@echo sl37 making ${MID}/prt.c from ${IN}/prt.c.pamphlet
	@${TANGLE} prt.c.pamphlet >${MID}/prt.c

${OUT}/prt.o: ${MID}/prt.c
	@echo sl38 making ${OUT}/prt.o from ${MID}/prt.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/prt.c )

${DOCINT}/prt.c.dvi: ${IN}/prt.c.pamphlet 
	@echo sl39 making ${DOCINT}/prt.c.dvi from ${IN}/prt.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/prt.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} prt.c ; \
	rm -f ${DOCINT}/prt.c.pamphlet ; \
	rm -f ${DOCINT}/prt.c.tex ; \
	rm -f ${DOCINT}/prt.c )

${DOCMNT}/prt.c.dvi: ${DOCINT}/prt.c.dvi
	@echo sl40 making ${DOCMNT}/prt.c.dvi from ${DOCINT}/prt.c.dvi
	@cp ${DOCINT}/prt.c.dvi ${DOCMNT}/prt.c.dvi 

@
\subsection{sockio-c.c \cite{10}}
The sockio-c file contains socket primitives used by Axiom.
They must be linked into and visible from the inferior lisp.
In GCL this link happens thru setting a shell variable called
{\bf EXTRAS} in the {\bf h/386-linux.defs} file. This file
gets included as part of the final system build of GCL.

<<sockio-c>>=
${MID}/sockio-c.c: ${IN}/sockio-c.c.pamphlet
	@echo sl41 making ${MID}/sockio-c.c from ${IN}/sockio-c.c.pamphlet
	@${TANGLE} sockio-c.c.pamphlet >${MID}/sockio-c.c

${OUT}/sockio-c.o: ${MID}/sockio-c.c
	@echo sl42 making ${OUT}/sockio-c.o from ${MID}/sockio-c.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/sockio-c.c )

${DOCINT}/sockio-c.c.dvi: ${IN}/sockio-c.c.pamphlet 
	@echo sl43 making ${DOCINT}/sockio-c.c.dvi from ${IN}/sockio-c.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/sockio-c.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} sockio-c.c ; \
	rm -f ${DOCINT}/sockio-c.c.pamphlet ; \
	rm -f ${DOCINT}/sockio-c.c.tex ; \
	rm -f ${DOCINT}/sockio-c.c )

${DOCMNT}/sockio-c.c.dvi: ${DOCINT}/sockio-c.c.dvi
	@echo sl44 making ${DOCMNT}/sockio-c.c.dvi from ${DOCINT}/sockio-c.c.dvi
	@cp ${DOCINT}/sockio-c.c.dvi ${DOCMNT}/sockio-c.c.dvi 

@
\subsection{spadcolors.c \cite{11}}
<<spadcolors>>=
${MID}/spadcolors.c: ${IN}/spadcolors.c.pamphlet
	@echo sl45 making ${MID}/spadcolors.c from ${IN}/spadcolors.c.pamphlet
	@${TANGLE} spadcolors.c.pamphlet >${MID}/spadcolors.c

${OUT}/spadcolors.o: ${MID}/spadcolors.c
	@echo sl46 making ${OUT}/spadcolors.o from ${MID}/spadcolors.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/spadcolors.c )

${DOCINT}/spadcolors.c.dvi: ${IN}/spadcolors.c.pamphlet 
	@echo sl47 making ${DOCINT}/spadcolors.c.dvi from \
          ${IN}/spadcolors.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/spadcolors.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} spadcolors.c ; \
	rm -f ${DOCINT}/spadcolors.c.pamphlet ; \
	rm -f ${DOCINT}/spadcolors.c.tex ; \
	rm -f ${DOCINT}/spadcolors.c )

${DOCMNT}/spadcolors.c.dvi: ${DOCINT}/spadcolors.c.dvi
	@echo sl48 making ${DOCMNT}/spadcolors.c.dvi from ${DOCINT}/spadcolors.c.dvi
	@cp ${DOCINT}/spadcolors.c.dvi ${DOCMNT}/spadcolors.c.dvi 

@
\subsection{util.c \cite{12}}
<<util>>=
${MID}/util.c: ${IN}/util.c.pamphlet
	@echo sl49 making ${MID}/util.c from ${IN}/util.c.pamphlet
	@${TANGLE} util.c.pamphlet >${MID}/util.c

${OUT}/util.o: ${MID}/util.c
	@echo sl50 making ${OUT}/util.o from ${MID}/util.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/util.c )

${DOCINT}/util.c.dvi: ${IN}/util.c.pamphlet 
	@echo sl51 making ${DOCINT}/util.c.dvi from ${IN}/util.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/util.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} util.c ; \
	rm -f ${DOCINT}/util.c.pamphlet ; \
	rm -f ${DOCINT}/util.c.tex ; \
	rm -f ${DOCINT}/util.c )

${DOCMNT}/util.c.dvi: ${DOCINT}/util.c.dvi
	@echo sl52 making ${DOCMNT}/util.c.dvi from ${DOCINT}/util.c.dvi
	@cp ${DOCINT}/util.c.dvi ${DOCMNT}/util.c.dvi 

@
\subsection{wct.c \cite{13}}
<<wct>>=
${MID}/wct.c: ${IN}/wct.c.pamphlet
	@echo sl53 making ${MID}/wct.c from ${IN}/wct.c.pamphlet
	@${TANGLE} wct.c.pamphlet >${MID}/wct.c

${OUT}/wct.o: ${MID}/wct.c
	@echo sl54 making ${OUT}/wct.o from ${MID}/wct.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/wct.c )

${DOCINT}/wct.c.dvi: ${IN}/wct.c.pamphlet 
	@echo sl55 making ${DOCINT}/wct.c.dvi from ${IN}/wct.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/wct.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} wct.c ; \
	rm -f ${DOCINT}/wct.c.pamphlet ; \
	rm -f ${DOCINT}/wct.c.tex ; \
	rm -f ${DOCINT}/wct.c )

${DOCMNT}/wct.c.dvi: ${DOCINT}/wct.c.dvi
	@echo sl56 making ${DOCMNT}/wct.c.dvi from ${DOCINT}/wct.c.dvi
	@cp ${DOCINT}/wct.c.dvi ${DOCMNT}/wct.c.dvi 

@
\subsection{xdither.c \cite{14}}
<<xdither>>=
${MID}/xdither.c: ${IN}/xdither.c.pamphlet
	@echo sl57 making ${MID}/xdither.c from ${IN}/xdither.c.pamphlet
	@${TANGLE} xdither.c.pamphlet >${MID}/xdither.c

${OUT}/xdither.o: ${MID}/xdither.c
	@echo sl58 making ${OUT}/xdither.o from ${MID}/xdither.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/xdither.c )

${DOCINT}/xdither.c.dvi: ${IN}/xdither.c.pamphlet 
	@echo sl59 making ${DOCINT}/xdither.c.dvi from ${IN}/xdither.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/xdither.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} xdither.c ; \
	rm -f ${DOCINT}/xdither.c.pamphlet ; \
	rm -f ${DOCINT}/xdither.c.tex ; \
	rm -f ${DOCINT}/xdither.c )

${DOCMNT}/xdither.c.dvi: ${DOCINT}/xdither.c.dvi
	@echo sl60 making ${DOCMNT}/xdither.c.dvi from ${DOCINT}/xdither.c.dvi
	@cp ${DOCINT}/xdither.c.dvi ${DOCMNT}/xdither.c.dvi 

@
\subsection{xshade.c \cite{15}}
<<xshade>>=
${MID}/xshade.c: ${IN}/xshade.c.pamphlet
	@echo sl61 making ${MID}/xshade.c from ${IN}/xshade.c.pamphlet
	@${TANGLE} xshade.c.pamphlet >${MID}/xshade.c

${OUT}/xshade.o: ${MID}/xshade.c
	@echo sl62 making ${OUT}/xshade.o from ${MID}/xshade.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/xshade.c )

${DOCINT}/xshade.c.dvi: ${IN}/xshade.c.pamphlet 
	@echo sl63 making ${DOCINT}/xshade.c.dvi from ${IN}/xshade.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/xshade.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} xshade.c ; \
	rm -f ${DOCINT}/xshade.c.pamphlet ; \
	rm -f ${DOCINT}/xshade.c.tex ; \
	rm -f ${DOCINT}/xshade.c )

${DOCMNT}/xshade.c.dvi: ${DOCINT}/xshade.c.dvi
	@echo sl64 making ${DOCMNT}/xshade.c.dvi from ${DOCINT}/xshade.c.dvi
	@cp ${DOCINT}/xshade.c.dvi ${DOCMNT}/xshade.c.dvi 

@
\subsection{xspadfill.c \cite{16}}
<<xspadfill>>=
${MID}/xspadfill.c: ${IN}/xspadfill.c.pamphlet
	@echo sl65 making ${MID}/xspadfill.c from ${IN}/xspadfill.c.pamphlet
	@${TANGLE} xspadfill.c.pamphlet >${MID}/xspadfill.c

${OUT}/xspadfill.o: ${MID}/xspadfill.c
	@echo sl66 making ${OUT}/xspadfill.o from ${MID}/xspadfill.c
	@( cd ${OUT} ; \
	${CC} ${CCF} -c -I${INC} ${MID}/xspadfill.c )

${DOCINT}/xspadfill.c.dvi: ${IN}/xspadfill.c.pamphlet 
	@echo sl67 making ${DOCINT}/xspadfill.c.dvi from ${IN}/xspadfill.c.pamphlet
	@(cd ${DOCINT} ; \
	cp ${IN}/xspadfill.c.pamphlet ${DOCINT} ; \
	${DOCUMENT} ${NOISE} xspadfill.c ; \
	rm -f ${DOCINT}/xspadfill.c.pamphlet ; \
	rm -f ${DOCINT}/xspadfill.c.tex ; \
	rm -f ${DOCINT}/xspadfill.c )

${DOCMNT}/xspadfill.c.dvi: ${DOCINT}/xspadfill.c.dvi
	@echo sl68 making ${DOCMNT}/xspadfill.c.dvi from ${DOCINT}/xspadfill.c.dvi
	@cp ${DOCINT}/xspadfill.c.dvi ${DOCMNT}/xspadfill.c.dvi 

@
\section{The document stanza}
<<document>>=
document: ${DOCFILES}
	@echo sl69 documenting ${IN}

@
\section{The clean stanza}
<<clean>>=
clean:
	@echo sl70 cleaning ${IN}
	@rm -rf ${MID} ${OUT} ${DOCINT} ${DOCMNT}
	@rm -f Makefile Makefile.dvi

@
\subsection{Makefile documentation}
<<Makefile.dvi>>=
${DOCMNT}/Makefile.dvi: ${IN}/Makefile.dvi
	@echo sl71 making ${DOCMNT}/Makefile.dvi from ${IN}/Makefile.dvi
	@cp ${IN}/Makefile.dvi ${DOCMNT}/Makefile.dvi 

@
<<*>>=
<<environment>>

all: announce ${OUT}/libspad.a ${OTHER} ${DOCFILES}
	@echo sl72 finished making ${IN}

announce:
	@ echo ======================================
	@ echo src/lib BUILDING LIB FILES
	@ echo ======================================

${OUT}/libspad.a: ${AR} 
	@echo sl73 making ${OUT}/libspad.a
	@(cd ${OUT} ; \
	ar ru ${OUT}/libspad.a ${AR} ; \
	${RANLIB} ${OBJ}/${SYS}/lib/libspad.a )

<<Makefile.dvi>>
<<bsdsignal>>
<<cfuns-c>>
<<cursor>>
<<edin>>
<<fnctkey>>
<<halloc>>
<<hash>>
<<openpty>>
<<pixmap>>
<<prt>>
<<sockio-c>>
<<spadcolors>>
<<util>>
<<wct>>
<<xdither>>
<<xshade>>
<<xspadfill>>
<<document>>
<<clean>>
@

\eject
\begin{thebibliography}{99}
\bibitem{1} {\$SPAD/src/lib/bsdssignal.c.pamphlet}
\bibitem{2} {\$SPAD/src/lib/cfuns-c.c.pamphlet}
\bibitem{3} {\$SPAD/src/lib/cursor.c.pamphlet}
\bibitem{4} {\$SPAD/src/lib/edin.c.pamphlet}
\bibitem{5} {\$SPAD/src/lib/fnct-key.c.pamphlet}
\bibitem{6} {\$SPAD/src/lib/halloc.c.pamphlet}
\bibitem{7} {\$SPAD/src/lib/openpty.c.pamphlet}
\bibitem{8} {\$SPAD/src/lib/pixmap.c.pamphlet}
\bibitem{9} {\$SPAD/src/lib/prt.c.pamphlet}
\bibitem{10} {\$SPAD/src/lib/sockio-c.c.pamphlet}
\bibitem{11} {\$SPAD/src/lib/spadcolors.c.pamphlet}
\bibitem{12} {\$SPAD/src/lib/util.c.pamphlet}
\bibitem{13} {\$SPAD/src/lib/wct.c.pamphlet}
\bibitem{14} {\$SPAD/src/lib/xdither.c.pamphlet}
\bibitem{15} {\$SPAD/src/lib/xshade.c.pamphlet}
\bibitem{16} {\$SPAD/src/lib/xspadfill.c.pamphlet}
\end{thebibliography}
\end{document}
