\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/clef Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{Environment variables}
<<environment>>=
# this is where we are compiling from
IN=     ${SRC}/clef

# this is the intermediate place 
MID=    ${OBJ}/${SYS}/clef

# this is where to put the clef command
OUT=	${MNT}/${SYS}/bin

# this is where the include files live
INC=    ${SRC}/include

# this is where we hid the libspad library
LIB=	${OBJ}/${SYS}/lib

DOC=    ${MNT}/${SYS}/doc/src/clef

# this is the set of files that comprise clef
OBJS= ${MID}/edible.o

CFLAGS=	${CCF} 
LDFLAGS= -L${LIB} -lspad ${LDF}

CLEFOBJS= ${MID}/edible.o ${LIB}/fnct-key.o ${LIB}/edin.o ${LIB}/bsdsignal.o \
          ${LIB}/prt.o ${LIB}/wct.o ${LIB}/openpty.o ${LIB}/cursor.o

DOCFILES=${DOC}/edible.c.dvi

@
\section{The clef sources, edible}
<<edible>>=
${OUT}/clef:	${CLEFOBJS}
	@ echo 1 linking clef
	@ ${CC} ${CLEFOBJS} -o ${OUT}/clef

${MID}/edible.c: ${IN}/edible.c.pamphlet
	@ echo 2 making ${MID}/edible.c from ${IN}/edible.c.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/edible.c.pamphlet >edible.c )

${MID}/edible.o: ${MID}/edible.c ${INC}/edible.h
	@ echo 3 making ${MID}/edible.o from ${MID}/edible.c
	@ ( cd ${MID} ; ${CC} -c ${CFLAGS} edible.c -I${INC} )

${DOC}/edible.c.dvi: ${IN}/edible.c.pamphlet 
	@ echo 4 making ${DOC}/edible.c.dvi from ${IN}/edible.c.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/edible.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} edible.c ; \
	rm -f ${DOC}/edible.c.pamphlet ; \
	rm -f ${DOC}/edible.c.tex ; \
	rm -f ${DOC}/edible.c )

@
<<*>>=
<<environment>>
all:	${OUT}/clef ${DOCFILES}
	@ echo 6 finished ${IN}

clean:
	@echo 7 cleaning ${SRC}/clef

<<edible>>
@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
