\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/share Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
Files in the share directory are common to all of the system builds.
\end{abstract}
\eject
\tableofcontents
\eject
\section{command.list}
The [[command.list]] file contains command completion strings used by
the [[clef]] command line editor function. In the NAG version this 
lived in the share subdirectory but the open source version moves it
back to the [[lib]] directory where it originally lived.
<<command.list>>=
${LIB}/command.list: ${IN}/algebra/command.list
	@ echo 2 making ${LIB}/command.list from ${IN}/algebra/command.list
	@ cp ${IN}/algebra/command.list ${LIB}/command.list

@
<<*>>=
IN=${SRC}/share
HYPER=${MNT}/${SYS}/doc/hypertex/pages
LIB=${MNT}/${SYS}/lib

FILES=${LIB}/command.list

all: ${FILES}
	@ echo 3 finished ${IN}

clean:
	@echo 4 cleaning ${SRC}/share

<<command.list>>
@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
