#!/bin/sh
latex=`which latex`
STY=$AXIOM/../../books/axiom.sty
TAN=$AXIOM/../../books/tanglec
echo extract1: $TAN
if [ "$latex" = "" ] ; then
  echo document ERROR You must install latex first
  exit 0
fi
if [ ! -f axiom.sty ] ; then cp $STY . ; fi
if [ "$#" = "3" ]; then
 REDIRECT=$2
 FILE=`basename $3 .pamphlet`
 $TAN $FILE.pamphlet >$FILE
 echo extract2: `pwd`/$FILE.pamphlet
 if [ ! -f axiom.sty ] ; then cp $STY . ; fi
 $latex --interaction nonstopmode $FILE.pamphlet >$REDIRECT
 $latex --interaction nonstopmode $FILE.pamphlet >$REDIRECT
 dvipdfm $FILE.dvi
 rm -f $FILE~
 rm -f $FILE.pamphlet~
 rm -f $FILE.log
 rm -f $FILE.tex
 rm -f $FILE.toc
 rm -f $FILE.aux
 exit 0
fi
if [ "$#" = "1" ]; then
 FILE=`basename $1 .pamphlet`
 $TAN $FILE.pamphlet >$FILE
 echo extract3: `pwd`/$FILE.pamphlet
 if [ ! -f axiom.sty ] ; then cp $STY . ; fi
 $latex $FILE.pamphlet
 $latex $FILE.pamphlet
 dvipdfm $FILE.dvi
 rm -f $FILE~
 rm -f $FILE.pamphlet~
 rm -f $FILE.log
 rm -f $FILE.tex
 rm -f $FILE.toc
 rm -f $FILE.aux
 exit 0
fi
echo "document [ -o redirect ] pamphlet"


