\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{books/Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
This Makefile creates all the primary documentation for Axiom
as pdf files in the final output tree.
\end{abstract}
\eject
\tableofcontents
\eject
\section{The Makefile}
<<*>>=
PDF=${AXIOM}/doc
IN=${SPD}/books
LATEX=latex
MAKEINDEX=makeindex
DVIPS=dvips -Ppdf
PS2PDF=ps2pdf
RM=rm -f

BOOKS=${PDF}/bookvol0.pdf ${PDF}/bookvol1.pdf ${PDF}/bookvol2.pdf \
      ${PDF}/bookvol3.pdf ${PDF}/bookvol4.pdf ${PDF}/bookvol5.pdf \
      ${PDF}/bookvol6.pdf ${PDF}/bookvol7.pdf ${PDF}/bookvol8.pdf \
      ${PDF}/bookvol9.pdf ${PDF}/bookvol10.pdf ${PDF}/bookvol11.pdf \
      ${PDF}/bookvol12.pdf 

all: ${PDF}/axiom.sty ${BOOKS} ${PDF}/toc.pdf

@
\section{Volume 0: Axiom Jenks and Sutor}
This is the reconstructed Jenks and Sutor volume.
<<*>>=
${PDF}/bookvol0.pdf: ${IN}/bookvol0.pamphlet 
	@echo 0 making ${PDF}/bookvol0.pdf from ${IN}/bookvol0.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol0.pamphlet ${PDF} ; \
	  cp -pr ${IN}/ps ${PDF} ; \
	  ${WEAVE} -delay bookvol0.pamphlet >bookvol0.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol0.tex ; \
	    ${LATEX} bookvol0.tex >/dev/null ; \
	    ${DVIPS} bookvol0.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol0.ps >/dev/null ; \
	    ${RM} bookvol0.aux bookvol0.dvi bookvol0.log bookvol0.ps \
                  bookvol0.idx bookvol0.tex bookvol0.pamphlet ; \
	  else \
	    ${LATEX} bookvol0.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol0.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol0.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol0.ps >${TMP}/trace  ; \
	    ${RM} bookvol0.aux bookvol0.dvi bookvol0.log bookvol0.ps \
                  bookvol0.idx bookvol0.tex bookvol0.pamphlet ; \
	  fi )

@
\section{Volume 1: Axiom Tutorial}
This is the tutorial volume. ISBN 1-411-66587-X. 
Hardcopy is available from Amazon.com or Lulu.com.
<<*>>=
${PDF}/bookvol1.pdf: ${IN}/bookvol1.pamphlet 
	@echo 1 making ${PDF}/bookvol1.pdf from ${IN}/bookvol1.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol1.pamphlet ${PDF} ; \
	  cp -pr ${IN}/ps ${PDF} ; \
	  ${WEAVE} -delay bookvol1.pamphlet >bookvol1.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol1.tex ; \
	    ${LATEX} bookvol1.tex >/dev/null ; \
	    ${DVIPS} bookvol1.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol1.ps >/dev/null ; \
	    ${RM} bookvol1.aux bookvol1.dvi bookvol1.log bookvol1.ps \
                  bookvol1.idx bookvol1.tex bookvol1.pamphlet ; \
	  else \
	    ${LATEX} bookvol1.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol1.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol1.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol1.ps >${TMP}/trace  ; \
	    ${RM} bookvol1.aux bookvol1.dvi bookvol1.log bookvol1.ps \
                  bookvol1.idx bookvol1.tex bookvol1.pamphlet ; \
	  fi )

@
\section{Volume 2: Axiom Users Guide}
This is a more detailed explanation with current information
for Axiom users.
<<*>>=
${PDF}/bookvol2.pdf: ${IN}/bookvol2.pamphlet 
	@echo 2 making ${PDF}/bookvol2.pdf from ${IN}/bookvol2.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol2.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol2.pamphlet >bookvol2.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol2.tex ; \
	    ${LATEX} bookvol2.tex >/dev/null ; \
	    ${DVIPS} bookvol2.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol2.ps >/dev/null ; \
	    ${RM} bookvol2.aux bookvol2.dvi bookvol2.log bookvol2.ps \
                  bookvol2.idx bookvol2.tex bookvol2.pamphlet ; \
	  else \
	    ${LATEX} bookvol2.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol2.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol2.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol2.ps >${TMP}/trace  ; \
	    ${RM} bookvol2.aux bookvol2.dvi bookvol2.log bookvol2.ps \
                  bookvol2.idx bookvol2.tex bookvol2.pamphlet ; \
	  fi )

@
\section{Volume 3: Axiom Programmers Guide}
This is information about the language and algebra hierarchy
for Spad language programmers.
<<*>>=
${PDF}/bookvol3.pdf: ${IN}/bookvol3.pamphlet 
	@echo making ${PDF}/bookvol3.pdf from ${IN}/bookvol3.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol3.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol3.pamphlet >bookvol3.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol3.tex ; \
	    ${LATEX} bookvol3.tex >/dev/null ; \
	    ${DVIPS} bookvol3.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol3.ps >/dev/null ; \
	    ${RM} bookvol3.aux bookvol3.dvi bookvol3.log bookvol3.ps \
                  bookvol3.idx bookvol3.tex bookvol3.pamphlet ; \
	  else \
	    ${LATEX} bookvol3.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol3.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol3.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol3.ps >${TMP}/trace  ; \
	    ${RM} bookvol3.aux bookvol3.dvi bookvol3.log bookvol3.ps \
                  bookvol3.idx bookvol3.tex bookvol3.pamphlet ; \
	  fi )

@
\section{Volume 4: Axiom Developers Guide}
This is a collection of userful information for developers.
<<*>>=
${PDF}/bookvol4.pdf: ${IN}/bookvol4.pamphlet 
	@echo making ${PDF}/bookvol4.pdf from ${IN}/bookvol4.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol4.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol4.pamphlet >bookvol4.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol4.tex ; \
	    ${LATEX} bookvol4.tex >/dev/null ; \
	    ${DVIPS} bookvol4.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol4.ps >/dev/null ; \
	    ${RM} bookvol4.aux bookvol4.dvi bookvol4.log bookvol4.ps \
                  bookvol4.idx bookvol4.tex bookvol4.pamphlet ; \
	  else \
	    ${LATEX} bookvol4.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol4.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol4.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol4.ps >${TMP}/trace  ; \
	    ${RM} bookvol4.aux bookvol4.dvi bookvol4.log bookvol4.ps \
                  bookvol4.idx bookvol4.tex bookvol4.pamphlet ; \
	  fi )

@
\section{Volume 5: Axiom Interpreter}
This is the source code and explanation for the interpreter.
<<*>>=
${PDF}/bookvol5.pdf: ${IN}/bookvol5.pamphlet 
	@echo making ${PDF}/bookvol5.pdf from ${IN}/bookvol5.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol5.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol5.pamphlet >bookvol5.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol5.tex ; \
	    ${LATEX} bookvol5.tex >/dev/null ; \
	    ${DVIPS} bookvol5.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol5.ps >/dev/null ; \
	    ${RM} bookvol5.aux bookvol5.dvi bookvol5.log bookvol5.ps \
                  bookvol5.idx bookvol5.tex bookvol5.pamphlet ; \
	  else \
	    ${LATEX} bookvol5.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol5.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol5.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol5.ps >${TMP}/trace  ; \
	    ${RM} bookvol5.aux bookvol5.dvi bookvol5.log bookvol5.ps \
                  bookvol5.idx bookvol5.tex bookvol5.pamphlet ; \
	  fi )

@
\section{Volume 6: Axiom Command}
This covers the axiom commands, sman, and some other system related issues.
<<*>>=
${PDF}/bookvol6.pdf: ${IN}/bookvol6.pamphlet 
	@echo making ${PDF}/bookvol6.pdf from ${IN}/bookvol6.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol6.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol6.pamphlet >bookvol6.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol6.tex ; \
	    ${LATEX} bookvol6.tex >/dev/null ; \
	    ${DVIPS} bookvol6.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol6.ps >/dev/null ; \
	    ${RM} bookvol6.aux bookvol6.dvi bookvol6.log bookvol6.ps \
                  bookvol6.idx bookvol6.tex bookvol6.pamphlet ; \
	  else \
	    ${LATEX} bookvol6.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol6.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol6.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol6.ps >${TMP}/trace  ; \
	    ${RM} bookvol6.aux bookvol6.dvi bookvol6.log bookvol6.ps \
                  bookvol6.idx bookvol6.tex bookvol6.pamphlet ; \
	  fi )

@
\section{Volume 7: Axiom Hyperdoc}
This is the source and explanation for the X11 hyperdoc subsystem
<<*>>=
${PDF}/bookvol7.pdf: ${IN}/bookvol7.pamphlet 
	@echo making ${PDF}/bookvol7.pdf from ${IN}/bookvol7.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol7.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol7.pamphlet >bookvol7.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol7.tex ; \
	    ${LATEX} bookvol7.tex >/dev/null ; \
	    ${DVIPS} bookvol7.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol7.ps >/dev/null ; \
	    ${RM} bookvol7.aux bookvol7.dvi bookvol7.log bookvol7.ps \
                  bookvol7.idx bookvol7.tex bookvol7.pamphlet ; \
	  else \
	    ${LATEX} bookvol7.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol7.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol7.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol7.ps >${TMP}/trace  ; \
	    ${RM} bookvol7.aux bookvol7.dvi bookvol7.log bookvol7.ps \
                  bookvol7.idx bookvol7.tex bookvol7.pamphlet ; \
	  fi )

@
\section{Volume 8: Axiom Graphics}
This is the source and explanation for the X11 graphics subsystem
<<*>>=
${PDF}/bookvol8.pdf: ${IN}/bookvol8.pamphlet 
	@echo making ${PDF}/bookvol8.pdf from ${IN}/bookvol8.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol8.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol8.pamphlet >bookvol8.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol8.tex ; \
	    ${MAKEINDEX} bookvol8 >/dev/null ; \
	    ${LATEX} bookvol8.tex >/dev/null ; \
	    ${DVIPS} bookvol8.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol8.ps >/dev/null ; \
	    ${RM} bookvol8.aux bookvol8.dvi bookvol8.log bookvol8.ps \
                  bookvol8.idx bookvol8.tex bookvol8.pamphlet ; \
	  else \
	    ${LATEX} bookvol8.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${MAKEINDEX} bookvol8 >${TMP}/trace ; \
	    ${LATEX} bookvol8.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol8.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol8.ps >${TMP}/trace  ; \
	    ${RM} bookvol8.aux bookvol8.dvi bookvol8.log bookvol8.ps \
                  bookvol8.idx bookvol8.tex bookvol8.pamphlet ; \
	  fi )

@
\section{Volume 9: Axiom Compiler}
This is the source and explanation for the spad compiler.
<<*>>=
${PDF}/bookvol9.pdf: ${IN}/bookvol9.pamphlet 
	@echo making ${PDF}/bookvol9.pdf from ${IN}/bookvol9.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol9.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol9.pamphlet >bookvol9.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol9.tex ; \
	    ${LATEX} bookvol9.tex >/dev/null ; \
	    ${DVIPS} bookvol9.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol9.ps >/dev/null ; \
	    ${RM} bookvol9.aux bookvol9.dvi bookvol9.log bookvol9.ps \
                  bookvol9.idx bookvol9.tex bookvol9.pamphlet ; \
	  else \
	    ${LATEX} bookvol9.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol9.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol9.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol9.ps >${TMP}/trace  ; \
	    ${RM} bookvol9.aux bookvol9.dvi bookvol9.log bookvol9.ps \
                  bookvol9.idx bookvol9.tex bookvol9.pamphlet ; \
	  fi )

@
\section{Volume 10: Axiom Algebra}
This ia multi-volumne set covering the algebra.
<<*>>=
${PDF}/bookvol10.pdf: ${IN}/bookvol10.pamphlet 
	@echo 10 making ${PDF}/bookvol10.pdf from ${IN}/bookvol10.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol10.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol10.pamphlet >bookvol10.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol10.tex ; \
	    ${LATEX} bookvol10.tex >/dev/null ; \
	    ${DVIPS} bookvol10.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol10.ps >/dev/null ; \
	    ${RM} bookvol10.aux bookvol10.dvi bookvol10.log bookvol10.ps \
                  bookvol10.idx bookvol10.tex bookvol10.pamphlet ; \
	  else \
	    ${LATEX} bookvol10.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol10.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol10.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol10.ps >${TMP}/trace  ; \
	    ${RM} bookvol10.aux bookvol10.dvi bookvol10.log bookvol10.ps \
                  bookvol10.idx bookvol10.tex bookvol10.pamphlet ; \
	  fi )

@
\section{Volume 11: Axiom Browser}
This is the source and explanation of the new Firefox browser front end.
<<*>>=
${PDF}/bookvol11.pdf: ${IN}/bookvol11.pamphlet 
	@echo 11 making ${PDF}/bookvol11.pdf from ${IN}/bookvol11.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol11.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol11.pamphlet >bookvol11.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol11.tex ; \
	    ${LATEX} bookvol11.tex >/dev/null ; \
	    ${DVIPS} bookvol11.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol11.ps >/dev/null ; \
	    ${RM} bookvol11.aux bookvol11.dvi bookvol11.log bookvol11.ps \
                  bookvol11.idx bookvol11.tex bookvol11.pamphlet ; \
	  else \
	    ${LATEX} bookvol11.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol11.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol11.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol11.ps >${TMP}/trace  ; \
	    ${RM} bookvol11.aux bookvol11.dvi bookvol11.log bookvol11.ps \
                  bookvol11.idx bookvol11.tex bookvol11.pamphlet ; \
	  fi )

@
\section{Volume 12: Axiom Crystal}
This is the design documents for the crystal interface.
<<*>>=
${PDF}/bookvol12.pdf: ${IN}/bookvol12.pamphlet 
	@echo 12 making ${PDF}/bookvol12.pdf from ${IN}/bookvol12.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol12.pamphlet ${PDF} ; \
	  ${WEAVE} -delay bookvol12.pamphlet >bookvol12.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${LATEX} bookvol12.tex ; \
	    ${LATEX} bookvol12.tex >/dev/null ; \
	    ${DVIPS} bookvol12.dvi 2>/dev/null ; \
	    ${PS2PDF} bookvol12.ps >/dev/null ; \
	    ${RM} bookvol12.aux bookvol12.dvi bookvol12.log bookvol12.ps \
                  bookvol12.idx bookvol12.tex bookvol12.pamphlet ; \
	  else \
	    ${LATEX} bookvol12.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${LATEX} bookvol12.tex >${TMP}/trace ; \
	    ${DVIPS} bookvol12.dvi 2>${TMP}/trace  ; \
	    ${PS2PDF} bookvol12.ps >${TMP}/trace  ; \
	    ${RM} bookvol12.aux bookvol12.dvi bookvol12.log bookvol12.ps \
                  bookvol12.idx bookvol12.tex bookvol12.pamphlet ; \
	  fi )

@
\section{Combined Table of Contents}
This is the table of contents from the existing volumes combined into
one document for easy reference.
<<*>>=
${PDF}/toc.pdf: ${BOOKS}
	@echo 13 making ${PDF}/toc.pdf
	@(cd ${PDF} ; \
	echo "\\documentclass{book}" >toc.tex ; \
	echo "\\begin{document}" >>toc.tex ; \
	echo "{\\bf Volume ~ 0}: Axiom {\\sl Jenks and Sutor}\\\\" >toc.toc ; \
	echo "{\\bf Volume ~ 1}: Axiom {\\sl Tutorial}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 2}: Axiom {\\sl Users Guide}\\\\" >>toc.toc ; \
	echo \
         "{\\bf Volume ~ 3}: Axiom {\\sl Programmers Guide}\\\\" >>toc.toc ; \
	echo \
         "{\\bf Volume ~ 4}: Axiom {\\sl Developers Guide}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 5}: Axiom {\\sl Interpreter}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 6}: Axiom {\\sl Command}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 7}: Axiom {\\sl Hyperdoc}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 8}: Axiom {\\sl Graphics}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 9}: Axiom {\\sl Compiler}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 10}: Axiom {\\sl Algebra}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 11}: Axiom {\\sl Browser}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 12}: Axiom {\\sl Crystal}\\\\" >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\tableofcontents" >>toc.tex ; \
	echo "\\end{document}" >>toc.tex ; \
	echo "\\section*{Volume 0: Axiom Jenks and Sutor}" >>toc.toc ; \
	cat bookvol0.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 1: Axiom Tutorial}" >>toc.toc ; \
	cat bookvol1.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 2: Axiom Users Guide}" >>toc.toc ; \
	cat bookvol2.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 3: Axiom Programmers Guide}" >>toc.toc ; \
	cat bookvol3.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 4: Axiom Developers Guide}" >>toc.toc ; \
	cat bookvol4.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 5: Axiom Interpreter}" >>toc.toc ; \
	cat bookvol5.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 6: Axiom Command}" >>toc.toc ; \
	cat bookvol6.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 7: Axiom Hyperdoc}" >>toc.toc ; \
	cat bookvol7.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 8: Axiom Graphics}" >>toc.toc ; \
	cat bookvol8.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 9: Axiom Compiler}" >>toc.toc ; \
	cat bookvol9.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 10: Axiom Algebra}" >>toc.toc ; \
	cat bookvol10.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 11: Axiom Browser}" >>toc.toc ; \
	cat bookvol11.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 12: Axiom Crystal}" >>toc.toc ; \
	cat bookvol12.toc >>toc.toc ; \
	if [ -z "${NOISE}" ] ; then \
	  ${LATEX} toc.tex ; \
	  ${DVIPS} toc.dvi 2>/dev/null ; \
	  ${PS2PDF} toc.ps >/dev/null ; \
	  ${RM} -f *.toc toc.aux toc.dvi toc.log toc.ps toc.tex toc.toc ; \
	else \
	  ${LATEX} toc.tex >${TMP}/trace ; \
	  ${DVIPS} toc.dvi 2>${TMP}/trace ; \
	  ${PS2PDF} toc.ps >${TMP}/trace ; \
	  ${RM} -f *.toc toc.aux toc.dvi toc.log toc.ps toc.tex toc.toc ; \
	fi )

${PDF}/axiom.sty: ${SRC}/scripts/tex/axiom.sty
	@echo 14 making ${PDF}/axiom.sty from ${SRC}/scripts/tex/axiom.sty
	@cp ${SRC}/scripts/tex/axiom.sty ${PDF}/axiom.sty

@
\eject
\begin{thebibliography}{99}
\bibitem{1} CMUCL {\bf http://www.cons.org/cmucl}
\bibitem{2} GCL {\bf http://savannah.gnu.org/projects/gcl}
\bibitem{3} Codemist Ltd, ``Alta'', Horsecombe Vale Combs Down
Bath BA2 5QR UK Tel. +44-1225-837430 
{\bf http://www.codemist.co.uk}
\bibitem{4} \$SPAD/zips/noweb-2.10a.tgz, the noweb source tree
\bibitem{5} \$SPAD/zips/advi-1.2.0.tar.gz, the advi source tree
\end{thebibliography}
\end{document}

