\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{books/Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
This Makefile creates all the primary documentation for Axiom
as pdf files in the final output tree.
\end{abstract}
\eject
\tableofcontents
\eject
Note that we need to set the SHELL variable here because the
default shell appears to be /bin/sh which does not follow the
semantics of echo used by /bin/bash. Thus, while trying to 
write the backslash-newpage lines the backslash-n gets interpreted
as a newline.
\section{The Makefile}
<<*>>=
SHELL=bash
PDF=${AXIOM}/doc
IN=${SPD}/books
LATEX=latex
MAKEINDEX=makeindex
DVIPDFM=dvipdfm
DVIPS=dvips -Ppdf
PS2PDF=ps2pdf
RM=rm -f

BOOKS=${PDF}/bookvol0.pdf ${PDF}/bookvol1.pdf ${PDF}/bookvol2.pdf \
      ${PDF}/bookvol3.pdf ${PDF}/bookvol4.pdf \
      ${PDF}/bookvol7.1.pdf \
      ${PDF}/bookvol8.pdf ${PDF}/bookvol10.pdf \
      ${PDF}/bookvol10.1.pdf ${PDF}/bookvol10.2.pdf ${PDF}/bookvol10.3.pdf \
      ${PDF}/bookvol10.4.pdf ${PDF}/bookvol10.5.pdf \
      ${PDF}/bookvol11.pdf ${PDF}/bookvol12.pdf ${PDF}/bookvolbib.pdf

BUUKS=${PDF}/bookvol5.pdf ${PDF}/bookvol6.pdf ${PDF}/bookvol7.pdf \
      ${PDF}/bookvol9.pdf 

all: ${PDF}/axiom.sty ${BUUKS} ${BOOKS} ${PDF}/toc.pdf

${PDF}/bookvol5.pdf: ${IN}/bookvol5.pamphlet 
	@echo books/1 making ${PDF}/bookvol5.pdf from ${IN}/bookvol5.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol5.pamphlet ${PDF}/bookvol5.tex ; \
	  cp -pr ${IN}/ps ${PDF} ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${RM} bookvol5.toc ; \
	    ${LATEX} bookvol5.tex ; \
	    ${MAKEINDEX} bookvol5 >/dev/null ; \
	    ${LATEX} bookvol5.tex >/dev/null ; \
	    ${DVIPDFM} bookvol5.dvi 2>/dev/null ; \
	    ${RM} bookvol5.aux bookvol5.dvi bookvol5.log bookvol5.ps ; \
            ${RM} bookvol5.idx bookvol5.tex bookvol5.pamphlet ; \
	    ${RM} bookvol5.ilg bookvol5.ind ; \
	  else \
	    ${RM} bookvol5.toc ; \
	    ${LATEX} bookvol5.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${MAKEINDEX} bookvol5 >${TMP}/trace ; \
	    ${LATEX} bookvol5.tex >${TMP}/trace ; \
	    ${DVIPDFM} bookvol5.dvi 2>${TMP}/trace ; \
	    ${RM} bookvol5.aux bookvol5.dvi bookvol5.log bookvol5.ps ; \
            ${RM} bookvol5.idx bookvol5.tex bookvol5.pamphlet ; \
	    ${RM} bookvol5.ilg bookvol5.ind ; \
	  fi )

${PDF}/bookvol6.pdf: ${IN}/bookvol6.pamphlet 
	@echo books/1 making ${PDF}/bookvol6.pdf from ${IN}/bookvol6.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol6.pamphlet ${PDF}/bookvol6.tex ; \
	  cp -pr ${IN}/ps ${PDF} ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${RM} bookvol6.toc ; \
	    ${LATEX} bookvol6.tex ; \
	    ${MAKEINDEX} bookvol6 >/dev/null ; \
	    ${LATEX} bookvol6.tex >/dev/null ; \
	    ${DVIPDFM} bookvol6.dvi 2>/dev/null ; \
	    ${RM} bookvol6.aux bookvol6.dvi bookvol6.log bookvol6.ps ; \
            ${RM} bookvol6.idx bookvol6.tex bookvol6.pamphlet ; \
	    ${RM} bookvol6.ilg bookvol6.ind ; \
	  else \
	    ${RM} bookvol6.toc ; \
	    ${LATEX} bookvol6.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${MAKEINDEX} bookvol6 >${TMP}/trace ; \
	    ${LATEX} bookvol6.tex >${TMP}/trace ; \
	    ${DVIPDFM} bookvol6.dvi 2>${TMP}/trace ; \
	    ${RM} bookvol6.aux bookvol6.dvi bookvol6.log bookvol6.ps ; \
            ${RM} bookvol6.idx bookvol6.tex bookvol6.pamphlet ; \
	    ${RM} bookvol6.ilg bookvol6.ind ; \
	  fi )

${PDF}/bookvol7.pdf: ${IN}/bookvol7.pamphlet 
	@echo books/1 making ${PDF}/bookvol7.pdf from ${IN}/bookvol7.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol7.pamphlet ${PDF}/bookvol7.tex ; \
	  cp -pr ${IN}/ps ${PDF} ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${RM} bookvol7.toc ; \
	    ${LATEX} bookvol7.tex ; \
	    ${MAKEINDEX} bookvol7 >/dev/null ; \
	    ${LATEX} bookvol7.tex >/dev/null ; \
	    ${DVIPDFM} bookvol7.dvi 2>/dev/null ; \
	    ${RM} bookvol7.aux bookvol7.dvi bookvol7.log bookvol7.ps ; \
            ${RM} bookvol7.idx bookvol7.tex bookvol7.pamphlet ; \
	    ${RM} bookvol7.ilg bookvol7.ind ; \
	  else \
	    ${RM} bookvol7.toc ; \
	    ${LATEX} bookvol7.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${MAKEINDEX} bookvol7 >${TMP}/trace ; \
	    ${LATEX} bookvol7.tex >${TMP}/trace ; \
	    ${DVIPDFM} bookvol7.dvi 2>${TMP}/trace ; \
	    ${RM} bookvol7.aux bookvol7.dvi bookvol7.log bookvol7.ps ; \
            ${RM} bookvol7.idx bookvol7.tex bookvol7.pamphlet ; \
	    ${RM} bookvol7.ilg bookvol7.ind ; \
	  fi )

${PDF}/bookvol9.pdf: ${IN}/bookvol9.pamphlet 
	@echo books/1 making ${PDF}/bookvol9.pdf from ${IN}/bookvol9.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/bookvol9.pamphlet ${PDF}/bookvol9.tex ; \
	  cp -pr ${IN}/ps ${PDF} ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${RM} bookvol9.toc ; \
	    ${LATEX} bookvol9.tex ; \
	    ${MAKEINDEX} bookvol9 >/dev/null ; \
	    ${LATEX} bookvol9.tex >/dev/null ; \
	    ${DVIPDFM} bookvol9.dvi 2>/dev/null ; \
	    ${RM} bookvol9.aux bookvol9.dvi bookvol9.log bookvol9.ps ; \
            ${RM} bookvol9.idx bookvol9.tex bookvol9.pamphlet ; \
	    ${RM} bookvol9.ilg bookvol9.ind ; \
	  else \
	    ${RM} bookvol9.toc ; \
	    ${LATEX} bookvol9.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${MAKEINDEX} bookvol9 >${TMP}/trace ; \
	    ${LATEX} bookvol9.tex >${TMP}/trace ; \
	    ${DVIPDFM} bookvol9.dvi 2>${TMP}/trace ; \
	    ${RM} bookvol9.aux bookvol9.dvi bookvol9.log bookvol9.ps ; \
            ${RM} bookvol9.idx bookvol9.tex bookvol9.pamphlet ; \
	    ${RM} bookvol9.ilg bookvol9.ind ; \
	  fi )

${PDF}/%.pdf: ${IN}/%.pamphlet 
	@echo 0 making ${PDF}/$*.pdf from ${IN}/$*.pamphlet
	@(cd ${PDF} ; \
	  cp ${IN}/$*.pamphlet ${PDF} ; \
	  cp -pr ${IN}/ps ${PDF} ; \
	  ${WEAVE} -delay $*.pamphlet >$*.tex ; \
	  if [ -z "${NOISE}" ] ; then \
	    ${RM} $*.toc ; \
	    ${LATEX} $*.tex ; \
	    ${MAKEINDEX} $* >/dev/null ; \
	    ${LATEX} $*.tex >/dev/null ; \
	    ${DVIPDFM} $*.dvi 2>/dev/null ; \
	    ${RM} $*.aux $*.dvi $*.log $*.ps $*.idx $*.tex $*.pamphlet ; \
	    ${RM} $*.ilg $*.ind ; \
	  else \
	    ${RM} $*.toc ; \
	    ${LATEX} $*.tex >${TMP}/trace ; \
	    echo ...first latex complete ; \
	    ${MAKEINDEX} $* >${TMP}/trace ; \
	    ${LATEX} $*.tex >${TMP}/trace ; \
	    ${DVIPDFM} $*.dvi 2>${TMP}/trace ; \
	    ${RM} $*.aux $*.dvi $*.log $*.ps $*.idx $*.tex $*.pamphlet ; \
	    ${RM} $*.ilg $*.ind ; \
	  fi )

@
\section{Combined Table of Contents}
This is the table of contents from the existing volumes combined into
one document for easy reference.

It turns out that the hyperref package adds junk on the end of the 
lines in the .toc files. We use these files to create the combined
table of contents so we need to clean up after hyperref. These 
patterns remove the last braced item in the line. If a new one
shows up you'll have to add the pattern here to remove it.

The cruft I've found so far has the forms:
\begin{itemize}
\item \verb|{chapter.1}|
\item \verb|{section.1.1}|
\item \verb|{subsection.1.1}|
\item \verb|{appendix.A}|
\item \verb|{section.A.1}|
\item \verb|{subsection.A.1}|
\end{itemize}
The sed patterns to match and remove them (in order) are:
<<sed pattern>>=
	sed -e 's/{chapter.[0-9]*}//' \
            -e 's/{section.[0-9]*.[0-9]*}//' \
            -e 's/{subsection.[0-9]*.[0-9]*.[0-9]*}//' \
            -e 's/{appendix.*}//' \
            -e 's/{section.[A-Z]*.[0-9]*}//' \
            -e 's/{subsection.[A-Z]*.[0-9]*.[0-9]*}//' \
@
<<*>>=
${PDF}/toc.pdf: ${BOOKS}
	@echo 13 making ${PDF}/toc.pdf
	@(cd ${PDF} ; \
	echo "\\documentclass{book}" >toc.tex ; \
	echo "\\setlength{\\textwidth}{400pt}" >>toc.tex ; \
	echo "\\usepackage{amssymb}" >>toc.tex ; \
	echo "\\begin{document}" >>toc.tex ; \
	echo "{\\bf Volume ~ 0}: Axiom {\\sl Jenks and Sutor}\\\\" >toc.toc ; \
	echo "{\\bf Volume ~ 1}: Axiom {\\sl Tutorial}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 2}: Axiom {\\sl Users Guide}\\\\" >>toc.toc ; \
	echo \
         "{\\bf Volume ~ 3}: Axiom {\\sl Programmers Guide}\\\\" >>toc.toc ; \
	echo \
         "{\\bf Volume ~ 4}: Axiom {\\sl Developers Guide}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 5}: Axiom {\\sl Interpreter}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 6}: Axiom {\\sl Command}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 7}: Axiom {\\sl Hyperdoc}\\\\" >>toc.toc ; \
	echo \
         "{\\bf Volume ~ 7.1}: Axiom {\\sl Hyperdoc Pages}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 8}: Axiom {\\sl Graphics}\\\\" >>toc.toc ; \
	echo "{\\bf Volume ~ 9}: Axiom {\\sl Compiler}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 10}: Axiom {\\sl Algebra: Implementation}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 10.1}: Axiom {\\sl Algebra: Theory}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 10.2}: Axiom {\\sl Algebra: Categories}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 10.3}: Axiom {\\sl Algebra: Domains}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 10.4}: Axiom {\\sl Algebra: Packages}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 10.5}: Axiom {\\sl Algebra: Numerics}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 11}: Axiom {\\sl Browser}\\\\" >>toc.toc ; \
	echo "{\\bf Volume 12}: Axiom {\\sl Crystal}\\\\" >>toc.toc ; \
	echo "{\\bf Bibliography}: Axiom {\\sl Bibliography}\\\\" >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\tableofcontents" >>toc.tex ; \
	echo "\\end{document}" >>toc.tex ; \
	echo "\\section*{Volume 0: Axiom Jenks and Sutor}" >>toc.toc ; \
<<sed pattern>>
            <bookvol0.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 1: Axiom Tutorial}" >>toc.toc ; \
<<sed pattern>>
            <bookvol1.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 2: Axiom Users Guide}" >>toc.toc ; \
<<sed pattern>>
            <bookvol2.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 3: Axiom Programmers Guide}" >>toc.toc ; \
<<sed pattern>>
            <bookvol3.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 4: Axiom Developers Guide}" >>toc.toc ; \
<<sed pattern>>
            <bookvol4.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 5: Axiom Interpreter}" >>toc.toc ; \
<<sed pattern>>
            <bookvol5.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 6: Axiom Command}" >>toc.toc ; \
<<sed pattern>>
            <bookvol6.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 7: Axiom Hyperdoc}" >>toc.toc ; \
<<sed pattern>>
            <bookvol7.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 7.1: Axiom Hyperdoc}" >>toc.toc ; \
<<sed pattern>>
            <bookvol7.1.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 8: Axiom Graphics}" >>toc.toc ; \
<<sed pattern>>
            <bookvol8.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 9: Axiom Compiler}" >>toc.toc ; \
<<sed pattern>>
            <bookvol9.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 10: Axiom Algebra: Implementation}" >>toc.toc ; \
<<sed pattern>>
            <bookvol10.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 10.1: Axiom Algebra: Theory}" >>toc.toc ; \
<<sed pattern>>
            <bookvol10.1.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 10.2: Axiom Algebra: Categories}" >>toc.toc ; \
<<sed pattern>>
            <bookvol10.2.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 10.3: Axiom Algebra: Domains}" >>toc.toc ; \
<<sed pattern>>
            <bookvol10.3.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 10.4: Axiom Algebra: Packages}" >>toc.toc ; \
<<sed pattern>>
            <bookvol10.4.toc >>toc.toc ; \
            <bookvol10.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 10.5: Axiom Algebra: Numerics}" >>toc.toc ; \
<<sed pattern>>
            <bookvol10.5.toc >>toc.toc ; \
            <bookvol10.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 11: Axiom Browser}" >>toc.toc ; \
<<sed pattern>>
            <bookvol11.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Volume 12: Axiom Crystal}" >>toc.toc ; \
<<sed pattern>>
            <bookvol12.toc >>toc.toc ; \
	echo "\\newpage" >>toc.toc ; \
	echo "\\section*{Bibliography: Axiom Bibliography}" >>toc.toc ; \
<<sed pattern>>
            <bookvolbib.toc >>toc.toc ; \
	if [ -z "${NOISE}" ] ; then \
	  ${LATEX} toc.tex ; \
	  ${DVIPS} toc.dvi 2>/dev/null ; \
	  ${PS2PDF} toc.ps 2>/dev/null ; \
	  ${RM} -f toc.aux toc.dvi toc.log toc.ps toc.tex toc.toc ; \
	else \
	  ${LATEX} toc.tex >${TMP}/trace ; \
	  ${DVIPS} toc.dvi 2>${TMP}/trace ; \
	  ${PS2PDF} toc.ps 2>${TMP}/trace ; \
	  ${RM} -f toc.aux toc.dvi toc.log toc.ps toc.tex toc.toc ; \
	fi )

${PDF}/axiom.sty: ${SRC}/scripts/tex/axiom.sty
	@echo 14 making ${PDF}/axiom.sty from ${SRC}/scripts/tex/axiom.sty
	@cp ${SRC}/scripts/tex/axiom.sty ${PDF}/axiom.sty

@
\section{Combined Bibliography}
\eject
\begin{thebibliography}{99}
\bibitem{1} CMUCL {\bf http://www.cons.org/cmucl}
\bibitem{2} GCL {\bf http://savannah.gnu.org/projects/gcl}
\bibitem{3} Codemist Ltd, ``Alta'', Horsecombe Vale Combs Down
Bath BA2 5QR UK Tel. +44-1225-837430 
{\bf http://www.codemist.co.uk}
\bibitem{4} \$SPAD/zips/noweb-2.10a.tgz, the noweb source tree
\bibitem{5} \$SPAD/zips/advi-1.2.0.tar.gz, the advi source tree
\end{thebibliography}
\end{document}

