#!/bin/sh
latex=`which latex`
if [ "$latex" = "" ] ; then
  echo document ERROR You must install latex first
  exit 0
fi
if [ ! -f axiom.sty ] ; then cp $AXIOM/bin/tex/axiom.sty . ; fi
tangle=$AXIOM/bin/lib/notangle
weave=$AXIOM/bin/lib/noweave
if [ "$#" = "3" ]; then
 REDIRECT=$2
 FILE=`basename $3 .pamphlet`
 $tangle -t8 $FILE.pamphlet >$FILE
 $weave -delay $FILE.pamphlet >$FILE.tex
 if [ ! -f axiom.sty ] ; then cp $AXIOM/bin/tex/axiom.sty . ; fi
 $latex --interaction nonstopmode $FILE.tex >$REDIRECT
 $latex --interaction nonstopmode $FILE.tex >$REDIRECT
 rm -f $FILE~
 rm -f $FILE.pamphlet~
 rm -f $FILE.log
 rm -f $FILE.tex
 rm -f $FILE.toc
 rm -f $FILE.aux
 exit 0
fi
if [ "$#" = "1" ]; then
 FILE=`basename $1 .pamphlet`
 $tangle -t8 $FILE.pamphlet >$FILE
 $weave -delay $FILE.pamphlet >$FILE.tex
 $latex $FILE.tex 
 $latex $FILE.tex
 rm -f $FILE~
 rm -f $FILE.pamphlet~
 rm -f $FILE.log
 rm -f $FILE.tex
 rm -f $FILE.toc
 rm -f $FILE.aux
 exit 0
fi
echo "document [ -o redirect ] pamphlet"


