\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/scripts Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{The Makefile}
This Makefile checks to make sure that the command line scripts
exist in the bin subdirectory. We depend on the ``document'' 
script to exist and prevent duplicate copying.
<<*>>=
OUT=${MNT}/${SYS}/bin
OUT1=${MNT}/${SYS}/lib

all: announce ${OUT}/document ${OUT1}/SPADEDIT

announce:
	@ echo ======================================
	@ echo src/scripts BUILDING SCRIPTS
	@ echo ======================================

${OUT}/document:
	@echo 1 making ${SRC}/scripts
	@cp -pr * ${OUT}
	@mkdir -p ${OUT}/tex
	@rm -f ${OUT}/Makefile*
	@rm -f ${OUT}/SPADEDIT

${OUT1}/SPADEDIT:
	@echo 2 making ${OUT1}/SPADEDIT from ${SRC}/scripts/SPADEDIT
	@mkdir -p ${OUT1}
	@cp ${SRC}/scripts/SPADEDIT ${OUT1}/SPADEDIT

clean:
	@echo 2 cleaning ${SRC}/scripts

@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
