\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/sman Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{Environment variables}
<<environment>>=
# this is where we are compiling from
IN=     ${SRC}/sman

# this is the intermediate place 
MID=    ${INT}/sman

# this is the intermediate place 
MIDOBJ=    ${OBJ}/${SYS}/sman

# this is where to put the various commands
OUT=	${MNT}/${SYS}/bin
OUTLIB=	${MNT}/${SYS}/lib

# this is where the include files live
INC=    ${SRC}/include

# this is where we hid the libspad library
LIB=	${OBJ}/${SYS}/lib

# this is where the documentation ends up
DOC=    ${MNT}/${SYS}/doc
CFLAGS=	${CCF} 
LDFLAGS= -L${LIB} -lspad ${LDF}

DOCFILES=${DOC}/bookvol6.dvi
SMANOBJS= ${LIB}/libspad.a

@
\section{The axiom command}
<<axiomcmd>>=
${OUT}/axiom: ${IN}/bookvol6.pamphlet
	@echo 1 making ${OUT}/axiom from ${IN}/bookvol6.pamphlet
	@ (cd ${OUT} ; \
           ${TANGLE} -R"axiomcmd" ${IN}/bookvol6.pamphlet >axiom )
	@chmod +x ${OUT}/axiom

@
\section{session}
<<session>>=
${OUTLIB}/session: ${SMANOBJS} ${MIDOBJ}/session.o
	@ echo 1 linking session
	@ ${CC} -o ${OUTLIB}/session ${MIDOBJ}/session.o ${SMANOBJS} 

${MID}/session.c: ${IN}/bookvol6.pamphlet
	@ echo 2 making ${MID}/session.c from ${IN}/bookvol6.pamphlet
	@ (cd ${MID} ; \
          ${TANGLE} -R"session" ${IN}/bookvol6.pamphlet >session.c )

${MIDOBJ}/session.o: ${MID}/session.c ${INC}/session.h1
	@ echo 3 making ${MIDOBJ}/session.o from ${MID}/session.c
	@ ( cd ${MIDOBJ} ; ${CC} -c ${CFLAGS} ${MID}/session.c -I${INC} )

@
\section{nagman}
Note that we do not build the nagman component as we do not have the
necessary code (for instance, [[callnag]]).
<<nagman>>=
${OUT}/nagman:	${SMANOBJS} ${MIDOBJ}/nagman.o
	@ echo 5 linking nagman
	@ ${CC} -o ${OUT}/nagman ${MIDOBJ}/nagman.o ${SMANOBJS} 

${MID}/nagman.c: ${IN}/bookvol6.pamphlet
	@ echo 6 making ${MID}/nagman.c from ${IN}/bookvol6.pamphlet
	@ (cd ${MID} ; \
           ${TANGLE} -R"nagman" ${IN}/bookvol6.pamphlet >nagman.c )

${MIDOBJ}/nagman.o: ${MID}/nagman.c ${INC}/nagman.h1
	@ echo 7 making ${MIDOBJ}/nagman.o from ${MID}/nagman.c
	@ ( cd ${MIDOBJ} ; ${CC} -c ${CFLAGS} ${MID}/nagman.c -I${INC} )

@
\section{spadclient}
<<spadclient>>=
${OUTLIB}/spadclient: ${SMANOBJS} ${MIDOBJ}/spadclient.o
	@ echo 9 linking spadclient
	@ ${CC} -o ${OUTLIB}/spadclient ${MIDOBJ}/spadclient.o  ${SMANOBJS} 

${MID}/spadclient.c: ${IN}/bookvol6.pamphlet
	@ echo 10 making ${MID}/spadclient.c from ${IN}/bookvol6.pamphlet
	@ (cd ${MID} ; \
           ${TANGLE} -R"spadclient" ${IN}/bookvol6.pamphlet >spadclient.c )

${MIDOBJ}/spadclient.o: ${MID}/spadclient.c ${INC}/spadclient.h1
	@ echo 11 making ${MIDOBJ}/spadclient.o from ${MID}/spadclient.c
	@ ( cd ${MIDOBJ} ; ${CC} -c ${CFLAGS} ${MID}/spadclient.c -I${INC} )

@
\section{sman}
<<sman>>=
${OUT}/sman: ${SMANOBJS} ${MIDOBJ}/sman.o
	@ echo 13 linking sman
	@ ${CC} -o ${OUT}/sman ${MIDOBJ}/sman.o ${SMANOBJS} 

${MID}/sman.h: ${IN}/bookvol6.pamphlet
	@ echo 00 making ${MID}/sman.h from ${IN}/bookvol6.pamphlet
	@ (cd ${MID} ; \
           ${TANGLE} -R"sman.h" ${IN}/bookvol6.pamphlet >sman.h )

${MID}/sman.c: ${MID}/sman.h ${IN}/bookvol6.pamphlet
	@ echo 14 making ${MID}/sman.c from ${IN}/bookvol6.pamphlet
	@ (cd ${MID} ; \
           ${TANGLE} -R"sman" ${IN}/bookvol6.pamphlet >sman.c )

${MIDOBJ}/sman.o: ${MID}/sman.c ${INC}/sman.h1
	@ echo 15 making ${MIDOBJ}/sman.o from ${MID}/sman.c
	@ ( cd ${MIDOBJ} ; ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/sman.c )

${DOC}/bookvol6.dvi: ${IN}/bookvol6.pamphlet 
	@ echo 16 making ${DOC}/bookvol6.dvi from ${IN}/bookvol6.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/bookvol6.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} bookvol6 ; \
	rm -f ${DOC}/bookvol6.pamphlet ; \
	rm -f ${DOC}/bookvol6.idx ; \
	rm -f ${DOC}/bookvol6.tex ; \
	rm -f ${DOC}/bookvol6 )

@
<<*>>=
<<environment>>
all:	${OUTLIB}/session ${OUTLIB}/spadclient ${OUT}/sman ${OUT}/axiom \
        ${DOCFILES}
	@ echo 18 finished ${IN}

clean:
	@echo 19 cleaning ${SRC}/sman

<<axiomcmd>>
<<sman>>
<<session>>
<<spadclient>>
<<nagman>>
@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
