\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/sman Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{Environment variables}
<<environment>>=
# this is where we are compiling from
IN=     ${SRC}/sman

# this is the intermediate place 
MID=    ${INT}/sman

# this is the intermediate place 
MIDOBJ=    ${OBJ}/${SYS}/sman

# this is where to put the various commands
OUT=	${MNT}/${SYS}/bin
OUTLIB=	${MNT}/${SYS}/lib

# this is where the include files live
INC=    ${SRC}/include

# this is where we hid the libspad library
LIB=	${OBJ}/${SYS}/lib

# this is where the documentation ends up
DOC=    ${MNT}/${SYS}/doc/src/sman
CFLAGS=	${CCF} 
LDFLAGS= -L${LIB} -lspad ${LDF}

DOCFILES=${DOC}/session.c.dvi ${DOC}/nagman.c.dvi ${DOC}/sman.c.dvi \
         ${DOC}/spadclient.c.dvi

SMANOBJS= ${LIB}/libspad.a

@
\section{session}
<<session>>=
${OUTLIB}/session: ${SMANOBJS} ${MIDOBJ}/session.o
	@ echo 1 linking session
	@ ${CC} -o ${OUTLIB}/session ${MIDOBJ}/session.o ${SMANOBJS} 

${MID}/session.c: ${IN}/session.c.pamphlet
	@ echo 2 making ${MID}/session.c from ${IN}/session.c.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/session.c.pamphlet >session.c )

${MIDOBJ}/session.o: ${MID}/session.c ${INC}/session.H1
	@ echo 3 making ${MIDOBJ}/session.o from ${MID}/session.c
	@ ( cd ${MIDOBJ} ; ${CC} -c ${CFLAGS} ${MID}/session.c -I${INC} )

${DOC}/session.c.dvi: ${IN}/session.c.pamphlet 
	@ echo 4 making ${DOC}/session.c.dvi from ${IN}/session.c.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/session.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} session.c ; \
	rm -f ${DOC}/session.c.pamphlet ; \
	rm -f ${DOC}/session.c.tex ; \
	rm -f ${DOC}/session.c )

@
\section{nagman}
Note that we do not build the nagman component as we do not have the
necessary code (for instance, [[callnag]]).
<<nagman>>=
${OUT}/nagman:	${SMANOBJS} ${MIDOBJ}/nagman.o
	@ echo 5 linking nagman
	@ ${CC} -o ${OUT}/nagman ${MIDOBJ}/nagman.o ${SMANOBJS} 

${MID}/nagman.c: ${IN}/nagman.c.pamphlet
	@ echo 6 making ${MID}/nagman.c from ${IN}/nagman.c.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/nagman.c.pamphlet >nagman.c )

${MIDOBJ}/nagman.o: ${MID}/nagman.c ${INC}/nagman.H1
	@ echo 7 making ${MIDOBJ}/nagman.o from ${MID}/nagman.c
	@ ( cd ${MIDOBJ} ; ${CC} -c ${CFLAGS} ${MID}/nagman.c -I${INC} )

${DOC}/nagman.c.dvi: ${IN}/nagman.c.pamphlet 
	@ echo 8 making ${DOC}/nagman.c.dvi from ${IN}/nagman.c.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/nagman.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} nagman.c ; \
	rm -f ${DOC}/nagman.c.pamphlet ; \
	rm -f ${DOC}/nagman.c.tex ; \
	rm -f ${DOC}/nagman.c )

@
\section{spadclient}
<<spadclient>>=
${OUTLIB}/spadclient: ${SMANOBJS} ${MIDOBJ}/spadclient.o
	@ echo 9 linking spadclient
	@ ${CC} -o ${OUTLIB}/spadclient ${MIDOBJ}/spadclient.o  ${SMANOBJS} 

${MID}/spadclient.c: ${IN}/spadclient.c.pamphlet
	@ echo 10 making ${MID}/spadclient.c from ${IN}/spadclient.c.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/spadclient.c.pamphlet >spadclient.c )

${MIDOBJ}/spadclient.o: ${MID}/spadclient.c ${INC}/spadclient.H1
	@ echo 11 making ${MIDOBJ}/spadclient.o from ${MID}/spadclient.c
	@ ( cd ${MIDOBJ} ; ${CC} -c ${CFLAGS} ${MID}/spadclient.c -I${INC} )

${DOC}/spadclient.c.dvi: ${IN}/spadclient.c.pamphlet 
	@ echo 12 making ${DOC}/spadclient.c.dvi from ${IN}/spadclient.c.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/spadclient.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} spadclient.c ; \
	rm -f ${DOC}/spadclient.c.pamphlet ; \
	rm -f ${DOC}/spadclient.c.tex ; \
	rm -f ${DOC}/spadclient.c )

@
\section{sman}
<<sman>>=
${OUT}/sman: ${SMANOBJS} ${MIDOBJ}/sman.o
	@ echo 13 linking sman
	@ ${CC} -o ${OUT}/sman ${MIDOBJ}/sman.o ${SMANOBJS} 

${MID}/sman.h: ${IN}/sman.c.pamphlet
	@ echo 00 making ${MID}/sman.h from ${IN}/sman.c.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"sman.h" ${IN}/sman.c.pamphlet >sman.h )

${MID}/sman.c: ${MID}/sman.h ${IN}/sman.c.pamphlet
	@ echo 14 making ${MID}/sman.c from ${IN}/sman.c.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/sman.c.pamphlet >sman.c )

${MIDOBJ}/sman.o: ${MID}/sman.c ${INC}/sman.H1
	@ echo 15 making ${MIDOBJ}/sman.o from ${MID}/sman.c
	@ ( cd ${MIDOBJ} ; ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/sman.c )

${DOC}/sman.c.dvi: ${IN}/sman.c.pamphlet 
	@ echo 16 making ${DOC}/sman.c.dvi from ${IN}/sman.c.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/sman.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} sman.c ; \
	rm -f ${DOC}/sman.c.pamphlet ; \
	rm -f ${DOC}/sman.c.tex ; \
	rm -f ${DOC}/sman.c )

@
<<*>>=
<<environment>>
all:	${OUTLIB}/session ${OUTLIB}/spadclient ${OUT}/sman ${DOCFILES}
	@ echo 18 finished ${IN}

clean:
	@echo 19 cleaning ${SRC}/sman

<<sman>>
<<session>>
<<spadclient>>
<<nagman>>
@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
