\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/booklets Makefile.pamphlet}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
<<*>>=
all:
	@echo 1 building ${INT}/docs/src/booklets
	@cp Rosetta.pamphlet ${INT}/docs/src/booklets
	@(cd ${INT}/docs/src/booklets ; \
	  ${DOCUMENT} ${NOISE} Rosetta )

clean:
	@echo 2 cleaning ${INT}/docs/src/booklets
	@rm -rf ${INT}/docs/src/booklets
	@rm -f Makefile Makefile.dvi
@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
