\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/graph Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{Directory overview}
\subsection{Environment variables}
DIRS is a list of directories with the suffix {\bf dir}.

Thus if we have a new directory {\bf foo} add it to the {\bf DIRS}
variable as {\bf foodir}. It will automatically be added to {\bf DOCS}
as {\bf foodocument} and {\bf CLNS} as {\bf fooclean}.

These variables are used to drive the make, make document, and
make clean processes, respectively.

<<environment>>=
BOOK=${SPD}/books/bookvol8.pamphlet
DIRS=viewmandir gdrawsdir view2ddir view3ddir viewalonedir

@
\subsection{The viewman directory}
<<viewmandir>>=
viewmandir: ${SRC}/graph/viewman/Makefile
	@ echo 1 making ${SRC}/graph/viewman 
	@ mkdir -p ${OBJ}/${SYS}/graph/viewman
	@ mkdir -p ${OBJ}/${SYS}/lib
	@ mkdir -p ${MNT}/${SYS}/lib
	@ mkdir -p ${MNT}/${SYS}/doc/src/graph
	@(cd ${INT}/graph/viewman ; ${ENV} ${MAKE} )

${SRC}/graph/viewman/Makefile: ${BOOK}
	@echo 2 making ${SRC}/graph/viewman/Makefile from ${BOOK}
	@ mkdir -p ${INT}/graph/viewman
	@( cd ${INT}/graph/viewman ; \
	  ${TANGLE} -t8 -R"viewman/Makefile" ${BOOK} >Makefile )

@
\subsection{The gdraws directory}
<<gdrawsdir>>=
gdrawsdir: ${SRC}/graph/gdraws/Makefile
	@echo 5 making ${SRC}/graph/gdraws
	@mkdir -p ${INT}/graph/gdraws
	@mkdir -p ${OBJ}/${SYS}/graph/gdraws
	@mkdir -p ${MNT}/${SYS}/lib
	@mkdir -p ${MNT}/${SYS}/lib/graph
	@mkdir -p ${MNT}/${SYS}/doc/src/graph
	@(cd gdraws ; ${ENV} ${MAKE} )

${SRC}/graph/gdraws/Makefile: ${SRC}/graph/gdraws/Makefile.pamphlet
	@echo 6 making ${SRC}/graph/gdraws/Makefile from ${SRC}/graph/gdraws/Makefile.pamphlet
	@( cd gdraws ; \
           ${DOCUMENT} ${NOISE} Makefile ; \
	   cp Makefile.dvi ${MNT}/${SYS}/doc/src/graph.gdraws.Makefile.dvi )

gdrawsdocument: ${SRC}/graph/gdraws/Makefile
	@echo 7 documenting ${SRC}/graph/gdraws
	@( cd gdraws ; ${ENV} ${MAKE} document )

gdrawsclean: ${SRC}/graph/gdraws/Makefile
	@echo 8 cleaning ${SRC}/graph/gdraws
	@( cd gdraws ; ${ENV} ${MAKE} clean )
	@rm -f ${SRC}/graph/gdraws/Makefile
	@rm -f ${SRC}/graph/gdraws/Makefile.dvi

@
\subsection{The view3d directory}
<<view3ddir>>=
view3ddir: ${SRC}/graph/view3d/Makefile
	@echo 9 making ${SRC}/graph/view3d
	@mkdir -p ${OBJ}/${SYS}/graph/view3d
	@mkdir -p ${OBJ}/${SYS}/lib
	@mkdir -p ${OBJ}/${SYS}/graph/gdraws
	@mkdir -p ${MNT}/${SYS}/lib
	@mkdir -p ${MNT}/${SYS}/doc/src/graph
	@(cd ${INT}/graph/view3d ; ${ENV} ${MAKE} )

${SRC}/graph/view3d/Makefile: ${BOOK}
	@echo 10 making ${SRC}/graph/view3d/Makefile from ${BOOK}
	@mkdir -p ${INT}/graph/view3d
	@( cd ${INT}/graph/view3d ; \
	  ${TANGLE} -t8 -R"view3d/Makefile" ${BOOK} >Makefile )

@
\subsection{The view2d directory}
<<view2ddir>>=
view2ddir: ${INT}/graph/view2d/Makefile
	@echo 13 making bookvol8 view2d
	@mkdir -p ${OBJ}/${SYS}/graph/view2d
	@mkdir -p ${OBJ}/${SYS}/lib
	@mkdir -p ${MNT}/${SYS}/lib
	@mkdir -p ${MNT}/${SYS}/doc/src/graph
	@(cd ${INT}/graph/view2d ; ${ENV} ${MAKE} )

${INT}/graph/view2d/Makefile: ${BOOK}
	@echo 14 making ${SRC}/graph/view2d/Makefile from ${BOOK}
	@mkdir -p ${INT}/graph/view2d
	@( cd ${INT}/graph/view2d ; \
	  ${TANGLE} -t8 -R"view2d/Makefile" ${BOOK} >Makefile )

@
\subsection{The viewalone directory}
<<viewalonedir>>=
viewalonedir: ${SRC}/graph/viewalone/Makefile
	@echo 17 making ${SRC}/graph/viewalone
	@mkdir -p ${OBJ}/${SYS}/graph/viewalone
	@mkdir -p ${MNT}/${SYS}/bin
	@mkdir -p ${MNT}/${SYS}/doc/src/graph
	@(cd viewalone ; ${ENV} ${MAKE} )

${SRC}/graph/viewalone/Makefile: ${BOOK} 
	@echo 18 making ${SRC}/graph/viewalone/Makefile from ${BOOK} 
	@mkdir -p ${INT}/graph/viewalone
	@( cd ${INT}/graph/viewalone ; \
	  ${TANGLE} -t8 -R"viewalone/Makefile" ${BOOK} >Makefile )

@
<<*>>=
<<environment>>

all: ${DIRS} 
	@ echo 24 finished ${IN}

<<viewmandir>>
<<gdrawsdir>>
<<view3ddir>>
<<view2ddir>>
<<viewalonedir>>

clean: ${CLNS}
	@ echo 25 cleaning ${SRC}/graph

document: ${DIRS}
	@ echo 26 documenting graph

@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
