\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{no title}
\author{The Axiom Team}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{environment}
<<environment>>=

IN=	${SRC}/graph/view3d
MIDINT=	${INT}/graph/view3d
MIDOBJ= ${OBJ}/${SYS}/graph/view3d
OUT=	${MNT}/${SYS}/lib
DOC=    ${MNT}/${SYS}/doc/src/graph

LIB=    ${OBJ}/${SYS}/lib
GDRAW=  ${OBJ}/${SYS}/graph/gdraws

# local include files shared by graphics
LINC=	${SRC}/graph/include

# global include files shared by everyone 
GINC=	${SRC}/include

# bitmaps for cursors
BIT=	${SRC}/graph/include/purty

@
\section{buttons3d}
<<buttons3d.c (MIDINT from IN)>>=
${MIDINT}/buttons3d.c: ${IN}/buttons3d.c.pamphlet
	@ echo 1 ${MIDINT}/buttons3d.c from ${IN}/buttons3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/buttons3d.c.pamphlet >buttons3d.c )
	
<<buttons3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/buttons3d.o: ${HEADERS} ${IN}/cpanel.h ${MIDINT}/buttons3d.c
	@ echo 2 making ${MIDOBJ}/buttons3d.o from ${MIDINT}/buttons3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/buttons3d.c )

@
<<buttons3d.c.dvi (DOC from IN)>>=
${DOC}/buttons3d.c.dvi: ${IN}/buttons3d.c.pamphlet 
	@echo 3 making ${DOC}/buttons3d.c.dvi from ${IN}/buttons3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/buttons3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} buttons3d.c ; \
	rm -f ${DOC}/buttons3d.c.pamphlet ; \
	rm -f ${DOC}/buttons3d.c.tex ; \
	rm -f ${DOC}/buttons3d.c )

@
\section{closeview3d}
<<closeview3d.c (MIDINT from IN)>>=
${MIDINT}/closeview3d.c: ${IN}/closeview3d.c.pamphlet
	@ echo 4 ${MIDINT}/closeview3d.c from ${IN}/closeview3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/closeview3d.c.pamphlet >closeview3d.c )
	
@
<<closeview3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/closeview3d.o: ${HEADERS} ${MIDINT}/closeview3d.c
	@ echo 5 making ${MIDOBJ}/closeview3d.o from ${MIDINT}/closeview3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/closeview3d.c )

@
<<closeview3d.c.dvi (DOC from IN)>>=
${DOC}/closeview3d.c.dvi: ${IN}/closeview3d.c.pamphlet 
	@echo 6 making ${DOC}/closeview3d.c.dvi from ${IN}/closeview3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/closeview3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} closeview3d.c ; \
	rm -f ${DOC}/closeview3d.c.pamphlet ; \
	rm -f ${DOC}/closeview3d.c.tex ; \
	rm -f ${DOC}/closeview3d.c )

@
\section{component3d}
<<component3d.c (MIDINT from IN)>>=
${MIDINT}/component3d.c: ${IN}/component3d.c.pamphlet
	@ echo 7 ${MIDINT}/component3d.c from ${IN}/component3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/component3d.c.pamphlet >component3d.c )
	
@
<<component3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/component3d.o: ${HEADERS} ${MIDINT}/component3d.c
	@ echo 8 making ${MIDOBJ}/component3d.o from ${MIDINT}/component3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/component3d.c )

@
<<component3d.c.dvi (DOC from IN)>>=
${DOC}/component3d.c.dvi: ${IN}/component3d.c.pamphlet 
	@echo 9 making ${DOC}/component3d.c.dvi from ${IN}/component3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/component3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} component3d.c ; \
	rm -f ${DOC}/component3d.c.pamphlet ; \
	rm -f ${DOC}/component3d.c.tex ; \
	rm -f ${DOC}/component3d.c )

@
\section{control3d}
<<control3d.c (MIDINT from IN)>>=
${MIDINT}/control3d.c: ${IN}/control3d.c.pamphlet
	@ echo 10 ${MIDINT}/control3d.c from ${IN}/control3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/control3d.c.pamphlet >control3d.c )
	
@
<<control3d.o (MIDOBJ from MIDINT))>>=
${MIDOBJ}/control3d.o: ${HEADERS} ${IN}/cpanel.h  ${BIT}/mouse11.bitmap \
	 ${BIT}/mouse11.mask ${MIDINT}/control3d.c
	@ echo 11 making ${MIDOBJ}/control3d.o from ${MIDINT}/control3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/control3d.c )

@
<<control3d.c.dvi (DOC from IN)>>=
${DOC}/control3d.c.dvi: ${IN}/control3d.c.pamphlet 
	@echo 12 making ${DOC}/control3d.c.dvi from ${IN}/control3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/control3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} control3d.c ; \
	rm -f ${DOC}/control3d.c.pamphlet ; \
	rm -f ${DOC}/control3d.c.tex ; \
	rm -f ${DOC}/control3d.c )

@
\section{illuminate3d}
<<illuminate3d.c (MIDINT from IN)>>=
${MIDINT}/illuminate3d.c: ${IN}/illuminate3d.c.pamphlet
	@ echo 13 ${MIDINT}/illuminate3d.c from ${IN}/illuminate3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/illuminate3d.c.pamphlet >illuminate3d.c )
	
@
<<illuminate3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/illuminate3d.o: ${HEADERS} ${IN}/cpanel.h ${MIDINT}/illuminate3d.c
	@ echo 14 making ${MIDOBJ}/illuminate3d.o from ${MIDINT}/illuminate3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/illuminate3d.c )

@
<<illuminate3d.c.dvi (DOC from IN)>>=
${DOC}/illuminate3d.c.dvi: ${IN}/illuminate3d.c.pamphlet 
	@echo 15 making ${DOC}/illuminate3d.c.dvi from ${IN}/illuminate3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/illuminate3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} illuminate3d.c ; \
	rm -f ${DOC}/illuminate3d.c.pamphlet ; \
	rm -f ${DOC}/illuminate3d.c.tex ; \
	rm -f ${DOC}/illuminate3d.c )

@
\section{lightbut3d}
<<lightbut3d.c (MIDINT from IN)>>=
${MIDINT}/lightbut3d.c: ${IN}/lightbut3d.c.pamphlet
	@ echo 16 ${MIDINT}/lightbut3d.c from ${IN}/lightbut3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/lightbut3d.c.pamphlet >lightbut3d.c )
	
@
<<lightbut3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/lightbut3d.o: ${HEADERS} ${IN}/cpanel.h ${MIDINT}/lightbut3d.c
	@ echo 17 making ${MIDOBJ}/lightbut3d.o from ${MIDINT}/lightbut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/lightbut3d.c )

@
<<lightbut3d.c.dvi (DOC from IN)>>=
${DOC}/lightbut3d.c.dvi: ${IN}/lightbut3d.c.pamphlet 
	@echo 18 making ${DOC}/lightbut3d.c.dvi from ${IN}/lightbut3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/lightbut3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} lightbut3d.c ; \
	rm -f ${DOC}/lightbut3d.c.pamphlet ; \
	rm -f ${DOC}/lightbut3d.c.tex ; \
	rm -f ${DOC}/lightbut3d.c )

@
\section{lighting3d}
<<lighting3d.c (MIDINT from IN)>>=
${MIDINT}/lighting3d.c: ${IN}/lighting3d.c.pamphlet
	@ echo 19 ${MIDINT}/lighting3d.c from ${IN}/lighting3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/lighting3d.c.pamphlet >lighting3d.c )
	
@
<<lighting3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/lighting3d.o: ${HEADERS} ${IN}/draw.h ${IN}/cpanel.h \
	${BIT}/light11.bitmap  ${BIT}/light11.mask ${MIDINT}/lighting3d.c
	@ echo 20 making ${MIDOBJ}/lighting3d.o from ${MIDINT}/lighting3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/lighting3d.c )

@
<<lighting3d.c.dvi (DOC from IN)>>=
${DOC}/lighting3d.c.dvi: ${IN}/lighting3d.c.pamphlet 
	@echo 21 making ${DOC}/lighting3d.c.dvi from ${IN}/lighting3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/lighting3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} lighting3d.c ; \
	rm -f ${DOC}/lighting3d.c.pamphlet ; \
	rm -f ${DOC}/lighting3d.c.tex ; \
	rm -f ${DOC}/lighting3d.c )

@
\section{main3d}
<<main3d.c (MIDINT from IN)>>=
${MIDINT}/main3d.c: ${IN}/main3d.c.pamphlet
	@ echo 22 ${MIDINT}/main3d.c from ${IN}/main3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/main3d.c.pamphlet >main3d.c )
	
@
<<main3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/main3d.o: ${HEADERS} ${LINC}/xdefs.h ${IN}/cpanel.h ${IN}/process.h \
	 ${LINC}/mode.h ${MIDINT}/main3d.c
	@ echo 23 making ${MIDOBJ}/main3d.o from ${MIDINT}/main3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/main3d.c )

@
<<main3d.c.dvi (DOC from IN)>>=
${DOC}/main3d.c.dvi: ${IN}/main3d.c.pamphlet 
	@echo 24 making ${DOC}/main3d.c.dvi from ${IN}/main3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/main3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} main3d.c ; \
	rm -f ${DOC}/main3d.c.pamphlet ; \
	rm -f ${DOC}/main3d.c.tex ; \
	rm -f ${DOC}/main3d.c )

@
\section{mesh3d}
<<mesh3d.c (MIDINT from IN)>>=
${MIDINT}/mesh3d.c: ${IN}/mesh3d.c.pamphlet
	@ echo 25 ${MIDINT}/mesh3d.c from ${IN}/mesh3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/mesh3d.c.pamphlet >mesh3d.c )
	
@
<<mesh3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/mesh3d.o: ${HEADERS} ${MIDINT}/mesh3d.c
	@ echo 26 making ${MIDOBJ}/mesh3d.o from ${MIDINT}/mesh3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/mesh3d.c )

@
<<mesh3d.c.dvi (DOC from IN)>>=
${DOC}/mesh3d.c.dvi: ${IN}/mesh3d.c.pamphlet 
	@echo 27 making ${DOC}/mesh3d.c.dvi from ${IN}/mesh3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/mesh3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} mesh3d.c ; \
	rm -f ${DOC}/mesh3d.c.pamphlet ; \
	rm -f ${DOC}/mesh3d.c.tex ; \
	rm -f ${DOC}/mesh3d.c )

@
\section{msort3d}
<<msort3d.c (MIDINT from IN)>>=
${MIDINT}/msort3d.c: ${IN}/msort3d.c.pamphlet
	@ echo 28 ${MIDINT}/msort3d.c from ${IN}/msort3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/msort3d.c.pamphlet >msort3d.c )
	
@
<<msort3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/msort3d.o: ${HEADERS} ${MIDINT}/msort3d.c
	@ echo 29 making ${MIDOBJ}/msort3d.o from ${MIDINT}/msort3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/msort3d.c )

@
<<msort3d.c.dvi (DOC from IN)>>=
${DOC}/msort3d.c.dvi: ${IN}/msort3d.c.pamphlet 
	@echo 30 making ${DOC}/msort3d.c.dvi from ${IN}/msort3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/msort3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} msort3d.c ; \
	rm -f ${DOC}/msort3d.c.pamphlet ; \
	rm -f ${DOC}/msort3d.c.tex ; \
	rm -f ${DOC}/msort3d.c )

@
\section{pot3d}
<<pot3d.c (MIDINT from IN)>>=
${MIDINT}/pot3d.c: ${IN}/pot3d.c.pamphlet
	@ echo 31 ${MIDINT}/pot3d.c from ${IN}/pot3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/pot3d.c.pamphlet >pot3d.c )
	
@
<<pot3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/pot3d.o: ${HEADERS} ${MIDINT}/pot3d.c
	@ echo 32 making ${MIDOBJ}/pot3d.o from ${MIDINT}/pot3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/pot3d.c )

@
<<pot3d.c.dvi (DOC from IN)>>=
${DOC}/pot3d.c.dvi: ${IN}/pot3d.c.pamphlet 
	@echo 33 making ${DOC}/pot3d.c.dvi from ${IN}/pot3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/pot3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} pot3d.c ; \
	rm -f ${DOC}/pot3d.c.pamphlet ; \
	rm -f ${DOC}/pot3d.c.tex ; \
	rm -f ${DOC}/pot3d.c )

@
\section{process3d}
<<process3d.c (MIDINT from IN)>>=
${MIDINT}/process3d.c: ${IN}/process3d.c.pamphlet
	@ echo 34 ${MIDINT}/process3d.c from ${IN}/process3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/process3d.c.pamphlet >process3d.c )
	
@
<<process3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/process3d.o: ${HEADERS} ${IN}/cpanel.h ${IN}/process.h \
         ${IN}/volume.h ${LINC}/mode.h ${MIDINT}/process3d.c
	@ echo 35 making ${MIDOBJ}/process3d.o from ${MIDINT}/process3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/process3d.c )

@
<<process3d.c.dvi (DOC from IN)>>=
${DOC}/process3d.c.dvi: ${IN}/process3d.c.pamphlet 
	@echo 36 making ${DOC}/process3d.c.dvi from ${IN}/process3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/process3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} process3d.c ; \
	rm -f ${DOC}/process3d.c.pamphlet ; \
	rm -f ${DOC}/process3d.c.tex ; \
	rm -f ${DOC}/process3d.c )

@
\section{project3d}
<<project3d.c (MIDINT from IN)>>=
${MIDINT}/project3d.c: ${IN}/project3d.c.pamphlet
	@ echo 37 ${MIDINT}/project3d.c from ${IN}/project3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/project3d.c.pamphlet >project3d.c )
	
@
<<project3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/project3d.o: ${HEADERS} ${IN}/draw.h ${MIDINT}/project3d.c
	@ echo 38 making ${MIDOBJ}/project3d.o from ${MIDINT}/project3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/project3d.c )

@
<<project3d.c.dvi (DOC from IN)>>=
${DOC}/project3d.c.dvi: ${IN}/project3d.c.pamphlet 
	@echo 39 making ${DOC}/project3d.c.dvi from ${IN}/project3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/project3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} project3d.c ; \
	rm -f ${DOC}/project3d.c.pamphlet ; \
	rm -f ${DOC}/project3d.c.tex ; \
	rm -f ${DOC}/project3d.c )

@
\section{quitbut3d}
<<quitbut3d.c (MIDINT from IN)>>=
${MIDINT}/quitbut3d.c: ${IN}/quitbut3d.c.pamphlet
	@ echo 40 ${MIDINT}/quitbut3d.c from ${IN}/quitbut3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/quitbut3d.c.pamphlet >quitbut3d.c )
	
@
<<quitbut3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/quitbut3d.o: ${HEADERS} ${IN}/cpanel.h ${MIDINT}/quitbut3d.c
	@ echo 41 making ${MIDOBJ}/quitbut3d.o from ${MIDINT}/quitbut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/quitbut3d.c )

@
<<quitbut3d.c.dvi (DOC from IN)>>=
${DOC}/quitbut3d.c.dvi: ${IN}/quitbut3d.c.pamphlet 
	@echo 42 making ${DOC}/quitbut3d.c.dvi from ${IN}/quitbut3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/quitbut3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} quitbut3d.c ; \
	rm -f ${DOC}/quitbut3d.c.pamphlet ; \
	rm -f ${DOC}/quitbut3d.c.tex ; \
	rm -f ${DOC}/quitbut3d.c )

@
\section{quit3d}
<<quit3d.c (MIDINT from IN)>>=
${MIDINT}/quit3d.c: ${IN}/quit3d.c.pamphlet
	@ echo 43 ${MIDINT}/quit3d.c from ${IN}/quit3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/quit3d.c.pamphlet >quit3d.c )
	
@
<<quit3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/quit3d.o: ${HEADERS} ${IN}/cpanel.h ${MIDINT}/quit3d.c
	@ echo 44 making ${MIDOBJ}/quit3d.o from ${MIDINT}/quit3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/quit3d.c )

@
<<quit3d.c.dvi (DOC from IN)>>=
${DOC}/quit3d.c.dvi: ${IN}/quit3d.c.pamphlet 
	@echo 45 making ${DOC}/quit3d.c.dvi from ${IN}/quit3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/quit3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} quit3d.c ; \
	rm -f ${DOC}/quit3d.c.pamphlet ; \
	rm -f ${DOC}/quit3d.c.tex ; \
	rm -f ${DOC}/quit3d.c )

@
\section{save3d}
<<save3d.c (MIDINT from IN)>>=
${MIDINT}/save3d.c: ${IN}/save3d.c.pamphlet
	@ echo 46 ${MIDINT}/save3d.c from ${IN}/save3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/save3d.c.pamphlet >save3d.c )
	
@
<<save3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/save3d.o: ${HEADERS} ${IN}/cpanel.h ${MIDINT}/save3d.c
	@ echo 47 making ${MIDOBJ}/savebut3d.o from ${MIDINT}/savebut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/save3d.c )

@
<<save3d.c.dvi (DOC from IN)>>=
${DOC}/save3d.c.dvi: ${IN}/save3d.c.pamphlet 
	@echo 48 making ${DOC}/save3d.c.dvi from ${IN}/save3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/save3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} save3d.c ; \
	rm -f ${DOC}/save3d.c.pamphlet ; \
	rm -f ${DOC}/save3d.c.tex ; \
	rm -f ${DOC}/save3d.c )

@
\section{savebut3d}
<<savebut3d.c (MIDINT from IN)>>=
${MIDINT}/savebut3d.c: ${IN}/savebut3d.c.pamphlet
	@ echo 49 ${MIDINT}/savebut3d.c from ${IN}/savebut3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/savebut3d.c.pamphlet >savebut3d.c )
	
@
<<savebut3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/savebut3d.o: ${HEADERS} ${IN}/cpanel.h ${MIDINT}/savebut3d.c
	@ echo 50 making ${MIDOBJ}/savebutbut3d.o from ${MIDINT}/savebutbut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/savebut3d.c )

@
<<savebut3d.c.dvi (DOC from IN)>>=
${DOC}/savebut3d.c.dvi: ${IN}/savebut3d.c.pamphlet 
	@echo 51 making ${DOC}/savebut3d.c.dvi from ${IN}/savebut3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/savebut3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} savebut3d.c ; \
	rm -f ${DOC}/savebut3d.c.pamphlet ; \
	rm -f ${DOC}/savebut3d.c.tex ; \
	rm -f ${DOC}/savebut3d.c )

@
\section{smoothshade3d}
<<smoothshade3d.c (MIDINT from IN)>>=
${MIDINT}/smoothshade3d.c: ${IN}/smoothshade3d.c.pamphlet
	@ echo 52 ${MIDINT}/smoothshade3d.c from ${IN}/smoothshade3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/smoothshade3d.c.pamphlet >smoothshade3d.c )
	
@
<<smoothshade3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/smoothshade3d.o: ${HEADERS} ${GINC}/spadcolors.h ${IN}/draw.h \
           ${MIDINT}/smoothshade3d.c
	@ echo 53 making ${MIDOBJ}/smoothShadebut3d.o from ${MIDINT}/smoothShadebut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/smoothshade3d.c )

@
<<smoothshade3d.c.dvi (DOC from IN)>>=
${DOC}/smoothshade3d.c.dvi: ${IN}/smoothshade3d.c.pamphlet 
	@echo 54 making ${DOC}/smoothshade3d.c.dvi from ${IN}/smoothshade3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/smoothshade3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} smoothshade3d.c ; \
	rm -f ${DOC}/smoothshade3d.c.pamphlet ; \
	rm -f ${DOC}/smoothshade3d.c.tex ; \
	rm -f ${DOC}/smoothshade3d.c )

@
\section{spadaction3d}
<<spadaction3d.c (MIDINT from IN)>>=
${MIDINT}/spadaction3d.c: ${IN}/spadaction3d.c.pamphlet
	@ echo 55 ${MIDINT}/spadaction3d.c from ${IN}/spadaction3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/spadaction3d.c.pamphlet >spadaction3d.c )
	
@
<<spadaction3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/spadaction3d.o: ${HEADERS} ${LINC}/mode.h ${MIDINT}/spadaction3d.c
	@ echo 56 making ${MIDOBJ}/spadActionbut3d.o from ${MIDINT}/spadActionbut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/spadaction3d.c )

@
<<spadaction3d.c.dvi (DOC from IN)>>=
${DOC}/spadaction3d.c.dvi: ${IN}/spadaction3d.c.pamphlet 
	@echo 57 making ${DOC}/spadaction3d.c.dvi from ${IN}/spadaction3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/spadaction3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} spadaction3d.c ; \
	rm -f ${DOC}/spadaction3d.c.pamphlet ; \
	rm -f ${DOC}/spadaction3d.c.tex ; \
	rm -f ${DOC}/spadaction3d.c )

@
\section{stuff3d}
<<stuff3d.c (MIDINT from IN)>>=
${MIDINT}/stuff3d.c: ${IN}/stuff3d.c.pamphlet
	@ echo 58 ${MIDINT}/stuff3d.c from ${IN}/stuff3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/stuff3d.c.pamphlet >stuff3d.c )
	
@
<<stuff3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/stuff3d.o: ${HEADERS} ${MIDINT}/stuff3d.c
	@ echo 59 making ${MIDOBJ}/stuffbut3d.o from ${MIDINT}/stuffbut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/stuff3d.c )

@
<<stuff3d.c.dvi (DOC from IN)>>=
${DOC}/stuff3d.c.dvi: ${IN}/stuff3d.c.pamphlet 
	@echo 60 making ${DOC}/stuff3d.c.dvi from ${IN}/stuff3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/stuff3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} stuff3d.c ; \
	rm -f ${DOC}/stuff3d.c.pamphlet ; \
	rm -f ${DOC}/stuff3d.c.tex ; \
	rm -f ${DOC}/stuff3d.c )

@
\section{surface3d}
<<surface3d.c (MIDINT from IN)>>=
${MIDINT}/surface3d.c: ${IN}/surface3d.c.pamphlet
	@ echo 61 ${MIDINT}/surface3d.c from ${IN}/surface3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/surface3d.c.pamphlet >surface3d.c )
	
@
<<surface3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/surface3d.o: ${HEADERS} ${IN}/draw.h ${MIDINT}/surface3d.c
	@ echo 62 making ${MIDOBJ}/surfacebut3d.o from ${MIDINT}/surfacebut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/surface3d.c )

@
<<surface3d.c.dvi (DOC from IN)>>=
${DOC}/surface3d.c.dvi: ${IN}/surface3d.c.pamphlet 
	@echo 63 making ${DOC}/surface3d.c.dvi from ${IN}/surface3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/surface3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} surface3d.c ; \
	rm -f ${DOC}/surface3d.c.pamphlet ; \
	rm -f ${DOC}/surface3d.c.tex ; \
	rm -f ${DOC}/surface3d.c )

@
\section{transform3d}
<<transform3d.c (MIDINT from IN)>>=
${MIDINT}/transform3d.c: ${IN}/transform3d.c.pamphlet
	@ echo 64 ${MIDINT}/transform3d.c from ${IN}/transform3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/transform3d.c.pamphlet >transform3d.c )
	
@
<<transform3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/transform3d.o: ${HEADERS} ${MIDINT}/transform3d.c
	@ echo 65 making ${MIDOBJ}/transformbut3d.o from ${MIDINT}/transformbut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/transform3d.c )

@
<<transform3d.c.dvi (DOC from IN)>>=
${DOC}/transform3d.c.dvi: ${IN}/transform3d.c.pamphlet 
	@echo 66 making ${DOC}/transform3d.c.dvi from ${IN}/transform3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/transform3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} transform3d.c ; \
	rm -f ${DOC}/transform3d.c.pamphlet ; \
	rm -f ${DOC}/transform3d.c.tex ; \
	rm -f ${DOC}/transform3d.c )

@
\section{viewport3d}
<<viewport3d.c (MIDINT from IN)>>=
${MIDINT}/viewport3d.c: ${IN}/viewport3d.c.pamphlet
	@ echo 67 ${MIDINT}/viewport3d.c from ${IN}/viewport3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/viewport3d.c.pamphlet >viewport3d.c )
	
@
<<viewport3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/viewport3d.o: ${HEADERS} ${IN}/draw.h ${IN}/static.h ${IN}/volume.h \
	${BIT}/spadbitmap.bitmap  ${BIT}/spadmask.mask ${MIDINT}/viewport3d.c
	@ echo 68 making ${MIDOBJ}/viewportbut3d.o from ${MIDINT}/viewportbut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/viewport3d.c )

@
<<viewport3d.c.dvi (DOC from IN)>>=
${DOC}/viewport3d.c.dvi: ${IN}/viewport3d.c.pamphlet 
	@echo 69 making ${DOC}/viewport3d.c.dvi from ${IN}/viewport3d.c.pamphlet 
	(cd ${DOC} ; \
	cp ${IN}/viewport3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} viewport3d.c ; \
	rm -f ${DOC}/viewport3d.c.pamphlet ; \
	rm -f ${DOC}/viewport3d.c.tex ; \
	rm -f ${DOC}/viewport3d.c )

@
\section{volume3d}
<<volume3d.c (MIDINT from IN)>>=
${MIDINT}/volume3d.c: ${IN}/volume3d.c.pamphlet
	@ echo 70 ${MIDINT}/volume3d.c from ${IN}/volume3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/volume3d.c.pamphlet >volume3d.c )
	
@
<<volume3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/volume3d.o: ${HEADERS} ${IN}/cpanel.h ${IN}/process.h \
        ${IN}/volume.h ${BIT}/volume.bitmap ${BIT}/volume.mask \
        ${MIDINT}/volume3d.c
	@ echo 71 making ${MIDOBJ}/volumebut3d.o from ${MIDINT}/volumebut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/volume3d.c )

@
<<volume3d.c.dvi (DOC from IN)>>=
${DOC}/volume3d.c.dvi: ${IN}/volume3d.c.pamphlet 
	@echo 72 making ${DOC}/volume3d.c.dvi from ${IN}/volume3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/volume3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} volume3d.c ; \
	rm -f ${DOC}/volume3d.c.pamphlet ; \
	rm -f ${DOC}/volume3d.c.tex ; \
	rm -f ${DOC}/volume3d.c )

@
\section{write3d}
<<write3d.c (MIDINT from IN)>>=
${MIDINT}/write3d.c: ${IN}/write3d.c.pamphlet
	@ echo 73 ${MIDINT}/write3d.c from ${IN}/write3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/write3d.c.pamphlet >write3d.c )
	
@
<<write3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/write3d.o: ${HEADERS} ${LINC}/write.h ${MIDINT}/write3d.c
	@ echo 74 making ${MIDOBJ}/writebut3d.o from ${MIDINT}/writebut3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/write3d.c )

@
<<write3d.c.dvi (DOC from IN)>>=
${DOC}/write3d.c.dvi: ${IN}/write3d.c.pamphlet 
	@echo 75 making ${DOC}/write3d.c.dvi from ${IN}/write3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/write3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} write3d.c ; \
	rm -f ${DOC}/write3d.c.pamphlet ; \
	rm -f ${DOC}/write3d.c.tex ; \
	rm -f ${DOC}/write3d.c )

@
\section{view3d}
<<view3d>>=
${OUT}/view3d: ${OBJS} ${GDRAW_OBJS} ${LIB}/bsdsignal.o ${LIB}/util.o \
               ${LIB}/xshade.o ${LIB}/halloc.o ${LIB}/pixmap.o \
               ${LIB}/spadcolors.o ${LIB}/xspadfill.o ${LIB}/xdither.o 
	@ echo 76 linking ${OUT}/view3d $(LDFLAGS)
	@ ${CC} ${OBJS} ${GDRAW_OBJS} ${LIB}/bsdsignal.o \
	${LIB}/util.o  ${LIB}/xshade.o ${LIB}/halloc.o \
	${LIB}/pixmap.o ${LIB}/spadcolors.o ${LIB}/xspadfill.o \
	${LIB}/xdither.o -o ${OUT}/view3d $(LDFLAGS) -lXpm

@
<<*>>=
<<environment>>

DOCFILES= ${DOC}/buttons3d.c.dvi    ${DOC}/closeview3d.c.dvi \
          ${DOC}/component3d.c.dvi  ${DOC}/control3d.c.dvi \
          ${DOC}/illuminate3d.c.dvi ${DOC}/lightbut3d.c.dvi \
          ${DOC}/lighting3d.c.dvi   ${DOC}/main3d.c.dvi \
          ${DOC}/mesh3d.c.dvi       ${DOC}/msort3d.c.dvi \
          ${DOC}/pot3d.c.dvi        ${DOC}/process3d.c.dvi \
          ${DOC}/project3d.c.dvi    ${DOC}/quitbut3d.c.dvi \
          ${DOC}/quit3d.c.dvi       ${DOC}/save3d.c.dvi \
          ${DOC}/savebut3d.c.dvi    ${DOC}/smoothshade3d.c.dvi \
          ${DOC}/spadaction3d.c.dvi ${DOC}/stuff3d.c.dvi \
          ${DOC}/surface3d.c.dvi    ${DOC}/transform3d.c.dvi \
          ${DOC}/viewport3d.c.dvi   ${DOC}/volume3d.c.dvi \
          ${DOC}/write3d.c.dvi

CFLAGS  = ${CCF} -I${LINC} -I${GINC} -I${IN}
LDFLAGS =  ${LDF} ${STATIC} -lX11 -lm 

OBJS = \
 ${MIDOBJ}/buttons3d.o    ${MIDOBJ}/closeview3d.o  ${MIDOBJ}/component3d.o   \
 ${MIDOBJ}/control3d.o    ${MIDOBJ}/illuminate3d.o ${MIDOBJ}/lightbut3d.o    \
 ${MIDOBJ}/lighting3d.o   ${MIDOBJ}/main3d.o       ${MIDOBJ}/mesh3d.o        \
 ${MIDOBJ}/msort3d.o      ${MIDOBJ}/pot3d.o        ${MIDOBJ}/process3d.o     \
 ${MIDOBJ}/project3d.o    ${MIDOBJ}/quitbut3d.o    ${MIDOBJ}/quit3d.o        \
 ${MIDOBJ}/save3d.o       ${MIDOBJ}/savebut3d.o    ${MIDOBJ}/smoothshade3d.o \
 ${MIDOBJ}/spadaction3d.o ${MIDOBJ}/stuff3d.o      ${MIDOBJ}/surface3d.o     \
 ${MIDOBJ}/transform3d.o  ${MIDOBJ}/viewport3d.o   ${MIDOBJ}/volume3d.o      \
 ${MIDOBJ}/write3d.o

GDRAW_OBJS  = ${GDRAW}/gfun.o ${OBJ}/${SYS}/lib/hash.o

HEADERS = ${IN}/header.h ${IN}/globals.h \
	${LINC}/component.h ${LINC}/view3d.h ${LINC}/tube.h \
	${LINC}/actions.h ${LINC}/viewcommand.h \
	${GINC}/view.h ${LINC}/g.h

all: ${OBJS} ${GDRAW_OBJS} ${OUT}/view3d ${DOCFILES}
	@echo 78 finished ${IN}

<<buttons3d.c (MIDINT from IN)>>
<<buttons3d.o (MIDOBJ from MIDINT)>>
<<buttons3d.c.dvi (DOC from IN)>>

<<closeview3d.c (MIDINT from IN)>>
<<closeview3d.o (MIDOBJ from MIDINT)>>
<<closeview3d.c.dvi (DOC from IN)>>

<<component3d.c (MIDINT from IN)>>
<<component3d.o (MIDOBJ from MIDINT)>>
<<component3d.c.dvi (DOC from IN)>>

<<control3d.c (MIDINT from IN)>>
<<control3d.o (MIDOBJ from MIDINT))>>
<<control3d.c.dvi (DOC from IN)>>

<<illuminate3d.c (MIDINT from IN)>>
<<illuminate3d.o (MIDOBJ from MIDINT)>>
<<illuminate3d.c.dvi (DOC from IN)>>

<<lightbut3d.c (MIDINT from IN)>>
<<lightbut3d.o (MIDOBJ from MIDINT)>>
<<lightbut3d.c.dvi (DOC from IN)>>

<<lighting3d.c (MIDINT from IN)>>
<<lighting3d.o (MIDOBJ from MIDINT)>>
<<lighting3d.c.dvi (DOC from IN)>>

<<main3d.c (MIDINT from IN)>>
<<main3d.o (MIDOBJ from MIDINT)>>
<<main3d.c.dvi (DOC from IN)>>

<<mesh3d.c (MIDINT from IN)>>
<<mesh3d.o (MIDOBJ from MIDINT)>>
<<mesh3d.c.dvi (DOC from IN)>>

<<msort3d.c (MIDINT from IN)>>
<<msort3d.o (MIDOBJ from MIDINT)>>
<<msort3d.c.dvi (DOC from IN)>>

<<pot3d.c (MIDINT from IN)>>
<<pot3d.o (MIDOBJ from MIDINT)>>
<<pot3d.c.dvi (DOC from IN)>>

<<process3d.c (MIDINT from IN)>>
<<process3d.o (MIDOBJ from MIDINT)>>
<<process3d.c.dvi (DOC from IN)>>

<<project3d.c (MIDINT from IN)>>
<<project3d.o (MIDOBJ from MIDINT)>>
<<project3d.c.dvi (DOC from IN)>>

<<quitbut3d.c (MIDINT from IN)>>
<<quitbut3d.o (MIDOBJ from MIDINT)>>
<<quitbut3d.c.dvi (DOC from IN)>>

<<quit3d.c (MIDINT from IN)>>
<<quit3d.o (MIDOBJ from MIDINT)>>
<<quit3d.c.dvi (DOC from IN)>>

<<save3d.c (MIDINT from IN)>>
<<save3d.o (MIDOBJ from MIDINT)>>
<<save3d.c.dvi (DOC from IN)>>

<<savebut3d.c (MIDINT from IN)>>
<<savebut3d.o (MIDOBJ from MIDINT)>>
<<savebut3d.c.dvi (DOC from IN)>>

<<smoothshade3d.c (MIDINT from IN)>>
<<smoothshade3d.o (MIDOBJ from MIDINT)>>
<<smoothshade3d.c.dvi (DOC from IN)>>

<<spadaction3d.c (MIDINT from IN)>>
<<spadaction3d.o (MIDOBJ from MIDINT)>>
<<spadaction3d.c.dvi (DOC from IN)>>

<<stuff3d.c (MIDINT from IN)>>
<<stuff3d.o (MIDOBJ from MIDINT)>>
<<stuff3d.c.dvi (DOC from IN)>>

<<surface3d.c (MIDINT from IN)>>
<<surface3d.o (MIDOBJ from MIDINT)>>
<<surface3d.c.dvi (DOC from IN)>>

<<transform3d.c (MIDINT from IN)>>
<<transform3d.o (MIDOBJ from MIDINT)>>
<<transform3d.c.dvi (DOC from IN)>>

<<viewport3d.c (MIDINT from IN)>>
<<viewport3d.o (MIDOBJ from MIDINT)>>
<<viewport3d.c.dvi (DOC from IN)>>

<<volume3d.c (MIDINT from IN)>>
<<volume3d.o (MIDOBJ from MIDINT)>>
<<volume3d.c.dvi (DOC from IN)>>

<<write3d.c (MIDINT from IN)>>
<<write3d.o (MIDOBJ from MIDINT)>>
<<write3d.c.dvi (DOC from IN)>>

<<view3d>>

clean: 
	@ echo 79 cleaning ${IN}/view3d

document: 
	@ echo 80 documenting ${IN}/view3d

@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
