(make-package "BOOT"  :USE '("LISP"))

(make-package "BOOTTRAN" :USE '("LISP"))

(IN-PACKAGE "BOOT") 

(PROCLAIM (QUOTE (FTYPE (FUNCTION (T) (*)) 
  BOOTTRAN::STRINGIMAGE))) 

(PROCLAIM (QUOTE (FTYPE (FUNCTION (T *) (VALUES T T)) 
  BOOTTRAN::|shoeread-line|)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T T) FIXNUM) 
  BOOTTRAN::QENUM)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T T T) *) 
  BOOTTRAN::|shoeGeneralFC|)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T T T T) T) 
  BOOTTRAN::STRPOSL 
  BOOTTRAN::|shoeLAM| 
  BOOTTRAN::|shoeClLines| 
  BOOTTRAN::|bfMDef| 
  BOOTTRAN::|shoeClCLines| 
  BOOTTRAN::|bfOpReduce| 
  BOOTTRAN::|bfSTEP| 
  BOOTTRAN::|bfDef| 
  BOOTTRAN::STRPOS 
  BOOTTRAN::|shoeConstructToken| 
  BOOTTRAN::|shoePackageStartsAt|)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T T T) T) 
  BOOTTRAN::|bfIf| 
  BOOTTRAN::SUBSTRING 
  BOOTTRAN::|shoeElse1| 
  BOOTTRAN::|shoeFindName2| 
  BOOTTRAN::|bfForInBy| 
  BOOTTRAN::|bfMDefinition2| 
  BOOTTRAN::|shoeSubStringMatch| 
  BOOTTRAN::|shoeFindLines| 
  BOOTTRAN::|bpListofFun| 
  BOOTTRAN::|shoeElse| 
  BOOTTRAN::|shoeLeafFloat| 
  BOOTTRAN::|shoeThen| 
  BOOTTRAN::|bpList| 
  BOOTTRAN::|bfCompHash| 
  BOOTTRAN::|bfCI| 
  BOOTTRAN::|bfListReduce| 
  BOOTTRAN::|shoeThen1| 
  BOOTTRAN::|bfLp2| 
  BOOTTRAN::|bfFor| 
  BOOTTRAN::|bpListof| 
  BOOTTRAN::|bfPosn| 
  BOOTTRAN::|shoePileForests| 
  BOOTTRAN::|bfISApplication| 
  BOOTTRAN::|bfSetelt| 
  BOOTTRAN::|defSETELT| 
  BOOTTRAN::|shoeTokConstruct| 
  BOOTTRAN::|bootOutLines| 
  BOOTTRAN::BVEC-SETELT 
  BOOTTRAN::|bpAndOr| 
  BOOTTRAN::|bfForTree| 
  BOOTTRAN::HPUT 
  BOOTTRAN::|bfDefinition2| 
  BOOTTRAN::|stripm| 
  BOOTTRAN::VEC-SETELT 
  BOOTTRAN::|shoeFindName| 
  BOOTTRAN::|bfInfApplication|)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION NIL T) 
  BOOTTRAN::|shoeNegComment| 
  BOOTTRAN::|bpSeg| 
  BOOTTRAN::|bpIs| 
  BOOTTRAN::|shoeStartsNegComment| 
  BOOTTRAN::|bpDef| 
  BOOTTRAN::|shoeComment| 
  BOOTTRAN::|shoeStartsComment| 
  BOOTTRAN::|bpPrimary| 
  BOOTTRAN::|bpPrimary1| 
  BOOTTRAN::|bpPileItems| 
  BOOTTRAN::|bpCrossBackSet| 
  BOOTTRAN::|bpDefinition| 
  BOOTTRAN::|bpExpt| 
  BOOTTRAN::|bpExit| 
  BOOTTRAN::|bpState| 
  BOOTTRAN::|bpPatternColon| 
  BOOTTRAN::|bpPop3| 
  BOOTTRAN::|bpDefinitionPileItems| 
  BOOTTRAN::|bpSexpKey| 
  BOOTTRAN::|bpExceptions| 
  BOOTTRAN::|bpSemiBackSet| 
  BOOTTRAN::|bpIterator| 
  BOOTTRAN::|shoeEsc| 
  BOOTTRAN::|bpUntil| 
  BOOTTRAN::|bpWhile| 
  BOOTTRAN::|bpForIn| 
  BOOTTRAN::|bpDConstruct| 
  BOOTTRAN::|shoeInteger| 
  BOOTTRAN::|shoeS| 
  BOOTTRAN::|bpReduceOperator| 
  BOOTTRAN::|bpAssignment| 
  BOOTTRAN::|bpAssign| 
  BOOTTRAN::|bpAssignVariable| 
  BOOTTRAN::|bpNextToken| 
  BOOTTRAN::BOOTLOOP 
  BOOTTRAN::|bpFirstToken| 
  BOOTTRAN::BOOTPO 
  BOOTTRAN::|bpStatement| 
  BOOTTRAN::|bpString| 
  BOOTTRAN::|bpInfixOperator| 
  BOOTTRAN::|bpAnyId| 
  BOOTTRAN::|bpSelector| 
  BOOTTRAN::|bpAssignLHS| 
  BOOTTRAN::|bpLoop| 
  BOOTTRAN::|bpLogical| 
  BOOTTRAN::|bfGenSymbol| 
  BOOTTRAN::|bpRegularList| 
  BOOTTRAN::|bpCaseItem| 
  BOOTTRAN::|bpPop2| 
  BOOTTRAN::|bpExpression| 
  BOOTTRAN::|bpWhere| 
  BOOTTRAN::|bpPattern| 
  BOOTTRAN::|bpTerm| 
  BOOTTRAN::|bpPatternList| 
  BOOTTRAN::|bpTypeList| 
  BOOTTRAN::|bpPatternTail| 
  BOOTTRAN::|bpRegularPatternItemL| 
  BOOTTRAN::|bpPiledCaseItems| 
  BOOTTRAN::|bpArith| 
  BOOTTRAN::|bpStruct| 
  BOOTTRAN::|bpChecknull| 
  BOOTTRAN::|bpName| 
  BOOTTRAN::|bpCase| 
  BOOTTRAN::|bpRegularBVItemL| 
  BOOTTRAN::|bpTypeItemList| 
  BOOTTRAN::|bpRegularBVItem| 
  BOOTTRAN::|bpCommaBackSet| 
  BOOTTRAN::|bpIdList| 
  BOOTTRAN::|bpTagged| 
  BOOTTRAN::|bpMinus| 
  BOOTTRAN::|bpBoundVariablelist| 
  BOOTTRAN::|bpCaseItemList| 
  BOOTTRAN::|bpPileTrap| 
  BOOTTRAN::|bpRegularPatternItem| 
  BOOTTRAN::|shoePunCons| 
  BOOTTRAN::|bpDot| 
  BOOTTRAN::|bpTimes| 
  BOOTTRAN::|bpReduce| 
  BOOTTRAN::|bpPatternL| 
  BOOTTRAN::|bpSuchThat| 
  BOOTTRAN::|bpDConstruction| 
  BOOTTRAN::|bpColonName| 
  BOOTTRAN::|shoeKeyTableCons| 
  BOOTTRAN::|bpBVString| 
  BOOTTRAN::|bpRecoverTrap| 
  BOOTTRAN::|bpReturn| 
  BOOTTRAN::|bpConstruction| 
  BOOTTRAN::|bpAnd| 
  BOOTTRAN::|bpPDefinitionItems| 
  BOOTTRAN::|bpIteratorTail| 
  BOOTTRAN::|bpVariable| 
  BOOTTRAN::|bpIterators| 
  BOOTTRAN::|bpBDefinitionPileItems| 
  BOOTTRAN::|bpSemiColon| 
  BOOTTRAN::|bpThetaName| 
  BOOTTRAN::|bpNext| 
  BOOTTRAN::|bpPushId| 
  BOOTTRAN::|bpCancel| 
  BOOTTRAN::|bpDDef| 
  BOOTTRAN::|shoeDictCons| 
  BOOTTRAN::|bpDefTail| 
  BOOTTRAN::|bpIteratorList| 
  BOOTTRAN::|bpDefinitionItem| 
  BOOTTRAN::|bpSexp1| 
  BOOTTRAN::|bpGeneralErrorHere| 
  BOOTTRAN::|bpSexp| 
  BOOTTRAN::|bpOperator| 
  BOOTTRAN::|shoeToken| 
  BOOTTRAN::|bpOutItem| 
  BOOTTRAN::|bpFirstTok| 
  BOOTTRAN::|bpBacksetElse| 
  BOOTTRAN::|shoeError| 
  BOOTTRAN::|bpBPileDefinition| 
  BOOTTRAN::|bpMdef| 
  BOOTTRAN::|shoeEscape| 
  BOOTTRAN::|bpMDefTail| 
  BOOTTRAN::|bpPDefinition| 
  BOOTTRAN::|shoeNumber| 
  BOOTTRAN::|bpStoreName| 
  BOOTTRAN::|bpConstruct| 
  BOOTTRAN::|bpEqual| 
  BOOTTRAN::|shoeString| 
  BOOTTRAN::|bfDot| 
  BOOTTRAN::|shoeSpace| 
  BOOTTRAN::|bpConstTok| 
  BOOTTRAN::|bpSemiColonDefinition| 
  BOOTTRAN::|bpApplication| 
  BOOTTRAN::|bpPop1| 
  BOOTTRAN::|shoePunct| 
  BOOTTRAN::|bpTrap| 
  BOOTTRAN::|bpPrefixOperator| 
  BOOTTRAN::|bpComma| 
  BOOTTRAN::|bpCompare| 
  BOOTTRAN::|shoeLispEscape|)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (*) T) 
  BOOTTRAN::|bAddLineNumber1| 
  BOOTTRAN::CONCAT 
  BOOTTRAN::|bMap1| 
  BOOTTRAN::|bAppend1| 
  BOOTTRAN::|bIgen1| 
  BOOTTRAN::|bRgen1| 
  COMPILER::CMPNOTE)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T) *) 
  BOOTTRAN::|shoePCompile| 
  BOOTTRAN::|shoeCompile| 
  BOOTTRAN::STTOMC 
  BOOTTRAN::|shoeInputFile| 
  BOOTTRAN::|shoeCOMPILE-FILE| 
  BOOTTRAN::EVAL-BOOT-FILE 
  BOOTTRAN::BOOT 
  BOOTTRAN::COMPILE-BOOT-FILE)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T) STRING) 
  BOOTTRAN::MAKE-CVEC)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T) T) 
  BOOTTRAN::|bpInfKey| 
  BOOTTRAN::|shoePlainLine?| 
  BOOTTRAN::|shoeInclude?| 
  BOOTTRAN::|shoeReport| 
  BOOTTRAN::|bfSegment1| 
  BOOTTRAN::|shoeFileInput| 
  BOOTTRAN::|bfCompDef| 
  BOOTTRAN::|shoeDefUse| 
  BOOTTRAN::BOCLAM 
  BOOTTRAN::|shoeLeafLisp| 
  BOOTTRAN::|bfReadLisp| 
  BOOTTRAN::|shoeLineFileInput| 
  BOOTTRAN::|shoeLeafLine| 
  BOOTTRAN::|bpAnyNo| 
  BOOTTRAN::|dqToList| 
  BOOTTRAN::|bfSequence| 
  BOOTTRAN::|shoeLeafNegComment| 
  BOOTTRAN::DUMMY1 
  BOOTTRAN::|bfTupleIf| 
  BOOTTRAN::|shoeLineToks| 
  BOOTTRAN::|bpRestore| 
  BOOTTRAN::|shoeKeyTr| 
  BOOTTRAN::|bpEqPeek| 
  BOOTTRAN::|lineCharacter| 
  BOOTTRAN::|shoeLeafKey| 
  BOOTTRAN::|shoeIncludeFunction?| 
  BOOTTRAN::|shoeSpaces| 
  BOOTTRAN::|shoePossFloat| 
  BOOTTRAN::|lineString| 
  BOOTTRAN::|shoeCloser| 
  BOOTTRAN::|shoePackage?| 
  BOOTTRAN::|lineNo| 
  BOOTTRAN::|shoeKeyWord| 
  BOOTTRAN::|shoeFin?| 
  BOOTTRAN::|shoeTransform2| 
  BOOTTRAN::|shoeFunctionFileInput| 
  BOOTTRAN::|bfDefSequence| 
  BOOTTRAN::|shoeInclude| 
  BOOTTRAN::|bfColon| 
  BOOTTRAN::|shoeItem| 
  BOOTTRAN::|bIgen| 
  BOOTTRAN::|shoeW| 
  BOOTTRAN::|bfBeginsDollar| 
  BOOTTRAN::|shoeTreeConstruct| 
  BOOTTRAN::|shoeLeafSpaces| 
  BOOTTRAN::|shoeLeafError| 
  BOOTTRAN::|shoePrefixLisp| 
  BOOTTRAN::|bpBracket| 
  BOOTTRAN::|shoeInteger1| 
  BOOTTRAN::|shoeIncludeLisp?| 
  BOOTTRAN::|bfListOf| 
  BOOTTRAN::BOOTTOMC 
  BOOTTRAN::|bPremStreamNil| 
  BOOTTRAN::BOOTTOCLC 
  BOOTTRAN::|shoeLeafId| 
  BOOTTRAN::|shoeConsole| 
  BOOTTRAN::|shoeLeafComment| 
  BOOTTRAN::|bPremStreamNull| 
  BOOTTRAN::|bfSuchthat| 
  BOOTTRAN::PSTOUT 
  BOOTTRAN::|bStreamNull| 
  BOOTTRAN::|bfSep| 
  BOOTTRAN::|shoeCompileTrees| 
  BOOTTRAN::|shoeInclude1| 
  BOOTTRAN::STOUT 
  BOOTTRAN::SIZE 
  BOOTTRAN::|shoeIdChar| 
  BOOTTRAN::|bfINON| 
  BOOTTRAN::|shoeSimpleLine| 
  BOOTTRAN::|bpParenTrap| 
  BOOTTRAN::DEFUSE 
  BOOTTRAN::DUMMY2 
  BOOTTRAN::|shoeIf?| 
  BOOTTRAN::|defQuoteId| 
  BOOTTRAN::|shoeEndIf?| 
  BOOTTRAN::|shoeSay?| 
  BOOTTRAN::|bpEqKeyNextTok| 
  BOOTTRAN::|shoePLACEP| 
  BOOTTRAN::|shoePrefixLine| 
  BOOTTRAN::BOOTCLAM 
  BOOTTRAN::|shoeIncludeLines?| 
  BOOTTRAN::|bfSmintable| 
  BOOTTRAN::|bfAND| 
  BOOTTRAN::|bfSuffixDot| 
  BOOTTRAN::XREF 
  BOOTTRAN::|bRgen| 
  BOOTTRAN::|shoeCLOSE| 
  BOOTTRAN::|bfOR| 
  BOOTTRAN::|bfNOT| 
  BOOTTRAN::|shoeFnFileName| 
  BOOTTRAN::|bpBracketConstruct| 
  BOOTTRAN::|shoeFileName| 
  BOOTTRAN::|last| 
  BOOTTRAN::|shoeBiteOff| 
  BOOTTRAN::|bfLoop1| 
  BOOTTRAN::|bfDs| 
  BOOTTRAN::|shoeLine?| 
  BOOTTRAN::|shoeElseIf?| 
  BOOTTRAN::|bfCreateDef| 
  BOOTTRAN::IDENTP 
  BOOTTRAN::|shoeLisp?| 
  BOOTTRAN::|shoeElse?| 
  BOOTTRAN::|bpCompMissing| 
  BOOTTRAN::|char| 
  BOOTTRAN::|bfTuple| 
  PNAME 
  BOOTTRAN::|bpOneOrMore| 
  BOOTTRAN::|shoeLastTokPosn| 
  BOOTTRAN::|shoeTokPosn| 
  BOOTTRAN::|bfTupleP| 
  BOOTTRAN::|bpConditional| 
  BOOTTRAN::|bpEqKey| 
  BOOTTRAN::|bfMakeCons| 
  BOOTTRAN::BOOTTOCL 
  BOOTTRAN::|shoePileColumn| 
  BOOTTRAN::|shoeFluids| 
  BOOTTRAN::|bpPileBracketed| 
  BOOTTRAN::|shoeRemovebootIfNec| 
  BOOTTRAN::|shoeAddbootIfNec| 
  BOOTTRAN::|shoeATOMs| 
  BOOTTRAN::|shoeConsoleItem| 
  DOUBLE 
  BOOTTRAN::|shoePileInsert| 
  BOOTTRAN::|shoeCompTran1| 
  BOOTTRAN::|shoeParseTrees| 
  BOOTTRAN::|shoeTokType| 
  BOOTTRAN::|shoeDQlines| 
  BOOTTRAN::|shoeConsoleLines| 
  BOOTTRAN::|shoeSeparatePiles| 
  BOOTTRAN::|compFluid| 
  BOOTTRAN::|bpMissing| 
  BOOTTRAN::|shoeOutParse| 
  BOOTTRAN::|dqConcat| 
  BOOTTRAN::|bfReName| 
  BOOTTRAN::|bfNameOnly| 
  BOOTTRAN::|bfDef1| 
  BOOTTRAN::|bpBrackTrap| 
  BOOTTRAN::|shoeAddComment| 
  BOOTTRAN::|dqUnit| 
  BOOTTRAN::|shoeComps| 
  BOOTTRAN::|bfBracket| 
  BOOTTRAN::|bpParenthesized| 
  BOOTTRAN::|shoeTransformStream| 
  BOOTTRAN::|shoeEnPile| 
  BOOTTRAN::|shoeComp| 
  BOOTTRAN::|shoeFirstTokPosn| 
  BOOTTRAN::|bfGargl| 
  BOOTTRAN::|bpListAndRecover| 
  BOOTTRAN::|shoeNotFound| 
  BOOTTRAN::|bpTuple| 
  BOOTTRAN::|bfAppend| 
  BOOTTRAN::|shoeTokPart| 
  BOOTTRAN::|bfMKPROGN| 
  BOOTTRAN::|compFluidize| 
  BOOTTRAN::|bfWhile| 
  BOOTTRAN::PSTTOMC 
  BOOTTRAN::|shoePileCforest| 
  BOOTTRAN::|bfFlattenSeq| 
  BOOTTRAN::|shoePCompileTrees| 
  BOOTTRAN::|shoeTransformString| 
  BOOTTRAN::|bfCross| 
  BOOTTRAN::|bfPile| 
  BOOTTRAN::|shoeXReport| 
  BOOTTRAN::|shoeStartsId| 
  BOOTTRAN::|bpMoveTo| 
  BOOTTRAN::|defSheepAndGoatsList| 
  BOOTTRAN::SSORT 
  BOOTTRAN::MAKE-BVEC 
  BOOTTRAN::|defSheepAndGoats| 
  BOOTTRAN::HKEYS 
  BOOTTRAN::|bfDTuple| 
  BOOTTRAN::|shoeConsoleTrees| 
  BOOTTRAN::|shoeTransformToConsole| 
  BOOTTRAN::|bfUntil| 
  BOOTTRAN::BO 
  BOOTTRAN::MAKE-HASHTABLE 
  BOOTTRAN::|shoeLeafString| 
  BOOTTRAN::|bfReturnNoName| 
  BOOTTRAN::|bfTupleConstruct| 
  BOOTTRAN::|defSeparate| 
  BOOTTRAN::|shoeNextLine| 
  BOOTTRAN::|unfluidlist| 
  BOOTTRAN::|shoeLeafLispExp| 
  BOOTTRAN::|defusebuiltin| 
  BOOTTRAN::|shoeKeyWordP| 
  BOOTTRAN::|shoeIntValue| 
  BOOTTRAN::|shoeOrdToNum| 
  BOOTTRAN::|bfConstruct| 
  BOOTTRAN::|bStreamPackageNull| 
  BOOTTRAN::|shoeLeafInteger| 
  BOOTTRAN::|shoeTransform| 
  BOOTTRAN::|bpAddTokens| 
  BOOTTRAN::STEVAL 
  BOOTTRAN::|bpSpecificErrorHere| 
  BOOTTRAN::|bfIterators| 
  BOOTTRAN::MAKE-VEC 
  BOOTTRAN::|bpIndentParenthesized| 
  BOOTTRAN::|bpInfGeneric| 
  BOOTTRAN::|shoeDigit| 
  BOOTTRAN::|bpPush| 
  BOOTTRAN::|bfEqual| 
  BOOTTRAN::|shoeCompTran| 
  BOOTTRAN::|bfSymbol| 
  BOOTTRAN::|shoeEVALANDFILEACTQ| 
  BOOTTRAN::|shoeWord| 
  BOOTTRAN::|shoeLispFileInput| 
  BOOTTRAN::|bpElse| 
  BOOTTRAN::|shoePunctuation| 
  BOOTTRAN::|shoeLineSyntaxError| 
  BOOTTRAN::|shoeEval?|)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T *) STRING)
  BOOTTRAN::MAKE-FULL-CVEC)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T *) T)
  BOOTTRAN::SHOEPRETTYPRIN1 
  BOOTTRAN::REALLYPRETTYPRINT 
  BOOTTRAN::SHOEPRETTYPRIN0 
  BOOTTRAN::SHOENOTPRETTYPRINT)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T T) *) 
  BOOTTRAN::FBO 
  BOOTTRAN::FEV)))
 
(PROCLAIM (QUOTE (FTYPE (FUNCTION (T T) T) 
  BOOTTRAN::|bootOut| 
  BOOTTRAN::|bfSegment2| 
  BOOTTRAN::|bfWhere| 
  BOOTTRAN::|bFileNext| 
  BOOTTRAN::|shoeLispToken| 
  BOOTTRAN::|bfApplication| 
  BOOTTRAN::|bpRightAssoc| 
  BOOTTRAN::|bNext| 
  BOOTTRAN::|bpIgnoredFromTo| 
  BOOTTRAN::|bfForin| 
  BOOTTRAN::|shoePrefix?| 
  BOOTTRAN::|shoeMatch| 
  BOOTTRAN::BOOTTOCLLINES 
  BOOTTRAN::|bAddLineNumber| 
  BOOTTRAN::|shoeIdEnd| 
  BOOTTRAN::|bFileNext1| 
  BOOTTRAN::|bfLET1| 
  BOOTTRAN::|shoeFileLines| 
  BOOTTRAN::|SoftShoeError| 
  BOOTTRAN::|bfLetForm| 
  BOOTTRAN::|bNext1| 
  BOOTTRAN::|bfLET2| 
  BOOTTRAN::|shoeMc| 
  BOOTTRAN::|shoeExponent| 
  BOOTTRAN::|bfCONTAINED| 
  BOOTTRAN::|bDelay| 
  BOOTTRAN::|bfReduce| 
  BOOTTRAN::|bfDrop| 
  BOOTTRAN::BOOTTOCLCLINES 
  BOOTTRAN::|bfReduceCollect| 
  BOOTTRAN::|bfIS| 
  BOOTTRAN::|shoeReadLispString| 
  BOOTTRAN::|bfIS1| 
  BOOTTRAN::|bfAssign| 
  BOOTTRAN::|bfInsertLet| 
  BOOTTRAN::|bAppend| 
  BOOTTRAN::|bfInsertLet1| 
  BOOTTRAN::|bfIN| 
  BOOTTRAN::|shoeDfu| 
  BOOTTRAN::|bfON| 
  BOOTTRAN::|bfTake| 
  BOOTTRAN::|bfLessp| 
  BOOTTRAN::BOOTCLAMLINES 
  BOOTTRAN::|bfQ| 
  BOOTTRAN::BVEC-MAKE-FULL 
  BOOTTRAN::|shoeXref| 
  BOOTTRAN::CHARMEM 
  BOOTTRAN::|shoeFileMap| 
  BOOTTRAN::|bfElt| 
  BOOTTRAN::|bMap| 
  BOOTTRAN::|bfCaseItem| 
  BOOTTRAN::SHOEGREATERP 
  BOOTTRAN::|bfMain| 
  BOOTTRAN::|bf0COLLECT| 
  BOOTTRAN::|bfCARCDR| 
  BOOTTRAN::SETDIFFERENCE 
  BOOTTRAN::|bf0APPEND| 
  BOOTTRAN::|bfLp| 
  BOOTTRAN::|bfISReverse| 
  BOOTTRAN::|bfStruct| 
  BOOTTRAN::|addCARorCDR| 
  BOOTTRAN::|bfPosition| 
  BOOTTRAN::|shoeReadLisp| 
  BOOTTRAN::|shoePileTree| 
  BOOTTRAN::|bfFlatten| 
  BOOTTRAN::|eqshoePileTree| 
  BOOTTRAN::|shoePROG| 
  BOOTTRAN::|shoePileForest1| 
  BOOTTRAN::|bfCase| 
  BOOTTRAN::|shoePileForest| 
  BOOTTRAN::|bfLocal| 
  BOOTTRAN::|bpMissingMate| 
  BOOTTRAN::|streamTake| 
  BOOTTRAN::|bfNameArgs| 
  BOOTTRAN::|shoeFileTrees| 
  BOOTTRAN::|shoeFileLine| 
  BOOTTRAN::|shoePileCoagulate| 
  BOOTTRAN::|bfLpCross| 
  BOOTTRAN::EQCAR 
  BOOTTRAN::|bfLp1| 
  BOOTTRAN::CLESSP 
  BOOTTRAN::|dqAppend| 
  BOOTTRAN::|bfTagged| 
  BOOTTRAN::|bfCaseItems| 
  BOOTTRAN::|shoeRemoveStringIfNec| 
  BOOTTRAN::|shoeAddStringIfNec| 
  BOOTTRAN::|shoePileCtree| 
  BOOTTRAN::|bfLET| 
  BOOTTRAN::|bfColonAppend| 
  BOOTTRAN::|bfSUBLIS1| 
  BOOTTRAN::|bfSUBLIS| 
  BOOTTRAN::|shoeTransformToFile| 
  BOOTTRAN::|bpLeftAssoc| 
  BOOTTRAN::|shoeToConsole| 
  BOOTTRAN::|bfDCollect| 
  BOOTTRAN::|shoeAccumulateLines| 
  BOOTTRAN::|bfCollect| 
  BOOTTRAN::|defuse1| 
  BOOTTRAN::|bfDefinition1| 
  BOOTTRAN::|bpSemiListing| 
  BOOTTRAN::|shoeInsert| 
  BOOTTRAN::|bpSpecificErrorAtToken| 
  BOOTTRAN::|defuse| 
  BOOTTRAN::FC 
  BOOTTRAN::|bfExit| 
  BOOTTRAN::|shoePPtoFile| 
  BOOTTRAN::|bfIfThenOnly|)))
 
