\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/doc Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{The bibtex stanza}
Axiom pamphlet files have citations. We collect all of the 
pamphlet file citations into this one file so we have a standard
place and format for bibliographic references.

Citations of pamphlet files which are local are generally by
the name. For example, [[asq.c.pamphlet]] would be cited using
[[\cite{asq.c}]].
<<bibtex>>=
${MID}/axiom.bib: ${IN}/axiom.bib.pamphlet
	@echo 1 making ${MID}/axiom.bib from ${IN}/axiom.bib.pamphlet
	@ (cd ${MID} ; \
	 ${TANGLE} ${IN}/axiom.bib.pamphlet >${MID}/axiom.bib )

@ 
\section{The axiom.sty stanza}
Axiom uses a style file that is a modified version of the noweb.sty
originally written by Norman Ramsey. To this we've added macros to
support the CATS (Computer Algebra Test Suite).
<<axiom.sty>>=
${STY}/axiom.sty: ${IN}/axiom.sty.pamphlet
	@echo 2 making ${STY}/axiom.sty from ${IN}/axiom.sty.pamphlet
	@(cd ${STY} ; \
	${TANGLE} -R"axiom.sty" ${IN}/axiom.sty.pamphlet >axiom.sty )

@ 
\section{The Developer Notes}
This file contains a random collection of facts about Axiom
intended for developers. It talks about directory structure,
internal representations, debugging tools, and gives a cookbook
for using CVS. There is nothing of interest for the end user.
<<DeveloperNotes>>=
${DVI}/DeveloperNotes.dvi: ${IN}/DeveloperNotes.pamphlet ${STY}/axiom.sty
	@echo 3 making ${DVI}/DeveloperNotes.dvi from ${IN}/DeveloperNotes.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/DeveloperNotes.pamphlet ${MID} ; \
	${DOCUMENT} ${NOISE} DeveloperNotes ; \
	cp DeveloperNotes.dvi ${DVI} )

@
\section{Book}
This file contains the main documentation for Axiom, the Axiom book.
We take care to copy the whole [[ps/]] directory that contains images
used by the book.
<<Book>>=
${DVI}/book.dvi: ${IN}/book.pamphlet
	@echo 4 making ${DVI}/book.dvi from ${IN}/book.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/book.pamphlet ${MID} ; \
	cp -pr ${IN}/ps ${MID} ; \
	${DOCUMENT} ${NOISE} book ; \
	cp book.dvi ${DVI} ; \
	cp -r ${IN}/ps ${DVI} )

@
\section{Book Volume 1: Tutorial}
This is the tutorial volume, the first book in the new axiom series.
<<bookvol1>>=
${DVI}/bookvol1.dvi: ${IN}/bookvol1.pamphlet
	@echo 4 making ${DVI}/bookvol1.dvi from ${IN}/bookvol1.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/bookvol1.pamphlet ${MID} ;\
	cp -pr ${IN}/ps ${MID} ; \
	${DOCUMENT} ${NOISE} bookvol1 ; \
	cp bookvol1.dvi ${DVI} ; \
	cp -r ${IN}/ps ${DVI} )

@
\section{The End Papers}
This document reproduces the diagrams on the inside covers of the
original Jenks Axiom book but adds hyperlinks.
<<Endpapers>>=
${DVI}/endpaper.dvi: ${IN}/endpaper.pamphlet
	@echo 4 making ${DVI}/endpaper.dvi from ${IN}/endpaper.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/endpaper.pamphlet ${MID} ; \
	cp -pr ${IN}/ps ${MID} ; \
	${DOCUMENT} ${NOISE} endpaper ; \
	cp endpaper.dvi ${DVI} ; \
	cp -r ${IN}/ps ${DVI} )

@
\section{Rosetta}
The Rosetta document is an effort to give a command-by-command
way of moving between various computer algebra systems. It was
originally created for the "Rosetta" series of CDs. These Rosetta
CDs contained multiple, free computer algebra systems.
<<Rosetta>>=
${DVI}/Rosetta.dvi: ${IN}/Rosetta.pamphlet
	@echo 5 building ${DVI}/Rosetta.dvi from ${IN}/Rosetta.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/Rosetta.pamphlet ${MID} ; \
	${DOCUMENT} ${NOISE} Rosetta ; \
	cp Rosetta.dvi ${DVI} )

@
\section{The booklet command}
<<booklet>>=
${OUT}/booklet: ${MID}/booklet.o
	@echo 6 making ${OUT}/booklet from ${MID}/booklet.o
	@(cd ${OUT} ; \
	  ${CC} ${MID}/booklet.o -o booklet )

${MID}/booklet.o: ${INT}/booklet.c
	@echo 7 making ${MID}/booklet.o from ${INT}/booklet.c
	@(cd ${MID} ; \
	  ${CC} -c ${INT}/booklet.c )

${INT}/booklet.c: ${IN}/booklet.c.pamphlet
	@echo 8 making ${INT}/booklet.c from ${IN}/booklet.c.pamphlet
	@(cd ${INT} ; \
	  ${TANGLE} ${IN}/booklet.c.pamphlet >booklet.c )
	  
@
\section{The Makefile}
We need to document the commands.
<<*>>=
IN=${SRC}/doc
MID=${INT}/doc
OUT=${MNT}/${SYS}/bin
STY=${OUT}/tex
DVI=${MNT}/${SYS}/doc
DOC=${INT}/doc

FILES= ${MID}/axiom.bib ${STY}/axiom.sty ${DVI}/DeveloperNotes.dvi \
       ${DVI}/book.dvi ${DVI}/bookvol1.dvi ${DVI}/endpaper.dvi \
       ${DVI}/Rosetta.dvi

CMDS=${OUT}/booklet

all: ${FILES} ${CMDS}
	@echo 9 finished ${IN}

<<booklet>>
<<bibtex>>
<<axiom.sty>>
<<DeveloperNotes>>
<<Book>>
<<bookvol1>>
<<Endpapers>>
<<Rosetta>>

document:
	@echo 10 documenting ${SRC}/doc

clean:
	@echo 11 cleaning ${SRC}/doc
@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
