\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/doc Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject

\section{The axiom.sty stanza}
Axiom uses a style file that is a modified version of the noweb.sty
originally written by Norman Ramsey. To this we've added macros to
support the CATS (Computer Algebra Test Suite).
<<axiom.sty>>=
${STY}/axiom.sty: ${IN}/axiom.sty.pamphlet
	@echo 2 making ${STY}/axiom.sty from ${IN}/axiom.sty.pamphlet
	@(cd ${STY} ; \
	${TANGLE} -R"axiom.sty" ${IN}/axiom.sty.pamphlet >axiom.sty )

@ 
\section{The Reference Card}
This is the one-page, 2 sided reference card
<<refcard>>=
${DVI}/refcard.pdf: ${IN}/refcard.pamphlet
	@echo 4 making ${DVI}/refcard.dvi from ${IN}/refcard.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/refcard.pamphlet ${MID} ;\
	latex refcard.pamphlet ; \
	dvipdf refcard.dvi ; \
	cp refcard.pdf ${DVI} ; \
	rm refcard.log ; \
	rm refcard.aux )

@
\section{The End Papers}
This document reproduces the diagrams on the inside covers of the
original Jenks Axiom book but adds hyperlinks.
<<Endpapers>>=
${DVI}/endpaper.pdf: ${IN}/endpaper.pamphlet
	@echo 4 making ${DVI}/endpaper.pdf from ${IN}/endpaper.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/endpaper.pamphlet ${MID} ; \
	mkdir -p ${MID}/ps ; \
	cp ${IN}/ps/*ps* ${MID}/ps ; \
	latex endpaper.pamphlet ; \
	latex endpaper.pamphlet ; \
	dvipdf endpaper.dvi ; \
	cp endpaper.pdf ${DVI} ; \
	rm endpaper.* ; \
	mkdir -p ${DVI}/ps ; \
	cp ${IN}/ps/*ps* ${DVI}/ps )

@
\section{rosetta}
The rosetta document is an effort to give a command-by-command
way of moving between various computer algebra systems. It was
originally created for the "rosetta" series of CDs. These rosetta
CDs contained multiple, free computer algebra systems.
<<rosetta>>=
${DVI}/rosetta.pdf: ${IN}/rosetta.pamphlet
	@echo 5 building ${DVI}/rosetta.dvi from ${IN}/rosetta.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/rosetta.pamphlet ${MID} ; \
	latex rosetta.pamphlet ; \
	dvipdf rosetta.dvi ; \
	cp rosetta.pdf ${DVI} )

@
\section{The booklet command}
<<booklet>>=
${OUT}/booklet: ${MID}/booklet.o
	@echo 6 making ${OUT}/booklet from ${MID}/booklet.o
	@(cd ${OUT} ; \
	  ${CC} ${MID}/booklet.o -o booklet )

${MID}/booklet.o: ${INT}/booklet.c
	@echo 7 making ${MID}/booklet.o from ${INT}/booklet.c
	@(cd ${MID} ; \
	  ${CC} -c ${INT}/booklet.c )

${INT}/booklet.c: ${IN}/booklet.c.pamphlet
	@echo 8 making ${INT}/booklet.c from ${IN}/booklet.c.pamphlet
	@(cd ${INT} ; \
	  ${TANGLE} ${IN}/booklet.c.pamphlet >booklet.c )
	  
@
\section{The Makefile}
We need to document the commands.
<<*>>=
IN=${SRC}/doc
MID=${INT}/doc
OUT=${MNT}/${SYS}/bin
STY=${OUT}/tex
DVI=${MNT}/${SYS}/doc
DOC=${INT}/doc

FILES= ${STY}/axiom.sty ${DVI}/refcard.pdf \
       ${DVI}/endpaper.pdf ${DVI}/rosetta.pdf 

CMDS=${OUT}/booklet

all: ${FILES} ${CMDS}
	@echo 9 finished ${IN}

<<booklet>>
<<axiom.sty>>
<<refcard>>
<<Endpapers>>
<<rosetta>>

document:
	@echo 10 documenting ${SRC}/doc

clean:
	@echo 11 cleaning ${SRC}/doc
@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
