\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/doc Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject

\section{The Reference Card}
This is the one-page, 2 sided reference card
\begin{chunk}{refcard}
${DVI}/refcard.pdf: ${IN}/refcard.pamphlet
	@echo sd02 making ${DVI}/refcard.dvi from ${IN}/refcard.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/refcard.pamphlet ${MID} ;\
	latex refcard.pamphlet ; \
	dvipdf refcard.dvi ; \
	cp refcard.pdf ${DVI} ; \
	rm refcard.log ; \
	rm refcard.aux )

\end{chunk}
\section{The End Papers}
This document reproduces the diagrams on the inside covers of the
original Jenks Axiom book but adds hyperlinks.
\begin{chunk}{Endpapers}
${DVI}/endpaper.pdf: ${IN}/endpaper.pamphlet
	@echo sd03 making ${DVI}/endpaper.pdf from ${IN}/endpaper.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/endpaper.pamphlet ${MID} ; \
	mkdir -p ${MID}/ps ; \
	cp ${IN}/ps/*ps* ${MID}/ps ; \
	latex endpaper.pamphlet ; \
	latex endpaper.pamphlet ; \
	dvipdf endpaper.dvi ; \
	cp endpaper.pdf ${DVI} ; \
	rm endpaper.* ; \
	mkdir -p ${DVI}/ps ; \
	cp ${IN}/ps/*ps* ${DVI}/ps )

\end{chunk}
\section{rosetta}
The rosetta document is an effort to give a command-by-command
way of moving between various computer algebra systems. It was
originally created for the "rosetta" series of CDs. These rosetta
CDs contained multiple, free computer algebra systems.
\begin{chunk}{rosetta}
${DVI}/rosetta.pdf: ${IN}/rosetta.pamphlet
	@echo sd04 building ${DVI}/rosetta.dvi from ${IN}/rosetta.pamphlet
	@(cd ${MID} ; \
	cp ${IN}/rosetta.pamphlet ${MID} ; \
	latex rosetta.pamphlet ; \
	dvipdf rosetta.dvi ; \
	cp rosetta.pdf ${DVI} )

\end{chunk}
\section{The booklet command}
\begin{chunk}{booklet}
${OUT}/booklet: ${MID}/booklet.o
	@echo sd05 making ${OUT}/booklet from ${MID}/booklet.o
	@(cd ${OUT} ; \
	  ${CC} ${MID}/booklet.o -o booklet )

${MID}/booklet.o: ${INT}/booklet.c
	@echo sd06 making ${MID}/booklet.o from ${INT}/booklet.c
	@(cd ${MID} ; \
	  ${CC} -c ${INT}/booklet.c )

${INT}/booklet.c: ${IN}/booklet.c.pamphlet
	@echo sd07 making ${INT}/booklet.c from ${IN}/booklet.c.pamphlet
	@(cd ${INT} ; \
	  ${BOOKS}/tanglec ${IN}/booklet.c.pamphlet >booklet.c )
	  
\end{chunk}
\section{The Makefile}
We need to document the commands.
\begin{chunk}{*}
IN=${SRC}/doc
MID=${INT}/doc
OUT=${MNT}/${SYS}/bin
STY=${OUT}/tex
DVI=${MNT}/${SYS}/doc
DOC=${INT}/doc

FILES= ${DVI}/refcard.pdf ${DVI}/endpaper.pdf ${DVI}/rosetta.pdf 

CMDS=${OUT}/booklet

all: announce ${FILES} ${CMDS}
	@echo sd08 finished ${IN}

announce:
	@ echo ======================================
	@ echo src/doc BUILDING DOC FILES
	@ echo ======================================

\getchunk{booklet}
\getchunk{refcard}
\getchunk{Endpapers}
\getchunk{rosetta}

document:
	@echo sd09 documenting ${SRC}/doc

clean:
	@echo sd10 cleaning ${SRC}/doc
\end{chunk}
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
