\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{src/graph/viewman Makefile}
\author{The Axiom Team}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{environment}
<<environment>>=
IN=	${SRC}/graph/viewman
MIDINT=	${INT}/graph/viewman
MIDOBJ=	${OBJ}/${SYS}/graph/viewman
OUT=	${MNT}/${SYS}/lib
LIB=    ${OBJ}/${SYS}/lib
DOC=    ${MNT}/${SYS}/doc/src/graph

# local include files shared by graphics
LINC=	${SRC}/graph/include

# global include files shared by everyone 
GINC=	${SRC}/include

@
\section{viewman}
<<viewman>>=
${OUT}/viewman: ${OBJS} ${LIB}/util.o ${LIB}/bsdsignal.o
	@ echo 1 linking ${OUT}/viewman
	@ ${CC} ${OBJS} -o ${OUT}/viewman ${LIB}/util.o ${LIB}/bsdsignal.o ${LDFLAGS}

@
<<viewman.c (MIDINT from IN)>>=
${MIDINT}/viewman.c: ${IN}/viewman.c.pamphlet
	@ echo 2 ${MIDINT}/viewman.c from ${IN}/viewman.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/viewman.c.pamphlet >viewman.c )

@
<<viewman.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/viewman.o: ${HEADERS} ${MIDINT}/viewman.c
	@ echo 3 making ${MIDOBJ}/viewman.o from ${MIDINT}/viewman.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/viewman.c )

@
<<viewman.c.dvi (DOC from IN)>>=
${DOC}/viewman.c.dvi: ${IN}/viewman.c.pamphlet 
	@echo 4 making ${DOC}/viewman.c.dvi from ${IN}/viewman.c.pamphlet
	@(cd ${DOC} ; \
	cp ${IN}/viewman.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} viewman.c ; \
	rm -f ${DOC}/viewman.c.pamphlet ; \
	rm -f ${DOC}/viewman.c.tex ; \
	rm -f ${DOC}/viewman.c )

@
\section{sselect}
<<sselect.c (MIDINT from IN)>>=
${MIDINT}/sselect.c: ${IN}/sselect.c.pamphlet
	@ echo 5 ${MIDINT}/sselect.c from ${IN}/sselect.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/sselect.c.pamphlet >sselect.c )

@
<<sselect.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/sselect.o: ${HEADERS} ${MIDINT}/sselect.c
	@ echo 6 making ${MIDOBJ}/sselect.o from ${MIDINT}/sselect.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/sselect.c )

@
<<sselect.c.dvi (DOC from IN)>>=
${DOC}/sselect.c.dvi: ${IN}/sselect.c.pamphlet 
	@echo 7 making ${DOC}/sselect.c.dvi from ${IN}/sselect.c.pamphlet
	@(cd ${DOC} ; \
	cp ${IN}/sselect.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} sselect.c ; \
	rm -f ${DOC}/sselect.c.pamphlet ; \
	rm -f ${DOC}/sselect.c.tex ; \
	rm -f ${DOC}/sselect.c )

@
\section{cleanup}
<<cleanup.c (MIDINT from IN)>>=
${MIDINT}/cleanup.c: ${IN}/cleanup.c.pamphlet
	@ echo 8 ${MIDINT}/cleanup.c from ${IN}/cleanup.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/cleanup.c.pamphlet >cleanup.c )

@
<<cleanup.c (MIDOBJ from MIDINT)>>=
${MIDOBJ}/cleanup.o: ${HEADERS} ${MIDINT}/cleanup.c
	@ echo 9 making ${MIDOBJ}/cleanup.o from ${MIDINT}/cleanup.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/cleanup.c )

@
<<cleanup.c.dvi (DOC from IN)>>=
${DOC}/cleanup.c.dvi: ${IN}/cleanup.c.pamphlet 
	@echo 10 making ${DOC}/cleanup.c.dvi from ${IN}/cleanup.c.pamphlet
	@(cd ${DOC} ; \
	cp ${IN}/cleanup.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} cleanup.c ; \
	rm -f ${DOC}/cleanup.c.pamphlet ; \
	rm -f ${DOC}/cleanup.c.tex ; \
	rm -f ${DOC}/cleanup.c )

@
\section{fun2D}
<<fun2D.c (MIDINT from IN)>>=
${MIDINT}/fun2D.c: ${IN}/fun2D.c.pamphlet
	@ echo 11 ${MIDINT}/fun2D.c from ${IN}/fun2D.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/fun2D.c.pamphlet >fun2D.c )

@
<<fun2D.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/fun2D.o: ${HEADERS} ${MIDINT}/fun2D.c
	@ echo 12 making ${MIDOBJ}/fun2D.o from ${MIDINT}/fun2D.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/fun2D.c )

@
<<fun2D.c.dvi (DOC from IN)>>=
${DOC}/fun2D.c.dvi: ${IN}/fun2D.c.pamphlet 
	@echo 13 making ${DOC}/fun2D.c.dvi from ${IN}/fun2D.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/fun2D.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} fun2D.c ; \
	rm -f ${DOC}/fun2D.c.pamphlet ; \
	rm -f ${DOC}/fun2D.c.tex ; \
	rm -f ${DOC}/fun2D.c )

@
\section{make2D}
<<make2D.c (MIDINT from IN)>>=
${MIDINT}/make2D.c: ${IN}/make2D.c.pamphlet
	@ echo 14 ${MIDINT}/make2D.c from ${IN}/make2D.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/make2D.c.pamphlet >make2D.c )

<<make2D.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/make2D.o: ${HEADERS} ${MIDINT}/make2D.c
	@ echo 15 making ${MIDOBJ}/make2D.o from ${MIDINT}/make2D.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/make2D.c )

@
<<make2D.c.dvi (DOC from IN)>>=
${DOC}/make2D.c.dvi: ${IN}/make2D.c.pamphlet 
	@echo 16 making ${DOC}/make2D.c.dvi from ${IN}/make2D.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/make2D.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} make2D.c ; \
	rm -f ${DOC}/make2D.c.pamphlet ; \
	rm -f ${DOC}/make2D.c.tex ; \
	rm -f ${DOC}/make2D.c )

@
\section{makeGraph}
<<makeGraph.c (MIDINT from IN)>>=
${MIDINT}/makeGraph.c: ${IN}/makeGraph.c.pamphlet
	@ echo 17 ${MIDINT}/makeGraph.c from ${IN}/makeGraph.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/makeGraph.c.pamphlet >makeGraph.c )

@
<<makeGraph.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/makeGraph.o: ${HEADERS} ${MIDINT}/makeGraph.c
	@ echo 18 making ${MIDOBJ}/makeGraph.o from ${MIDINT}/makeGraph.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/makeGraph.c )

@
<<makeGraph.c.dvi (DOC from IN)>>=
${DOC}/makeGraph.c.dvi: ${IN}/makeGraph.c.pamphlet 
	@echo 19 making ${DOC}/makeGraph.c.dvi from ${IN}/makeGraph.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/makeGraph.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} makeGraph.c ; \
	rm -f ${DOC}/makeGraph.c.pamphlet ; \
	rm -f ${DOC}/makeGraph.c.tex ; \
	rm -f ${DOC}/makeGraph.c )

@
\section{fun3D}
<<fun3D.c (MIDINT from IN)>>=
${MIDINT}/fun3D.c: ${IN}/fun3D.c.pamphlet
	@ echo 20 ${MIDINT}/fun3D.c from ${IN}/fun3D.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/fun3D.c.pamphlet >fun3D.c )

@
<<fun3D.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/fun3D.o: ${HEADERS} ${MIDINT}/fun3D.c
	@ echo 21 making ${MIDOBJ}/fun3D.o from ${MIDINT}/fun3D.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/fun3D.c )

@
<<fun3D.c.dvi (DOC from IN)>>=
${DOC}/fun3D.c.dvi: ${IN}/fun3D.c.pamphlet 
	@echo 22 making ${DOC}/fun3D.c.dvi from ${IN}/fun3D.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/fun3D.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} fun3D.c ; \
	rm -f ${DOC}/fun3D.c.pamphlet ; \
	rm -f ${DOC}/fun3D.c.tex ; \
	rm -f ${DOC}/fun3D.c )

@
\section{make3D}
<<make3D.c (MIDINT from IN)>>=
${MIDINT}/make3D.c: ${IN}/make3D.c.pamphlet
	@ echo 23 ${MIDINT}/make3D.c from ${IN}/make3D.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/make3D.c.pamphlet >make3D.c )

@
<<make3D.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/make3D.o: ${HEADERS} ${MIDINT}/make3D.c
	@ echo 24 making ${MIDOBJ}/make3D.o from ${MIDINT}/make3D.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/make3D.c )

@
<<make3D.c.dvi (DOC from IN)>>=
${DOC}/make3D.c.dvi: ${IN}/make3D.c.pamphlet 
	@echo 25 making ${DOC}/make3D.c.dvi from ${IN}/make3D.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/make3D.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} make3D.c ; \
	rm -f ${DOC}/make3D.c.pamphlet ; \
	rm -f ${DOC}/make3D.c.tex ; \
	rm -f ${DOC}/make3D.c )

@
\section{readView}
<<readView.c (MIDINT from IN)>>=
${MIDINT}/readView.c: ${IN}/readView.c.pamphlet
	@ echo 26 ${MIDINT}/readView.c from ${IN}/readView.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/readView.c.pamphlet >readView.c )

@
<<readView.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/readView.o: ${HEADERS} ${MIDINT}/readView.c
	@ echo 27 making ${MIDOBJ}/readView.o from ${MIDINT}/readView.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/readView.c )

@
<<readView.c.dvi (DOC from IN)>>=
${DOC}/readView.c.dvi: ${IN}/readView.c.pamphlet 
	@echo 28 making ${DOC}/readView.c.dvi from ${IN}/readView.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/readView.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} readView.c ; \
	rm -f ${DOC}/readView.c.pamphlet ; \
	rm -f ${DOC}/readView.c.tex ; \
	rm -f ${DOC}/readView.c )

@
<<*>>=
<<environment>>

CFLAGS  = ${CCF} -I${LINC} -I${GINC} -I${IN}
LDFLAGS = ${LDF} -lX11

DOCFILES=${DOC}/viewman.c.dvi ${DOC}/sselect.c.dvi ${DOC}/cleanup.c.dvi \
         ${DOC}/fun2D.c.dvi   ${DOC}/make2D.c.dvi  ${DOC}/makeGraph.c.dvi \
         ${DOC}/fun3D.c.dvi   ${DOC}/make3D.c.dvi  ${DOC}/readView.c.dvi

OBJS=   ${MIDOBJ}/viewman.o ${MIDOBJ}/readView.o  ${MIDOBJ}/make3D.o \
	${MIDOBJ}/fun3D.o   ${MIDOBJ}/makeGraph.o ${MIDOBJ}/make2D.o \
        ${MIDOBJ}/fun2D.o   ${MIDOBJ}/cleanup.o   ${MIDOBJ}/sselect.o \
        ${OBJ}/${SYS}/lib/sockio-c.o

HEADERS= ${IN}/viewman.h       ${LINC}/component.h ${LINC}/view2D.h  \
         ${LINC}/view3D.h      ${LINC}/tube.h      ${LINC}/actions.h \
         ${LINC}/viewCommand.h ${GINC}/com.h

all: ${OBJS} ${OUT}/viewman ${DOCFILES}
	@ echo 30 finished ${IN}

<<viewman>>

<<viewman.c (MIDINT from IN)>>
<<viewman.o (MIDOBJ from MIDINT)>>
<<viewman.c.dvi (DOC from IN)>>

<<sselect.c (MIDINT from IN)>>
<<sselect.o (MIDOBJ from MIDINT)>>
<<sselect.c.dvi (DOC from IN)>>

<<cleanup.c (MIDINT from IN)>>
<<cleanup.c (MIDOBJ from MIDINT)>>
<<cleanup.c.dvi (DOC from IN)>>

<<fun2D.c (MIDINT from IN)>>
<<fun2D.o (MIDOBJ from MIDINT)>>
<<fun2D.c.dvi (DOC from IN)>>

<<make2D.c (MIDINT from IN)>>
<<make2D.o (MIDOBJ from MIDINT)>>
<<make2D.c.dvi (DOC from IN)>>

<<makeGraph.c (MIDINT from IN)>>
<<makeGraph.o (MIDOBJ from MIDINT)>>
<<makeGraph.c.dvi (DOC from IN)>>

<<fun3D.c (MIDINT from IN)>>
<<fun3D.o (MIDOBJ from MIDINT)>>
<<fun3D.c.dvi (DOC from IN)>>

<<make3D.c (MIDINT from IN)>>
<<make3D.o (MIDOBJ from MIDINT)>>
<<make3D.c.dvi (DOC from IN)>>

<<readView.c (MIDINT from IN)>>
<<readView.o (MIDOBJ from MIDINT)>>
<<readView.c.dvi (DOC from IN)>>

clean: 
	@ echo 31 cleaning ${IN}/viewman

document: 
	@ echo 32 documenting ${IN}/viewman


@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
