\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{src/graph/viewman Makefile}
\author{The Axiom Team}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{environment}
<<environment>>=
IN=	${SRC}/graph/viewman
MIDINT=	${INT}/graph/viewman
MIDOBJ=	${OBJ}/${SYS}/graph/viewman
OUT=	${MNT}/${SYS}/lib
LIB=    ${OBJ}/${SYS}/lib
DOC=    ${MNT}/${SYS}/doc/src/graph

# local include files shared by graphics
LINC=	${SRC}/graph/include

# global include files shared by everyone 
GINC=	${SRC}/include

@
\section{viewman}
<<viewman>>=
${OUT}/viewman: ${OBJS} ${LIB}/util.o ${LIB}/bsdsignal.o
	@ echo 1 linking ${OUT}/viewman
	@ ${CC} ${OBJS} -o ${OUT}/viewman ${LIB}/util.o ${LIB}/bsdsignal.o ${LDFLAGS}

@
<<viewman.c (MIDINT from IN)>>=
${MIDINT}/viewman.c: ${IN}/viewman.c.pamphlet
	@ echo 2 ${MIDINT}/viewman.c from ${IN}/viewman.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/viewman.c.pamphlet >viewman.c )

@
<<viewman.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/viewman.o: ${HEADERS} ${MIDINT}/viewman.c
	@ echo 3 making ${MIDOBJ}/viewman.o from ${MIDINT}/viewman.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/viewman.c )

@
<<viewman.c.dvi (DOC from IN)>>=
${DOC}/viewman.c.dvi: ${IN}/viewman.c.pamphlet 
	@echo 4 making ${DOC}/viewman.c.dvi from ${IN}/viewman.c.pamphlet
	@(cd ${DOC} ; \
	cp ${IN}/viewman.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} viewman.c ; \
	rm -f ${DOC}/viewman.c.pamphlet ; \
	rm -f ${DOC}/viewman.c.tex ; \
	rm -f ${DOC}/viewman.c )

@
\section{sselect}
<<sselect.c (MIDINT from IN)>>=
${MIDINT}/sselect.c: ${IN}/sselect.c.pamphlet
	@ echo 5 ${MIDINT}/sselect.c from ${IN}/sselect.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/sselect.c.pamphlet >sselect.c )

@
<<sselect.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/sselect.o: ${HEADERS} ${MIDINT}/sselect.c
	@ echo 6 making ${MIDOBJ}/sselect.o from ${MIDINT}/sselect.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/sselect.c )

@
<<sselect.c.dvi (DOC from IN)>>=
${DOC}/sselect.c.dvi: ${IN}/sselect.c.pamphlet 
	@echo 7 making ${DOC}/sselect.c.dvi from ${IN}/sselect.c.pamphlet
	@(cd ${DOC} ; \
	cp ${IN}/sselect.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} sselect.c ; \
	rm -f ${DOC}/sselect.c.pamphlet ; \
	rm -f ${DOC}/sselect.c.tex ; \
	rm -f ${DOC}/sselect.c )

@
\section{cleanup}
<<cleanup.c (MIDINT from IN)>>=
${MIDINT}/cleanup.c: ${IN}/cleanup.c.pamphlet
	@ echo 8 ${MIDINT}/cleanup.c from ${IN}/cleanup.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/cleanup.c.pamphlet >cleanup.c )

@
<<cleanup.c (MIDOBJ from MIDINT)>>=
${MIDOBJ}/cleanup.o: ${HEADERS} ${MIDINT}/cleanup.c
	@ echo 9 making ${MIDOBJ}/cleanup.o from ${MIDINT}/cleanup.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/cleanup.c )

@
<<cleanup.c.dvi (DOC from IN)>>=
${DOC}/cleanup.c.dvi: ${IN}/cleanup.c.pamphlet 
	@echo 10 making ${DOC}/cleanup.c.dvi from ${IN}/cleanup.c.pamphlet
	@(cd ${DOC} ; \
	cp ${IN}/cleanup.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} cleanup.c ; \
	rm -f ${DOC}/cleanup.c.pamphlet ; \
	rm -f ${DOC}/cleanup.c.tex ; \
	rm -f ${DOC}/cleanup.c )

@
\section{fun2d}
<<fun2d.c (MIDINT from IN)>>=
${MIDINT}/fun2d.c: ${IN}/fun2d.c.pamphlet
	@ echo 11 ${MIDINT}/fun2d.c from ${IN}/fun2d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/fun2d.c.pamphlet >fun2d.c )

@
<<fun2d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/fun2d.o: ${HEADERS} ${MIDINT}/fun2d.c
	@ echo 12 making ${MIDOBJ}/fun2d.o from ${MIDINT}/fun2d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/fun2d.c )

@
<<fun2d.c.dvi (DOC from IN)>>=
${DOC}/fun2d.c.dvi: ${IN}/fun2d.c.pamphlet 
	@echo 13 making ${DOC}/fun2d.c.dvi from ${IN}/fun2d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/fun2d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} fun2d.c ; \
	rm -f ${DOC}/fun2d.c.pamphlet ; \
	rm -f ${DOC}/fun2d.c.tex ; \
	rm -f ${DOC}/fun2d.c )

@
\section{make2d}
<<make2d.c (MIDINT from IN)>>=
${MIDINT}/make2d.c: ${IN}/make2d.c.pamphlet
	@ echo 14 ${MIDINT}/make2d.c from ${IN}/make2d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/make2d.c.pamphlet >make2d.c )

<<make2d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/make2d.o: ${HEADERS} ${MIDINT}/make2d.c
	@ echo 15 making ${MIDOBJ}/make2d.o from ${MIDINT}/make2d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/make2d.c )

@
<<make2d.c.dvi (DOC from IN)>>=
${DOC}/make2d.c.dvi: ${IN}/make2d.c.pamphlet 
	@echo 16 making ${DOC}/make2d.c.dvi from ${IN}/make2d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/make2d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} make2d.c ; \
	rm -f ${DOC}/make2d.c.pamphlet ; \
	rm -f ${DOC}/make2d.c.tex ; \
	rm -f ${DOC}/make2d.c )

@
\section{makegraph}
<<makegraph.c (MIDINT from IN)>>=
${MIDINT}/makegraph.c: ${IN}/makegraph.c.pamphlet
	@ echo 17 ${MIDINT}/makegraph.c from ${IN}/makegraph.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/makegraph.c.pamphlet >makegraph.c )

@
<<makegraph.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/makegraph.o: ${HEADERS} ${MIDINT}/makegraph.c
	@ echo 18 making ${MIDOBJ}/makegraph.o from ${MIDINT}/makegraph.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/makegraph.c )

@
<<makegraph.c.dvi (DOC from IN)>>=
${DOC}/makegraph.c.dvi: ${IN}/makegraph.c.pamphlet 
	@echo 19 making ${DOC}/makegraph.c.dvi from ${IN}/makegraph.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/makegraph.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} makegraph.c ; \
	rm -f ${DOC}/makegraph.c.pamphlet ; \
	rm -f ${DOC}/makegraph.c.tex ; \
	rm -f ${DOC}/makegraph.c )

@
\section{fun3d}
<<fun3d.c (MIDINT from IN)>>=
${MIDINT}/fun3d.c: ${IN}/fun3d.c.pamphlet
	@ echo 20 ${MIDINT}/fun3d.c from ${IN}/fun3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/fun3d.c.pamphlet >fun3d.c )

@
<<fun3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/fun3d.o: ${HEADERS} ${MIDINT}/fun3d.c
	@ echo 21 making ${MIDOBJ}/fun3d.o from ${MIDINT}/fun3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/fun3d.c )

@
<<fun3d.c.dvi (DOC from IN)>>=
${DOC}/fun3d.c.dvi: ${IN}/fun3d.c.pamphlet 
	@echo 22 making ${DOC}/fun3d.c.dvi from ${IN}/fun3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/fun3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} fun3d.c ; \
	rm -f ${DOC}/fun3d.c.pamphlet ; \
	rm -f ${DOC}/fun3d.c.tex ; \
	rm -f ${DOC}/fun3d.c )

@
\section{make3d}
<<make3d.c (MIDINT from IN)>>=
${MIDINT}/make3d.c: ${IN}/make3d.c.pamphlet
	@ echo 23 ${MIDINT}/make3d.c from ${IN}/make3d.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/make3d.c.pamphlet >make3d.c )

@
<<make3d.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/make3d.o: ${HEADERS} ${MIDINT}/make3d.c
	@ echo 24 making ${MIDOBJ}/make3d.o from ${MIDINT}/make3d.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/make3d.c )

@
<<make3d.c.dvi (DOC from IN)>>=
${DOC}/make3d.c.dvi: ${IN}/make3d.c.pamphlet 
	@echo 25 making ${DOC}/make3d.c.dvi from ${IN}/make3d.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/make3d.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} make3d.c ; \
	rm -f ${DOC}/make3d.c.pamphlet ; \
	rm -f ${DOC}/make3d.c.tex ; \
	rm -f ${DOC}/make3d.c )

@
\section{readview}
<<readview.c (MIDINT from IN)>>=
${MIDINT}/readview.c: ${IN}/readview.c.pamphlet
	@ echo 26 ${MIDINT}/readview.c from ${IN}/readview.c.pamphlet
	@( cd ${MIDINT} ; \
	${TANGLE} ${IN}/readview.c.pamphlet >readview.c )

@
<<readview.o (MIDOBJ from MIDINT)>>=
${MIDOBJ}/readview.o: ${HEADERS} ${MIDINT}/readview.c
	@ echo 27 making ${MIDOBJ}/readview.o from ${MIDINT}/readview.c
	@ ( cd ${MIDOBJ} ; ${CC} ${CFLAGS} -c ${MIDINT}/readview.c )

@
<<readview.c.dvi (DOC from IN)>>=
${DOC}/readview.c.dvi: ${IN}/readview.c.pamphlet 
	@echo 28 making ${DOC}/readview.c.dvi from ${IN}/readview.c.pamphlet 
	@(cd ${DOC} ; \
	cp ${IN}/readview.c.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} readview.c ; \
	rm -f ${DOC}/readview.c.pamphlet ; \
	rm -f ${DOC}/readview.c.tex ; \
	rm -f ${DOC}/readview.c )

@
<<*>>=
<<environment>>

CFLAGS  = ${CCF} -I${LINC} -I${GINC} -I${IN}
LDFLAGS = ${LDF} -lX11

DOCFILES=${DOC}/viewman.c.dvi ${DOC}/sselect.c.dvi ${DOC}/cleanup.c.dvi \
         ${DOC}/fun2d.c.dvi   ${DOC}/make2d.c.dvi  ${DOC}/makegraph.c.dvi \
         ${DOC}/fun3d.c.dvi   ${DOC}/make3d.c.dvi  ${DOC}/readview.c.dvi

OBJS=   ${MIDOBJ}/viewman.o ${MIDOBJ}/readview.o  ${MIDOBJ}/make3d.o \
	${MIDOBJ}/fun3d.o   ${MIDOBJ}/makegraph.o ${MIDOBJ}/make2d.o \
        ${MIDOBJ}/fun2d.o   ${MIDOBJ}/cleanup.o   ${MIDOBJ}/sselect.o \
        ${OBJ}/${SYS}/lib/sockio-c.o

HEADERS= ${IN}/viewman.h       ${LINC}/component.h ${LINC}/view2d.h  \
         ${LINC}/view3d.h      ${LINC}/tube.h      ${LINC}/actions.h \
         ${LINC}/viewcommand.h ${GINC}/com.h

all: ${OBJS} ${OUT}/viewman ${DOCFILES}
	@ echo 30 finished ${IN}

<<viewman>>

<<viewman.c (MIDINT from IN)>>
<<viewman.o (MIDOBJ from MIDINT)>>
<<viewman.c.dvi (DOC from IN)>>

<<sselect.c (MIDINT from IN)>>
<<sselect.o (MIDOBJ from MIDINT)>>
<<sselect.c.dvi (DOC from IN)>>

<<cleanup.c (MIDINT from IN)>>
<<cleanup.c (MIDOBJ from MIDINT)>>
<<cleanup.c.dvi (DOC from IN)>>

<<fun2d.c (MIDINT from IN)>>
<<fun2d.o (MIDOBJ from MIDINT)>>
<<fun2d.c.dvi (DOC from IN)>>

<<make2d.c (MIDINT from IN)>>
<<make2d.o (MIDOBJ from MIDINT)>>
<<make2d.c.dvi (DOC from IN)>>

<<makegraph.c (MIDINT from IN)>>
<<makegraph.o (MIDOBJ from MIDINT)>>
<<makegraph.c.dvi (DOC from IN)>>

<<fun3d.c (MIDINT from IN)>>
<<fun3d.o (MIDOBJ from MIDINT)>>
<<fun3d.c.dvi (DOC from IN)>>

<<make3d.c (MIDINT from IN)>>
<<make3d.o (MIDOBJ from MIDINT)>>
<<make3d.c.dvi (DOC from IN)>>

<<readview.c (MIDINT from IN)>>
<<readview.o (MIDOBJ from MIDINT)>>
<<readview.c.dvi (DOC from IN)>>

clean: 
	@ echo 31 cleaning ${IN}/viewman

document: 
	@ echo 32 documenting ${IN}/viewman


@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
