\documentclass{article}
\usepackage{axiom}
\begin{document}
\title{\$SPAD/src/hyper Makefile}
\author{Timothy Daly}
\maketitle
\begin{abstract}
\end{abstract}
\eject
\tableofcontents
\eject
\section{Environment variables}
<<environment>>=
# this is where we are compiling from
IN=     ${SRC}/hyper

# this is the intermediate place 
MID=    ${INT}/hyper

# this is the intermediate place 
MIDOBJ=    ${OBJ}/${SYS}/hyper

# this is where to put the various commands
OUT=	${MNT}/${SYS}/bin
OUTLIB=	${MNT}/${SYS}/lib

# this is where the include files live
INC=    ${SRC}/include

# this is where we hid the libspad library
LIB=	${OBJ}/${SYS}/lib

# this is where the source file documentation ends up
DOC=    ${MNT}/${SYS}/doc/src/hyper

# this is where the hypertex documentation files are
HYPER=${MNT}/${SYS}/doc/hypertex

# this is where the hyperdoc pages are
PAGES=${HYPER}/pages

# this is where the hyperdoc bitmaps
BMAPS=${PAGES}/bitmaps

CFLAGS=	${CCF} -I${MID}
LDFLAGS= -L${LIB} -lspad ${LDF}

HTADD=${OUT}/htadd

INCLUDES = \
	${MID}/addfile.h ${MID}/cond.h ${MID}/dialog.h ${MID}/display.h     \
	${MID}/event.h ${MID}/extent.h ${MID}/group.h ${MID}/hterror.h      \
        ${MID}/hyper.h ${MID}/initx.h ${MID}/keyin.h ${MID}/lex.h           \
        ${MID}/mem.h ${MID}/parse.h ${MID}/parse-aux.h ${MID}/parse-paste.h \
        ${MID}/parse-types.h ${MID}/scrollbar.h ${MID}/show-types.h         \
        ${MID}/titlebar.h ${MID}/token.h

HYPER_OBJS = \
	${MIDOBJ}/addfile.o   ${MIDOBJ}/cond.o      ${MIDOBJ}/dialog.o \
        ${MIDOBJ}/display.o   ${MIDOBJ}/event.o     ${MIDOBJ}/extent1.o \
        ${MIDOBJ}/extent2.o   ${MIDOBJ}/form-ext.o  ${MIDOBJ}/group.o \
        ${MIDOBJ}/halloc.o    ${MIDOBJ}/hash.o      ${MIDOBJ}/hterror.o \
        ${MIDOBJ}/htinp.o     ${MIDOBJ}/hyper.o     ${MIDOBJ}/initx.o \
	${MIDOBJ}/input.o     ${MIDOBJ}/item.o      ${MIDOBJ}/keyin.o \
        ${MIDOBJ}/lex.o       ${MIDOBJ}/macro.o     ${MIDOBJ}/mem.o \
        ${MIDOBJ}/parse.o     ${MIDOBJ}/parse-aux.o ${MIDOBJ}/parse-input.o \
        ${MIDOBJ}/parse-paste.o ${MIDOBJ}/parse-types.o \
        ${MIDOBJ}/readbitmap.o  ${MIDOBJ}/scrollbar.o   \
        ${MIDOBJ}/show-types.o  ${MIDOBJ}/spadint.o \
        ${MIDOBJ}/titlebar.o

EX2HT_OBJS=${MIDOBJ}/ex2ht.o

HTADD_OBJS = \
	${MIDOBJ}/addfile.o ${MIDOBJ}/halloc.o  ${MIDOBJ}/hash.o \
        ${MIDOBJ}/htadd.o   ${MIDOBJ}/hterror.o ${MIDOBJ}/lex.o

HTHITS_OBJS = ${MIDOBJ}/hthits.o

SPADBUF_OBJS = ${MIDOBJ}/spadbuf.o

OBJS= \
	${HYPER_OBJS} ${EX2HT_OBJS} ${HTADD_OBJS} \
        ${HTHITS_OBJS} ${SPADBUF_OBJS} ${MIDOBJ}/debug.o

BITMAPS=${BMAPS}/mouse11.bitmap ${BMAPS}/mouse11.mask ${BMAPS}/sdown3d.bitmap \
        ${BMAPS}/sdown3dpr.bitmap ${BMAPS}/sdown.bitmap ${BMAPS}/sup3d.bitmap \
        ${BMAPS}/sup3dpr.bitmap ${BMAPS}/sup.bitmap ${BMAPS}/ht-icon

SCRIPTS=${OUTLIB}/htsearch ${OUTLIB}/presea

DOCFILES= \
	${DOC}/addfile.dvi     ${DOC}/cond.dvi        ${DOC}/debug.dvi       \
        ${DOC}/dialog.dvi      ${DOC}/display.dvi     ${DOC}/event.dvi       \
        ${DOC}/ex2ht.dvi       ${DOC}/extent1.dvi     ${DOC}/extent2.dvi     \
        ${DOC}/form-ext.dvi    ${DOC}/group.dvi       ${DOC}/halloc.dvi      \
        ${DOC}/hash.dvi        ${DOC}/htadd.dvi       ${DOC}/hterror.dvi     \
        ${DOC}/hthits.dvi      ${DOC}/htinp.dvi       ${DOC}/hyper.dvi       \
        ${DOC}/initx.dvi       ${DOC}/input.dvi       ${DOC}/item.dvi        \
        ${DOC}/keyin.dvi       ${DOC}/lex.dvi         ${DOC}/macro.dvi       \
        ${DOC}/mem.dvi         ${DOC}/parse.dvi       ${DOC}/parse-aux.dvi   \
        ${DOC}/parse-input.dvi ${DOC}/parse-paste.dvi ${DOC}/parse-types.dvi \
	${DOC}/readbitmap.dvi  ${DOC}/scrollbar.dvi   ${DOC}/show-types.dvi  \
	${DOC}/spadbuf.dvi     ${DOC}/spadint.dvi     ${DOC}/titlebar.dvi    \
        ${DOC}/bitmaps.dvi     ${DOC}/search.dvi

BINFILES= ${OUT}/hypertex ${OUT}/htadd ${OUT}/htsearch ${OUTLIB}/spadbuf \
          ${OUTLIB}/hthits ${OUTLIB}/ex2ht

@
\section{addfile}
<<addfile>>=
${MID}/addfile.h: ${IN}/addfile.pamphlet
	@ echo 1 making ${MID}/addfile.h from ${IN}/addfile.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"addfile.h" ${IN}/addfile.pamphlet >addfile.h )

${MID}/addfile.c: ${IN}/addfile.pamphlet
	@ echo 2 making ${MID}/addfile.c from ${IN}/addfile.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/addfile.pamphlet >addfile.c )

${MIDOBJ}/addfile.o: ${MID}/addfile.c 
	@ echo 3 making ${MIDOBJ}/addfile.o from ${MID}/addfile.c 
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/addfile.c )

${DOC}/addfile.dvi: ${IN}/addfile.pamphlet 
	@ echo 4 making ${DOC}/addfile.dvi from ${IN}/addfile.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/addfile.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} addfile ; \
	rm -f ${DOC}/addfile.pamphlet ; \
	rm -f ${DOC}/addfile.tex ; \
	rm -f ${DOC}/addfile )

@
\section{bitmaps}
<<bitmaps>>=
${MID}/mouse11.bitmap: ${IN}/bitmaps.pamphlet
	@echo 5 making ${BMAPS}/mouse11.bitmap from ${IN}/bitmaps.pamphlet
	@${TANGLE} -R"mouse11.bitmap" ${IN}/bitmaps.pamphlet \
           >${MID}/mouse11.bitmap

${BMAPS}/mouse11.bitmap: ${MID}/mouse11.bitmap
	@echo 5a making ${BMAPS}/mouse11.bitmap from ${MID}/mouse11.bitmap
	@cp ${MID}/mouse11.bitmap ${BMAPS}/mouse11.bitmap

${MID}/mouse11.mask: ${IN}/bitmaps.pamphlet
	@echo 6 making ${BMAPS}/mouse11.mask from ${IN}/bitmaps.pamphlet
	@${TANGLE} -R"mouse11.mask" ${IN}/bitmaps.pamphlet \
           >${MID}/mouse11.mask

${BMAPS}/mouse11.mask: ${MID}/mouse11.mask
	@echo 6a making ${BMAPS}/mouse11.mask from ${MID}/mouse11.mask
	@cp ${MID}/mouse11.mask ${BMAPS}/mouse11.mask

${MID}/sdown3d.bitmap: ${IN}/bitmaps.pamphlet
	@echo 7 making ${BMAPS}/sdown3d.bitmap from ${IN}/bitmaps.pamphlet
	@${TANGLE} -R"sdown3d.bitmap" ${IN}/bitmaps.pamphlet \
           >${MID}/sdown3d.bitmap

${BMAPS}/sdown3d.bitmap: ${MID}/sdown3d.bitmap
	@echo 7a making ${BMAPS}/sdown3d.bitmap from ${MID}/sdown3d.bitmap
	@cp ${MID}/sdown3d.bitmap ${BMAPS}/sdown3d.bitmap

${MID}/sdown3dpr.bitmap: ${IN}/bitmaps.pamphlet
	@echo 8 making ${BMAPS}/sdown3dpr.bitmap from ${IN}/bitmaps.pamphlet
	@${TANGLE} -R"sdown3dpr.bitmap" ${IN}/bitmaps.pamphlet \
           >${MID}/sdown3dpr.bitmap

${BMAPS}/sdown3dpr.bitmap: ${MID}/sdown3dpr.bitmap
	@echo 8a making ${BMAPS}/sdown3dpr.bitmap from ${MID}/sdown3dpr.bitmap
	@cp ${MID}/sdown3dpr.bitmap ${BMAPS}/sdown3dpr.bitmap

${MID}/sdown.bitmap: ${IN}/bitmaps.pamphlet
	@echo 9 making ${BMAPS}/sdown.bitmap from ${IN}/bitmaps.pamphlet
	@${TANGLE} -R"sdown.bitmap" ${IN}/bitmaps.pamphlet \
           >${MID}/sdown.bitmap

${BMAPS}/sdown.bitmap: ${MID}/sdown.bitmap
	@echo 9a making ${BMAPS}/sdown.bitmap from ${MID}/sdown.bitmap
	@cp ${MID}/sdown.bitmap ${BMAPS}/sdown.bitmap

${MID}/sup3d.bitmap: ${IN}/bitmaps.pamphlet
	@echo 10 making ${BMAPS}/sup3d.bitmap from ${IN}/bitmaps.pamphlet
	@${TANGLE} -R"sup3d.bitmap" ${IN}/bitmaps.pamphlet \
           >${MID}/sup3d.bitmap

${BMAPS}/sup3d.bitmap: ${MID}/sup3d.bitmap
	@echo 10a making ${BMAPS}/sup3d.bitmap from ${MID}/sup3d.bitmap
	@cp ${MID}/sup3d.bitmap ${BMAPS}/sup3d.bitmap

${MID}/sup3dpr.bitmap: ${IN}/bitmaps.pamphlet
	@echo 11 making ${BMAPS}/sup3dpr.bitmap from ${IN}/bitmaps.pamphlet
	@${TANGLE} -R"sup3dpr.bitmap" ${IN}/bitmaps.pamphlet \
           >${MID}/sup3dpr.bitmap

${BMAPS}/sup3dpr.bitmap: ${MID}/sup3dpr.bitmap
	@echo 11a making ${BMAPS}/sup3dpr.bitmap from ${MID}/sup3dpr.bitmap
	@cp ${MID}/sup3dpr.bitmap ${BMAPS}/sup3dpr.bitmap

${MID}/sup.bitmap: ${IN}/bitmaps.pamphlet
	@echo 12 making ${BMAPS}/sup.bitmap from ${IN}/bitmaps.pamphlet
	@${TANGLE} -R"sup.bitmap" ${IN}/bitmaps.pamphlet >${MID}/sup.bitmap

${BMAPS}/sup.bitmap: ${MID}/sup.bitmap
	@echo 12a making ${BMAPS}/sup.bitmap from ${MID}/sup.bitmap
	@cp ${MID}/sup.bitmap ${BMAPS}/sup.bitmap

${MID}/ht-icon: ${IN}/bitmaps.pamphlet
	@echo 13 making ${BMAPS}/ht-icon from ${IN}/bitmaps.pamphlet
	@${TANGLE} -R"hticon" ${IN}/bitmaps.pamphlet >${MID}/ht-icon

${BMAPS}/ht-icon: ${MID}/ht-icon
	@echo 13a making ${BMAPS}/ht-icon from ${MID}/ht-icon
	@cp ${MID}/ht-icon ${BMAPS}/ht-icon

${DOC}/bitmaps.dvi: ${IN}/bitmaps.pamphlet 
	@ echo 14 making ${DOC}/bitmaps.dvi from ${IN}/bitmaps.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/bitmaps.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} bitmaps ; \
	rm -f ${DOC}/bitmaps.pamphlet ; \
	rm -f ${DOC}/bitmaps.tex ; \
	rm -f ${DOC}/bitmaps )

@
\section{cond}
<<cond>>=
${MID}/cond.h: ${IN}/cond.pamphlet
	@ echo 15 making ${MID}/cond.h from ${IN}/cond.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"cond.h" ${IN}/cond.pamphlet >cond.h )

${MID}/cond.c: ${IN}/cond.pamphlet
	@ echo 16 making ${MID}/cond.c from ${IN}/cond.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/cond.pamphlet >cond.c )

${MIDOBJ}/cond.o: ${MID}/cond.c 
	@ echo 17 making ${MIDOBJ}/cond.o from ${MID}/cond.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/cond.c )

${DOC}/cond.dvi: ${IN}/cond.pamphlet 
	@ echo 18 making ${DOC}/cond.dvi from ${IN}/cond.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/cond.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} cond ; \
	rm -f ${DOC}/cond.pamphlet ; \
	rm -f ${DOC}/cond.tex ; \
	rm -f ${DOC}/cond )

@
\section{debug}
<<debug>>=
${MID}/debug.c: ${IN}/debug.pamphlet
	@ echo 19 making ${MID}/debug.c from ${IN}/debug.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/debug.pamphlet >debug.c )

${MIDOBJ}/debug.o: ${MID}/debug.c 
	@ echo 20 making ${MIDOBJ}/debug.o from ${MID}/debug.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/debug.c )

${DOC}/debug.dvi: ${IN}/debug.pamphlet 
	@ echo 21 making ${DOC}/debug.dvi from ${IN}/debug.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/debug.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} debug ; \
	rm -f ${DOC}/debug.pamphlet ; \
	rm -f ${DOC}/debug.tex ; \
	rm -f ${DOC}/debug )

@
\section{dialog}
<<dialog>>=
${MID}/dialog.h: ${IN}/dialog.pamphlet
	@ echo 22 making ${MID}/dialog.h from ${IN}/dialog.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"dialog.h" ${IN}/dialog.pamphlet >dialog.h )

${MID}/dialog.c: ${IN}/dialog.pamphlet
	@ echo 23 making ${MID}/dialog.c from ${IN}/dialog.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/dialog.pamphlet >dialog.c )

${MIDOBJ}/dialog.o: ${MID}/dialog.c 
	@ echo 24 making ${MIDOBJ}/dialog.o from ${MID}/dialog.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/dialog.c )

${DOC}/dialog.dvi: ${IN}/dialog.pamphlet 
	@ echo 25 making ${DOC}/dialog.dvi from ${IN}/dialog.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/dialog.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} dialog ; \
	rm -f ${DOC}/dialog.pamphlet ; \
	rm -f ${DOC}/dialog.tex ; \
	rm -f ${DOC}/dialog )

@
\section{display}
<<display>>=
${MID}/display.h: ${IN}/display.pamphlet
	@ echo 26 making ${MID}/display.h from ${IN}/display.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"display.h" ${IN}/display.pamphlet >display.h )

${MID}/display.c: ${IN}/display.pamphlet
	@ echo 27 making ${MID}/display.c from ${IN}/display.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/display.pamphlet >display.c )

${MIDOBJ}/display.o: ${MID}/display.c 
	@ echo 28 making ${MIDOBJ}/display.o from ${MID}/display.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/display.c )

${DOC}/display.dvi: ${IN}/display.pamphlet 
	@ echo 29 making ${DOC}/display.dvi from ${IN}/display.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/display.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} display ; \
	rm -f ${DOC}/display.pamphlet ; \
	rm -f ${DOC}/display.tex ; \
	rm -f ${DOC}/display )

@
\section{event}
<<event>>=
${MID}/event.h: ${IN}/event.pamphlet
	@ echo 30 making ${MID}/event.h from ${IN}/event.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"event.h" ${IN}/event.pamphlet >event.h )

${MID}/event.c: ${IN}/event.pamphlet
	@ echo 31 making ${MID}/event.c from ${IN}/event.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/event.pamphlet >event.c )

${MIDOBJ}/event.o: ${MID}/event.c
	@ echo 32 making ${MIDOBJ}/event.o from ${MID}/event.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/event.c )

${DOC}/event.dvi: ${IN}/event.pamphlet 
	@ echo 33 making ${DOC}/event.dvi from ${IN}/event.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/event.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} event ; \
	rm -f ${DOC}/event.pamphlet ; \
	rm -f ${DOC}/event.tex ; \
	rm -f ${DOC}/event )

@
\section{ex2ht}
<<ex2ht>>=
${MID}/ex2ht.c: ${IN}/ex2ht.pamphlet
	@ echo 34 making ${MID}/ex2ht.c from ${IN}/ex2ht.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/ex2ht.pamphlet >ex2ht.c )

${MIDOBJ}/ex2ht.o: ${MID}/ex2ht.c 
	@ echo 35 making ${MIDOBJ}/ex2ht.o from ${MID}/ex2ht.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/ex2ht.c )

${DOC}/ex2ht.dvi: ${IN}/ex2ht.pamphlet 
	@ echo 36 making ${DOC}/ex2ht.dvi from ${IN}/ex2ht.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/ex2ht.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} ex2ht ; \
	rm -f ${DOC}/ex2ht.pamphlet ; \
	rm -f ${DOC}/ex2ht.tex ; \
	rm -f ${DOC}/ex2ht )

@
\section{extent}
<<extent>>=
${MID}/extent.h: ${IN}/extent.pamphlet
	@ echo 37 making ${MID}/extent.h from ${IN}/extent.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"extent.h" ${IN}/extent.pamphlet >extent.h )

@
\section{extent1}
<<extent1>>=
${MID}/extent1.c: ${IN}/extent1.pamphlet
	@ echo 38 making ${MID}/extent1.c from ${IN}/extent1.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/extent1.pamphlet >extent1.c )

${MIDOBJ}/extent1.o: ${MID}/extent1.c 
	@ echo 39 making ${MIDOBJ}/extent1.o from ${MID}/extent1.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/extent1.c )

${DOC}/extent1.dvi: ${IN}/extent1.pamphlet 
	@ echo 40 making ${DOC}/extent1.dvi from ${IN}/extent1.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/extent1.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} extent1 ; \
	rm -f ${DOC}/extent1.pamphlet ; \
	rm -f ${DOC}/extent1.tex ; \
	rm -f ${DOC}/extent1 )

@
\section{extent2}
<<extent2>>=
${MID}/extent2.c: ${IN}/extent2.pamphlet
	@ echo 41 making ${MID}/extent2.c from ${IN}/extent2.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/extent2.pamphlet >extent2.c )

${MIDOBJ}/extent2.o: ${MID}/extent2.c
	@ echo 42 making ${MIDOBJ}/extent2.o from ${MID}/extent2.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/extent2.c )

${DOC}/extent2.dvi: ${IN}/extent2.pamphlet 
	@ echo 43 making ${DOC}/extent2.dvi from ${IN}/extent2.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/extent2.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} extent2 ; \
	rm -f ${DOC}/extent2.pamphlet ; \
	rm -f ${DOC}/extent2.tex ; \
	rm -f ${DOC}/extent2 )

@
\section{form-ext}
<<formext>>=
${MID}/form-ext.c: ${IN}/form-ext.pamphlet
	@ echo 44 making ${MID}/form-ext.c from ${IN}/form-ext.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/form-ext.pamphlet >form-ext.c )

${MIDOBJ}/form-ext.o: ${MID}/form-ext.c
	@ echo 45 making ${MIDOBJ}/form-ext.o from ${MID}/form-ext.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/form-ext.c )

${DOC}/form-ext.dvi: ${IN}/form-ext.pamphlet 
	@ echo 46 making ${DOC}/form-ext.dvi from ${IN}/form-ext.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/form-ext.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} form-ext ; \
	rm -f ${DOC}/form-ext.pamphlet ; \
	rm -f ${DOC}/form-ext.tex ; \
	rm -f ${DOC}/form-ext )

@
\section{group}
<<group>>=
${MID}/group.h: ${IN}/group.pamphlet
	@ echo 47 making ${MID}/group.h from ${IN}/group.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"group.h" ${IN}/group.pamphlet >group.h )

${MID}/group.c: ${IN}/group.pamphlet
	@ echo 48 making ${MID}/group.c from ${IN}/group.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/group.pamphlet >group.c )

${MIDOBJ}/group.o: ${MID}/group.c
	@ echo 49 making ${MIDOBJ}/group.o from ${MID}/group.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/group.c )

${DOC}/group.dvi: ${IN}/group.pamphlet 
	@ echo 50 making ${DOC}/group.dvi from ${IN}/group.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/group.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} group ; \
	rm -f ${DOC}/group.pamphlet ; \
	rm -f ${DOC}/group.tex ; \
	rm -f ${DOC}/group )

@
\section{halloc}
<<halloc>>=
${MID}/halloc.c: ${IN}/halloc.pamphlet
	@ echo 51 making ${MID}/halloc.c from ${IN}/halloc.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/halloc.pamphlet >halloc.c )

${MIDOBJ}/halloc.o: ${MID}/halloc.c
	@ echo 52 making ${MIDOBJ}/halloc.o from ${MID}/halloc.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/halloc.c )

${DOC}/halloc.dvi: ${IN}/halloc.pamphlet 
	@ echo 53 making ${DOC}/halloc.dvi from ${IN}/halloc.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/halloc.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} halloc ; \
	rm -f ${DOC}/halloc.pamphlet ; \
	rm -f ${DOC}/halloc.tex ; \
	rm -f ${DOC}/halloc )

@
\section{hash}
<<hash>>=
${MID}/hash.c: ${IN}/hash.pamphlet
	@ echo 54 making ${MID}/hash.c from ${IN}/hash.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/hash.pamphlet >hash.c )

${MIDOBJ}/hash.o: ${MID}/hash.c 
	@ echo 55 making ${MIDOBJ}/hash.o from ${MID}/hash.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/hash.c )

${DOC}/hash.dvi: ${IN}/hash.pamphlet 
	@ echo 56 making ${DOC}/hash.dvi from ${IN}/hash.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/hash.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} hash ; \
	rm -f ${DOC}/hash.pamphlet ; \
	rm -f ${DOC}/hash.tex ; \
	rm -f ${DOC}/hash )

@
\section{htadd}
<<htadd>>=
${MID}/htadd.c: ${IN}/htadd.pamphlet
	@ echo 57 making ${MID}/htadd.c from ${IN}/htadd.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/htadd.pamphlet >htadd.c )

${MIDOBJ}/htadd.o: ${MID}/htadd.c 
	@ echo 58 making ${MIDOBJ}/htadd.o from ${MID}/htadd.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/htadd.c )

${DOC}/htadd.dvi: ${IN}/htadd.pamphlet 
	@ echo 59 making ${DOC}/htadd.dvi from ${IN}/htadd.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/htadd.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} htadd ; \
	rm -f ${DOC}/htadd.pamphlet ; \
	rm -f ${DOC}/htadd.tex ; \
	rm -f ${DOC}/htadd )

@
\section{hterror}
<<hterror>>=
${MID}/hterror.h: ${IN}/hterror.pamphlet
	@ echo 60 making ${MID}/hterror.h from ${IN}/hterror.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"hterror.h" ${IN}/hterror.pamphlet >hterror.h )

${MID}/hterror.c: ${IN}/hterror.pamphlet
	@ echo 61 making ${MID}/hterror.c from ${IN}/hterror.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/hterror.pamphlet >hterror.c )

${MIDOBJ}/hterror.o: ${MID}/hterror.c
	@ echo 62 making ${MIDOBJ}/hterror.o from ${MID}/hterror.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/hterror.c )

${DOC}/hterror.dvi: ${IN}/hterror.pamphlet 
	@ echo 63 making ${DOC}/hterror.dvi from ${IN}/hterror.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/hterror.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} hterror ; \
	rm -f ${DOC}/hterror.pamphlet ; \
	rm -f ${DOC}/hterror.tex ; \
	rm -f ${DOC}/hterror )

@
\section{hthits}
<<hthits>>=
${MID}/hthits.c: ${IN}/hthits.pamphlet
	@ echo 64 making ${MID}/hthits.c from ${IN}/hthits.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/hthits.pamphlet >hthits.c )

${MIDOBJ}/hthits.o: ${MID}/hthits.c
	@ echo 65 making ${MIDOBJ}/hthits.o from ${MID}/hthits.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/hthits.c )

${DOC}/hthits.dvi: ${IN}/hthits.pamphlet 
	@ echo 66 making ${DOC}/hthits.dvi from ${IN}/hthits.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/hthits.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} hthits ; \
	rm -f ${DOC}/hthits.pamphlet ; \
	rm -f ${DOC}/hthits.tex ; \
	rm -f ${DOC}/hthits )

@
\section{htinp}
<<htinp>>=
${MID}/htinp.c: ${IN}/htinp.pamphlet
	@ echo 67 making ${MID}/htinp.c from ${IN}/htinp.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/htinp.pamphlet >htinp.c )

${MIDOBJ}/htinp.o: ${MID}/htinp.c
	@ echo 68 making ${MIDOBJ}/htinp.o from ${MID}/htinp.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/htinp.c )

${DOC}/htinp.dvi: ${IN}/htinp.pamphlet 
	@ echo 69 making ${DOC}/htinp.dvi from ${IN}/htinp.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/htinp.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} htinp ; \
	rm -f ${DOC}/htinp.pamphlet ; \
	rm -f ${DOC}/htinp.tex ; \
	rm -f ${DOC}/htinp )

@
\section{hyper}
<<hyper>>=
${MID}/hyper.h: ${IN}/hyper.pamphlet
	@ echo 70 making ${MID}/hyper.h from ${IN}/hyper.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"hyper.h" ${IN}/hyper.pamphlet >hyper.h )

${MID}/hyper.c: ${IN}/hyper.pamphlet
	@ echo 71 making ${MID}/hyper.c from ${IN}/hyper.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/hyper.pamphlet >hyper.c )

${MIDOBJ}/hyper.o: ${MID}/hyper.c
	@ echo 72 making ${MIDOBJ}/hyper.o from ${MID}/hyper.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/hyper.c )

${DOC}/hyper.dvi: ${IN}/hyper.pamphlet 
	@ echo 73 making ${DOC}/hyper.dvi from ${IN}/hyper.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/hyper.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} hyper ; \
	rm -f ${DOC}/hyper.pamphlet ; \
	rm -f ${DOC}/hyper.tex ; \
	rm -f ${DOC}/hyper )

@
\section{initx}
<<initx>>=
${MID}/initx.h: ${IN}/initx.pamphlet
	@ echo 74 making ${MID}/initx.h from ${IN}/initx.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"initx.h" ${IN}/initx.pamphlet >initx.h )

${MID}/initx.c: ${IN}/initx.pamphlet
	@ echo 75 making ${MID}/initx.c from ${IN}/initx.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/initx.pamphlet >initx.c )

${MIDOBJ}/initx.o: ${MID}/initx.c
	@ echo 76 making ${MIDOBJ}/initx.o from ${MID}/initx.c
	 ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/initx.c )

${DOC}/initx.dvi: ${IN}/initx.pamphlet 
	@ echo 77 making ${DOC}/initx.dvi from ${IN}/initx.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/initx.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} initx ; \
	rm -f ${DOC}/initx.pamphlet ; \
	rm -f ${DOC}/initx.tex ; \
	rm -f ${DOC}/initx )

@
\section{input}
<<input>>=
${MID}/input.c: ${IN}/input.pamphlet
	@ echo 78 making ${MID}/input.c from ${IN}/input.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/input.pamphlet >input.c )

${MIDOBJ}/input.o: ${MID}/input.c 
	@ echo 79 making ${MIDOBJ}/input.o from ${MID}/input.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/input.c )

${DOC}/input.dvi: ${IN}/input.pamphlet 
	@ echo 80 making ${DOC}/input.dvi from ${IN}/input.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/input.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} input ; \
	rm -f ${DOC}/input.pamphlet ; \
	rm -f ${DOC}/input.tex ; \
	rm -f ${DOC}/input )

@
\section{item}
<<item>>=
${MID}/item.c: ${IN}/item.pamphlet
	@ echo 81 making ${MID}/item.c from ${IN}/item.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/item.pamphlet >item.c )

${MIDOBJ}/item.o: ${MID}/item.c
	@ echo 82 making ${MIDOBJ}/item.o from ${MID}/item.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/item.c )

${DOC}/item.dvi: ${IN}/item.pamphlet 
	@ echo 83 making ${DOC}/item.dvi from ${IN}/item.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/item.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} item ; \
	rm -f ${DOC}/item.pamphlet ; \
	rm -f ${DOC}/item.tex ; \
	rm -f ${DOC}/item )

@
\section{keyin}
<<keyin>>=
${MID}/keyin.h: ${IN}/keyin.pamphlet
	@ echo 84 making ${MID}/keyin.h from ${IN}/keyin.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"keyin.h" ${IN}/keyin.pamphlet >keyin.h )

${MID}/keyin.c: ${IN}/keyin.pamphlet
	@ echo 85 making ${MID}/keyin.c from ${IN}/keyin.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/keyin.pamphlet >keyin.c )

${MIDOBJ}/keyin.o: ${MID}/keyin.c
	@ echo 86 making ${MIDOBJ}/keyin.o from ${MID}/keyin.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/keyin.c )

${DOC}/keyin.dvi: ${IN}/keyin.pamphlet 
	@ echo 87 making ${DOC}/keyin.dvi from ${IN}/keyin.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/keyin.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} keyin ; \
	rm -f ${DOC}/keyin.pamphlet ; \
	rm -f ${DOC}/keyin.tex ; \
	rm -f ${DOC}/keyin )

@
\section{lex}
<<lex>>=
${MID}/lex.h: ${IN}/lex.pamphlet
	@ echo 88 making ${MID}/lex.h from ${IN}/lex.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"lex.h" ${IN}/lex.pamphlet >lex.h )

${MID}/lex.c: ${IN}/lex.pamphlet
	@ echo 89 making ${MID}/lex.c from ${IN}/lex.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/lex.pamphlet >lex.c )

${MIDOBJ}/lex.o: ${MID}/lex.c 
	@ echo 90 making ${MIDOBJ}/lex.o from ${MID}/lex.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/lex.c )

${DOC}/lex.dvi: ${IN}/lex.pamphlet 
	@ echo 91 making ${DOC}/lex.dvi from ${IN}/lex.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/lex.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} lex ; \
	rm -f ${DOC}/lex.pamphlet ; \
	rm -f ${DOC}/lex.tex ; \
	rm -f ${DOC}/lex )

@
\section{macro}
<<macro>>=
${MID}/macro.c: ${IN}/macro.pamphlet
	@ echo 92 making ${MID}/macro.c from ${IN}/macro.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/macro.pamphlet >macro.c )

${MIDOBJ}/macro.o: ${MID}/macro.c
	@ echo 93 making ${MIDOBJ}/macro.o from ${MID}/macro.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/macro.c )

${DOC}/macro.dvi: ${IN}/macro.pamphlet 
	@ echo 94 making ${DOC}/macro.dvi from ${IN}/macro.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/macro.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} macro ; \
	rm -f ${DOC}/macro.pamphlet ; \
	rm -f ${DOC}/macro.tex ; \
	rm -f ${DOC}/macro )

@
\section{mem}
<<mem>>=
${MID}/mem.h: ${IN}/mem.pamphlet
	@ echo 95 making ${MID}/mem.h from ${IN}/mem.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"mem.h" ${IN}/mem.pamphlet >mem.h )

${MID}/mem.c: ${IN}/mem.pamphlet
	@ echo 96 making ${MID}/mem.c from ${IN}/mem.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/mem.pamphlet >mem.c )

${MIDOBJ}/mem.o: ${MID}/mem.c
	@ echo 97 making ${MIDOBJ}/mem.o from ${MID}/mem.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/mem.c )

${DOC}/mem.dvi: ${IN}/mem.pamphlet 
	@ echo 98 making ${DOC}/mem.dvi from ${IN}/mem.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/mem.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} mem ; \
	rm -f ${DOC}/mem.pamphlet ; \
	rm -f ${DOC}/mem.tex ; \
	rm -f ${DOC}/mem )

@
\section{parse}
<<parse>>=
${MID}/parse.h: ${IN}/parse.pamphlet
	@ echo 99 making ${MID}/parse.h from ${IN}/parse.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"parse.h" ${IN}/parse.pamphlet >parse.h )

${MID}/parse.c: ${IN}/parse.pamphlet
	@ echo 100 making ${MID}/parse.c from ${IN}/parse.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/parse.pamphlet >parse.c )

${MIDOBJ}/parse.o: ${MID}/parse.c
	@ echo 101 making ${MIDOBJ}/parse.o from ${MID}/parse.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/parse.c )

${DOC}/parse.dvi: ${IN}/parse.pamphlet 
	@ echo 102 making ${DOC}/parse.dvi from ${IN}/parse.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/parse.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} parse ; \
	rm -f ${DOC}/parse.pamphlet ; \
	rm -f ${DOC}/parse.tex ; \
	rm -f ${DOC}/parse )

@
\section{parse-aux}
<<parseaux>>=
${MID}/parse-aux.h: ${IN}/parse-aux.pamphlet
	@ echo 103 making ${MID}/parse-aux.h from ${IN}/parse-aux.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"parseaux.h" ${IN}/parse-aux.pamphlet >parse-aux.h )

${MID}/parse-aux.c: ${IN}/parse-aux.pamphlet
	@ echo 104 making ${MID}/parse-aux.c from ${IN}/parse-aux.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/parse-aux.pamphlet >parse-aux.c )

${MIDOBJ}/parse-aux.o: ${MID}/parse-aux.c
	@ echo 105 making ${MIDOBJ}/parse-aux.o from ${MID}/parse-aux.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/parse-aux.c )

${DOC}/parse-aux.dvi: ${IN}/parse-aux.pamphlet 
	@ echo 106 making ${DOC}/parse-aux.dvi from ${IN}/parse-aux.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/parse-aux.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} parse-aux ; \
	rm -f ${DOC}/parse-aux.pamphlet ; \
	rm -f ${DOC}/parse-aux.tex ; \
	rm -f ${DOC}/parse-aux )

@
\section{parse-input}
<<parseinput>>=
${MID}/parse-input.c: ${IN}/parse-input.pamphlet
	@ echo 107 making ${MID}/parse-input.c from ${IN}/parse-input.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/parse-input.pamphlet >parse-input.c )

${MIDOBJ}/parse-input.o: ${MID}/parse-input.c
	@ echo 108 making ${MIDOBJ}/parse-input.o from ${MID}/parse-input.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/parse-input.c )

${DOC}/parse-input.dvi: ${IN}/parse-input.pamphlet 
	@ echo 109 making ${DOC}/parse-input.dvi \
           from ${IN}/parse-input.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/parse-input.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} parse-input ; \
	rm -f ${DOC}/parse-input.pamphlet ; \
	rm -f ${DOC}/parse-input.tex ; \
	rm -f ${DOC}/parse-input )

@
\section{parse-paste}
<<parsepaste>>=
${MID}/parse-paste.h: ${IN}/parse-paste.pamphlet
	@ echo 110 making ${MID}/parse-paste.h from ${IN}/parse-paste.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"parsepaste.h" ${IN}/parse-paste.pamphlet >parse-paste.h )

${MID}/parse-paste.c: ${IN}/parse-paste.pamphlet
	@ echo 111 making ${MID}/parse-paste.c from ${IN}/parse-paste.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/parse-paste.pamphlet >parse-paste.c )

${MIDOBJ}/parse-paste.o: ${MID}/parse-paste.c
	@ echo 112 making ${MIDOBJ}/parse-paste.o from ${MID}/parse-paste.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/parse-paste.c )

${DOC}/parse-paste.dvi: ${IN}/parse-paste.pamphlet 
	@ echo 113 making ${DOC}/parse-paste.dvi \
           from ${IN}/parse-paste.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/parse-paste.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} parse-paste ; \
	rm -f ${DOC}/parse-paste.pamphlet ; \
	rm -f ${DOC}/parse-paste.tex ; \
	rm -f ${DOC}/parse-paste )

@
\section{parse-types}
<<parsetypes>>=
${MID}/parse-types.h: ${MID}/hterror.h ${IN}/parse-types.pamphlet
	@ echo 114 making ${MID}/parse-types.h from ${IN}/parse-types.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"parsetypes.h" ${IN}/parse-types.pamphlet >parse-types.h )

${MID}/parse-types.c: ${IN}/parse-types.pamphlet
	@ echo 115 making ${MID}/parse-types.c from ${IN}/parse-types.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/parse-types.pamphlet >parse-types.c )

${MIDOBJ}/parse-types.o: ${MID}/parse-types.c
	@ echo 116 making ${MIDOBJ}/parse-types.o from ${MID}/parse-types.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/parse-types.c )

${DOC}/parse-types.dvi: ${IN}/parse-types.pamphlet 
	@ echo 117 making ${DOC}/parse-types.dvi \
           from ${IN}/parse-types.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/parse-types.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} parse-types ; \
	rm -f ${DOC}/parse-types.pamphlet ; \
	rm -f ${DOC}/parse-types.tex ; \
	rm -f ${DOC}/parse-types )

@
\section{readbitmap}
<<readbitmap>>=
${MID}/readbitmap.c: ${IN}/readbitmap.pamphlet
	@ echo 118 making ${MID}/readbitmap.c from ${IN}/readbitmap.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/readbitmap.pamphlet >readbitmap.c )

${MIDOBJ}/readbitmap.o: ${MID}/readbitmap.c
	@ echo 119 making ${MIDOBJ}/readbitmap.o from ${MID}/readbitmap.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/readbitmap.c )

${DOC}/readbitmap.dvi: ${IN}/readbitmap.pamphlet 
	@ echo 120 making ${DOC}/readbitmap.dvi from ${IN}/readbitmap.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/readbitmap.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} readbitmap ; \
	rm -f ${DOC}/readbitmap.pamphlet ; \
	rm -f ${DOC}/readbitmap.tex ; \
	rm -f ${DOC}/readbitmap )

@
\section{scrollbar}
<<scrollbar>>=
${MID}/scrollbar.h: ${IN}/scrollbar.pamphlet
	@ echo 121 making ${MID}/scrollbar.h from ${IN}/scrollbar.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"scrollbar.h" ${IN}/scrollbar.pamphlet >scrollbar.h )

${MID}/scrollbar.c: ${IN}/scrollbar.pamphlet
	@ echo 122 making ${MID}/scrollbar.c from ${IN}/scrollbar.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/scrollbar.pamphlet >scrollbar.c )

${MIDOBJ}/scrollbar.o: ${MID}/scrollbar.c
	@ echo 123 making ${MIDOBJ}/scrollbar.o from ${MID}/scrollbar.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/scrollbar.c )

${DOC}/scrollbar.dvi: ${IN}/scrollbar.pamphlet 
	@ echo 124 making ${DOC}/scrollbar.dvi from ${IN}/scrollbar.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/scrollbar.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} scrollbar ; \
	rm -f ${DOC}/scrollbar.pamphlet ; \
	rm -f ${DOC}/scrollbar.tex ; \
	rm -f ${DOC}/scrollbar )

@
\section{search}
<<search>>=
${OUTLIB}/htsearch: ${IN}/search.pamphlet
	@echo 125 making ${OUTLIB}/htsearch from ${IN}/search.pamphlet
	@${TANGLE} -R"htsearch" ${IN}/search.pamphlet >${OUTLIB}/htsearch
	@chmod a+x ${OUTLIB}/htsearch

${OUTLIB}/presea: ${IN}/search.pamphlet
	@echo 126 making ${OUTLIB}/presea from ${IN}/search.pamphlet
	@${TANGLE} -R"presea" ${IN}/search.pamphlet >${OUTLIB}/presea
	@chmod a+x ${OUTLIB}/presea

${DOC}/search.dvi: ${IN}/search.pamphlet 
	@ echo 127 making ${DOC}/search.dvi from ${IN}/search.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/search.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} search ; \
	rm -f ${DOC}/search.pamphlet ; \
	rm -f ${DOC}/search.tex ; \
	rm -f ${DOC}/search )

@
\section{show-types}
<<showtypes>>=
${MID}/show-types.h: ${IN}/show-types.pamphlet
	@ echo 128 making ${MID}/show-types.h from ${IN}/show-types.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"showtypes.h" ${IN}/show-types.pamphlet >show-types.h )

${MID}/show-types.c: ${IN}/show-types.pamphlet
	@ echo 129 making ${MID}/show-types.c from ${IN}/show-types.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/show-types.pamphlet >show-types.c )

${MIDOBJ}/show-types.o: ${MID}/show-types.c
	@ echo 130 making ${MIDOBJ}/show-types.o from ${MID}/show-types.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/show-types.c )

${DOC}/show-types.dvi: ${IN}/show-types.pamphlet 
	@ echo 131 making ${DOC}/show-types.dvi from ${IN}/show-types.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/show-types.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} show-types ; \
	rm -f ${DOC}/show-types.pamphlet ; \
	rm -f ${DOC}/show-types.tex ; \
	rm -f ${DOC}/show-types )

@
\section{spadbuf}
<<spadbuf>>=
${MID}/spadbuf.c: ${IN}/spadbuf.pamphlet
	@ echo 132 making ${MID}/spadbuf.c from ${IN}/spadbuf.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/spadbuf.pamphlet >spadbuf.c )

${MIDOBJ}/spadbuf.o: ${MID}/spadbuf.c
	@ echo 133 making ${MIDOBJ}/spadbuf.o from ${MID}/spadbuf.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/spadbuf.c )

${DOC}/spadbuf.dvi: ${IN}/spadbuf.pamphlet 
	@ echo 134 making ${DOC}/spadbuf.dvi from ${IN}/spadbuf.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/spadbuf.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} spadbuf ; \
	rm -f ${DOC}/spadbuf.pamphlet ; \
	rm -f ${DOC}/spadbuf.tex ; \
	rm -f ${DOC}/spadbuf )

@
\section{spadint}
<<spadint>>=
${MID}/spadint.c: ${IN}/spadint.pamphlet
	@ echo 135 making ${MID}/spadint.c from ${IN}/spadint.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/spadint.pamphlet >spadint.c )

${MIDOBJ}/spadint.o: ${MID}/spadint.c
	@ echo 136 making ${MIDOBJ}/spadint.o from ${MID}/spadint.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/spadint.c )

${DOC}/spadint.dvi: ${IN}/spadint.pamphlet 
	@ echo 137 making ${DOC}/spadint.dvi from ${IN}/spadint.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/spadint.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} spadint ; \
	rm -f ${DOC}/spadint.pamphlet ; \
	rm -f ${DOC}/spadint.tex ; \
	rm -f ${DOC}/spadint )

@
\section{titlebar}
<<titlebar>>=
${MID}/titlebar.h: ${IN}/titlebar.pamphlet
	@ echo 138 making ${MID}/titlebar.h from ${IN}/titlebar.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"titlebar.h" ${IN}/titlebar.pamphlet >titlebar.h )

${MID}/titlebar.c: ${IN}/titlebar.pamphlet
	@ echo 139 making ${MID}/titlebar.c from ${IN}/titlebar.pamphlet
	@ (cd ${MID} ; ${TANGLE} ${IN}/titlebar.pamphlet >titlebar.c )

${MIDOBJ}/titlebar.o: ${MID}/titlebar.c
	@ echo 140 making ${MIDOBJ}/titlebar.o from ${MID}/titlebar.c
	@ ( cd ${MIDOBJ} ; \
	    ${CC} -I${INC} -I${MID} -c ${CFLAGS} ${MID}/titlebar.c )

${DOC}/titlebar.dvi: ${IN}/titlebar.pamphlet 
	@ echo 141 making ${DOC}/titlebar.dvi from ${IN}/titlebar.pamphlet
	@ (cd ${DOC} ; \
	cp ${IN}/titlebar.pamphlet ${DOC} ; \
	${DOCUMENT} ${NOISE} titlebar ; \
	rm -f ${DOC}/titlebar.pamphlet ; \
	rm -f ${DOC}/titlebar.tex ; \
	rm -f ${DOC}/titlebar )

@
\section{token}
<<token>>=
${MID}/token.h: ${IN}/token.pamphlet
	@ echo 142 making ${MID}/token.h from ${IN}/token.pamphlet
	@ (cd ${MID} ; ${TANGLE} -R"token.h" ${IN}/token.pamphlet >token.h )

@
\section{ex2ht binary}
<<ex2ht (BIN)>>=
${OUTLIB}/ex2ht: ${EX2HT_OBJS} 
	@ echo 143 linking ${OUTLIB}/ex2ht
	@ ${CC} ${EX2HT_OBJS} -o ${OUTLIB}/ex2ht ${LDFLAGS}

@
\section{htadd binary}
<<htadd (BIN)>>=
${OUT}/htadd: ${HTADD_OBJS}   ${LIB}/sockio-c.o ${LIB}/bsdsignal.o
	@ echo 144 linking ${OUT}/htadd
	@ ${CC} ${HTADD_OBJS} -o ${OUT}/htadd ${LIB}/sockio-c.o \
                ${LIB}/bsdsignal.o ${LDFLAGS}

@
\section{hthits binary}
<<hthits (BIN)>>=
${OUTLIB}/hthits: ${HTHITS_OBJS} 
	@ echo 145 linking ${OUTLIB}/hthits
	@ ${CC} ${HTHITS_OBJS} -o ${OUTLIB}/hthits ${LDFLAGS}

@
\section{hypertex binary}
<<hypertex (BIN)>>=
${OUT}/hypertex: ${HYPER_OBJS} ${LIB}/sockio-c.o ${LIB}/pixmap.o \
                    ${LIB}/spadcolors.o ${LIB}/util.o ${LIB}/bsdsignal.o
	@ echo 146 linking ${OUT}/hypertex
	 (cd ${OUT} ; \
	 ${CC} -g ${HYPER_OBJS} -o ${OUT}/hypertex ${LIB}/sockio-c.o \
	   ${LIB}/pixmap.o ${LIB}/spadcolors.o ${LIB}/util.o \
           ${LIB}/bsdsignal.o ${LDFLAGS} -lX11 -lm -L${LIB} )

@
\section{htsearch binary}
<<htsearch (BIN)>>=
${OUT}/htsearch: ${OUTLIB}/htsearch ${OUTLIB}/presea
	@ echo 147 making ${OUT}/htsearch
	@ cp -p ${OUTLIB}/htsearch ${OUT}/htsearch
	@ cp -p ${OUTLIB}/presea ${OUT}/presea

@
\section{spadbuf binary}
<<spadbuf (BIN)>>=
${OUTLIB}/spadbuf: ${SPADBUF_OBJS} ${LIB}/sockio-c.o ${LIB}/bsdsignal.o \
                   ${LIB}/wct.o ${LIB}/edin.o ${LIB}/prt.o ${LIB}/cursor.o \
                   ${LIB}/fnct-key.o
	@ echo 148 making ${OUTLIB}/spadbuf
	@ (cd ${OUTLIB} ; \
	   ${CC} ${SPADBUF_OBJS} -o ${OUTLIB}/spadbuf ${LIB}/sockio-c.o \
	         ${LIB}/bsdsignal.o ${LIB}/wct.o ${LIB}/edin.o ${LIB}/prt.o \
	         ${LIB}/cursor.o ${LIB}/fnct-key.o ${LDFLAGS} )

@
\section{pages}
We need to make sure that [[ht.db]], the hypertex database file
is up to date. The file contains absolute offsets into the various
[[ht]] and [[pht]] files so it must reflect the current pages. In
order to do this we run [[htadd]] in the [[${PAGES}]] directory.

The BMAPS directory holds the bitmaps for hyperdoc.
<<pages>>=
${PAGES}/ht.db: ${IN}/pages/*.ht ${IN}/pages/*.pht
	@echo 149 making ${PAGES} from ${SRC}/pages directory
	@ mkdir -p ${PAGES}
	@ mkdir -p ${BMAPS}
	@ cp -pr pages/*.ht ${PAGES}
	@ cp -pr pages/*.pht ${PAGES}
	@ (cd ${PAGES} ; \
           rm -f ht.db ; \
           rm -f *~ ; \
	   ${HTADD} *.ht *.pht )
	@ cp -pr bitmaps ${HYPER}
	@ cp -pr viewports ${MNT}/${SYS}/doc

@
<<browse>>=
${HYPER}/rootpage.xhtml: ${IN}/bookvol11.pamphlet
	@ echo 150 making ${HYPER}/xhtml from ${IN}/bookvol11.pamphlet
	( cd ${HYPER} ; \
          cp ${IN}/bookvol11.pamphlet . ; \
          ${TANGLE} -t8 bookvol11.pamphlet >Makefile.pages ; \
          make -j 10 -f Makefile.pages ; \
          rm -f Makefile.pages ; \
          rm -f bookvol11.pamphlet )

${HYPER}/bigbayou.png: ${IN}/bigbayou.png
	@ echo 151 making ${HYPER}/bigbayou.png from ${IN}/bigbayou.png
	@ cp ${IN}/bigbayou.png ${HYPER}/bigbayou.png

${HYPER}/doctitle.png: ${IN}/doctitle.png
	@ echo 152 making ${HYPER}/doctitle.png from ${IN}/doctitle.png
	@ cp ${IN}/doctitle.png ${HYPER}/doctitle.png

${MNT}/${SYS}/doc/bookvol11.dvi: ${IN}/bookvol11.pamphlet 
	@ echo 153 making ${MNT}/${SYS}/doc/bookvol11.dvi \
            from ${IN}/bookvol11.pamphlet
	@ ( cd ${MNT}/${SYS}/doc ; \
	    cp ${IN}/bookvol11.pamphlet . ; \
	    ${DOCUMENT} ${NOISE} bookvol11 ; \
	    rm -f bookvol11.pamphlet ; \
	    rm -f bookvol11.tex ; \
	    rm -f bookvol11.idx ; \
	    rm -f bookvol11 )

@
<<axbook>>=
${HYPER}/axbook: ${IN}/axbook.tgz
	@ echo 154 making ${HYPER}/axbook/xhtml from ${IN}/axbook.tgz
	@( cd ${HYPER} ; tar -zxf ${IN}/axbook.tgz )

@
The original hyperdoc pages live in the PAGES directory and the BITMAPS live
under the PAGES directory.

The browser pages are tangled from the file bookvol11 and live in HYPER. 
The mathML version of the Jenks book lives in HYPER/axbook.
The bigbayou and doctitle images are used by the new browser.
<<*>>=
<<environment>>
all: ${INCLUDES} ${BITMAPS} ${OBJS} ${SCRIPTS} ${BINFILES} \
     ${PAGES}/ht.db ${DOCFILES} ${HYPER}/rootpage.xhtml \
     ${HYPER}/axbook ${MNT}/${SYS}/doc/bookvol11.dvi \
     ${HYPER}/bigbayou.png ${HYPER}/doctitle.png
	@ echo 155 finished ${IN}

clean:
	@echo 156 cleaning ${SRC}/hyper

<<browse>>
<<axbook>>

<<addfile>>
<<bitmaps>>
<<cond>>
<<debug>>
<<dialog>>
<<display>>
<<event>>
<<ex2ht>>
<<extent>>
<<extent1>>
<<extent2>>
<<formext>>
<<group>>
<<halloc>>
<<hash>>
<<htadd>>
<<hterror>>
<<hthits>>
<<htinp>>
<<hyper>>
<<initx>>
<<input>>
<<item>>
<<keyin>>
<<lex>>
<<macro>>
<<mem>>
<<pages>>
<<parse>>
<<parseaux>>
<<parseinput>>
<<parsepaste>>
<<parsetypes>>
<<readbitmap>>
<<scrollbar>>
<<search>>
<<showtypes>>
<<spadbuf>>
<<spadint>>
<<titlebar>>
<<token>>

<<ex2ht (BIN)>>
<<htadd (BIN)>>
<<hthits (BIN)>>
<<htsearch (BIN)>>

<<hypertex (BIN)>>
<<spadbuf (BIN)>>

@
\eject
\begin{thebibliography}{99}
\bibitem{1} nothing
\end{thebibliography}
\end{document}
